/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 720
Dataflow Name: Full Enforcement Dataflow
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 26
  Successful: 26
  Failed: 0
  Unique Action Types: 7
  Action Types: ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, Metadata, PublishToVault
  Pipelines: 5

Generated: 2025-07-02 10:26:10
================================================================================
*/

WITH _Full_Limit_Buster_Inventory_DS AS (
  SELECT `sales_country_id`, `revenue`, `asins units`, `revenue brand`, `asins units brand`, `Percent Mix of Brand`, `Revenue Rank R3MTH`, `Revenue Distribution R3MTH`, `scraped_date`, `amazonID`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `Brand`, `isFBA`, `upc`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `cod_condition`, `unit_in_listing`, `bp_brand_id`, `asin_bp_enforceable`, `country`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS` FROM Full_Limit_Buster_Inventory_DS
),

_BP_PlatformNotices_Sent AS (
  SELECT `Staff`, `Brand`, `Storefront ID`, `storefront_name`, `ASIN`, `Date of First Message`, `Complaint Date`, `Complaint ID`, `Message`, `Column_10` FROM BP_PlatformNotices_Sent
),

_bp_enforcements AS (
  SELECT `Staff`, `Partner`, `Brand`, `marketplace_channel_id`, `marketplace_channel`, `country_id`, `country`, `Storefront ID`, `storefront_name`, `Date`, `Type`, `Notes/Comments`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Response Received`, `Order Cost`, `USPS Tracking Type`, `Recipient Address`, `Delivered City`, `ERROR_STATUS`, `RunDateTime`, `return Receipt Downloaded?`, `enforce_by_brand`, `enforce_by`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM bp_enforcements
),

_Keepa_Suppression_Status_Airtable AS (
  SELECT * FROM Keepa_Suppression_Status_Airtable
),

_UPCs AS (
  SELECT `brand_id`, `cases_per_layer`, `cases_per_pallet`, `catalog_source`, `client_id`, `cost`, `created_at`, `created_by`, `default_cost`, `default_discount`, `deleted_at`, `deleted_by`, `id`, `hero`, `map`, `min_order_qty`, `name`, `old_upc`, `parent_upc`, `reorder_comments`, `reorder_status`, `srp`, `unit_lxwxh_inches`, `unit_weight_lb`, `units_per_case`, `upc`, `updated_at`, `updated_by`, `vendor_sku`, `wholesale_price`, `is_discontinued_status`, `amazon_seller_id`, `unit_count_type_id`, `unit_count`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM UPCs
),

_Max_Units AS (
  SELECT `Brand`, `sellerId`, MAX(`Units`) AS `Max Units` FROM _Full_Limit_Buster_Inventory_DS GROUP BY `Brand`, `sellerId`
),

_Join_Data_6 AS (
  SELECT _bp_enforcements.`Staff`, _bp_enforcements.`Partner`, _bp_enforcements.`Brand`, _bp_enforcements.`marketplace_channel_id`, _bp_enforcements.`marketplace_channel`, _bp_enforcements.`country_id`, _bp_enforcements.`country`, _bp_enforcements.`Storefront ID`, _bp_enforcements.`storefront_name`, _bp_enforcements.`Date`, _bp_enforcements.`Type`, _bp_enforcements.`Notes/Comments`, _bp_enforcements.`Invoice ID`, _bp_enforcements.`Job ID`, _bp_enforcements.`USPS Tracking`, _bp_enforcements.`Delivery Status`, _bp_enforcements.`Delivery Date`, _bp_enforcements.`Response Received`, _bp_enforcements.`Order Cost`, _bp_enforcements.`USPS Tracking Type`, _bp_enforcements.`Recipient Address`, _bp_enforcements.`Delivered City`, _bp_enforcements.`ERROR_STATUS`, _bp_enforcements.`RunDateTime`, _bp_enforcements.`return Receipt Downloaded?`, _bp_enforcements.`enforce_by_brand`, _bp_enforcements.`enforce_by`, _bp_enforcements.`_BATCH_ID_`, _bp_enforcements.`_BATCH_LAST_RUN_`, _BP_PlatformNotices_Sent.`ASIN`, _BP_PlatformNotices_Sent.`Date of First Message`, _BP_PlatformNotices_Sent.`Complaint Date`, _BP_PlatformNotices_Sent.`Complaint ID`, _BP_PlatformNotices_Sent.`Message`, _BP_PlatformNotices_Sent.`Column_10` FROM _bp_enforcements LEFT JOIN _BP_PlatformNotices_Sent ON _bp_enforcements.`Brand` = _BP_PlatformNotices_Sent.`Brand` AND _bp_enforcements.`Storefront ID` = _BP_PlatformNotices_Sent.`Storefront ID`
),

_Filter_Rows AS (
  SELECT * FROM _bp_enforcements WHERE `Type` = 'Cease & Desist'
),

_Add_Formula_1 AS (
  SELECT *, (case when `Country` = 'USA' then 1 when `Country` = 'Canada' then 2 when `Country` = 'UK' then 3 when `Country` = 'France' then 4 when `Country` = 'Italy' then 5 when `Country` = 'Germany' then 6 when `Country` = 'Spain' then 7 when `Country` = 'Netherlands' then 8 when `Country` = 'Poland' then 9 when `Country` = 'Sweden' then 10 when `Country` = 'Belgium' then 11 else 0 end) AS `Country ID` FROM _Keepa_Suppression_Status_Airtable
),

_Fix_Vendor_SKU AS (
  SELECT `brand_id`, `cases_per_layer`, `cases_per_pallet`, `catalog_source`, `client_id`, `cost`, `created_at`, `created_by`, `default_cost`, `default_discount`, `deleted_at`, `deleted_by`, `id`, `hero`, `map`, `min_order_qty`, `name`, `old_upc`, `parent_upc`, `reorder_comments`, `reorder_status`, `srp`, `unit_lxwxh_inches`, `unit_weight_lb`, `units_per_case`, `upc`, `updated_at`, `updated_by`, `vendor_sku`, `wholesale_price`, `is_discontinued_status`, `amazon_seller_id`, `unit_count_type_id`, `unit_count`, `_BATCH_ID_`, `_BATCH_LAST_RUN_`, (CASE when `brand_id` IN (75,601,602,1270,1936) AND LENGTH(`vendor_sku`) >= 5 then null else `vendor_sku` END) AS `Vendor_SKU_Corrected` FROM _UPCs
),

_Join_Data_7 AS (
  SELECT _Max_Units.`Max Units`, _Full_Limit_Buster_Inventory_DS.`sales_country_id`, _Full_Limit_Buster_Inventory_DS.`revenue`, _Full_Limit_Buster_Inventory_DS.`asins units`, _Full_Limit_Buster_Inventory_DS.`revenue brand`, _Full_Limit_Buster_Inventory_DS.`asins units brand`, _Full_Limit_Buster_Inventory_DS.`Percent Mix of Brand`, _Full_Limit_Buster_Inventory_DS.`Revenue Rank R3MTH`, _Full_Limit_Buster_Inventory_DS.`Revenue Distribution R3MTH`, _Full_Limit_Buster_Inventory_DS.`scraped_date`, _Full_Limit_Buster_Inventory_DS.`amazonID`, _Full_Limit_Buster_Inventory_DS.`sellerId`, _Full_Limit_Buster_Inventory_DS.`sellerName`, _Full_Limit_Buster_Inventory_DS.`storefront_name`, _Full_Limit_Buster_Inventory_DS.`asin`, _Full_Limit_Buster_Inventory_DS.`isQuantityRestricted`, _Full_Limit_Buster_Inventory_DS.`Brand`, _Full_Limit_Buster_Inventory_DS.`isFBA`, _Full_Limit_Buster_Inventory_DS.`upc`, _Full_Limit_Buster_Inventory_DS.`upc_name`, _Full_Limit_Buster_Inventory_DS.`msrp`, _Full_Limit_Buster_Inventory_DS.`srp`, _Full_Limit_Buster_Inventory_DS.`map`, _Full_Limit_Buster_Inventory_DS.`parent_category`, _Full_Limit_Buster_Inventory_DS.`child_category`, _Full_Limit_Buster_Inventory_DS.`child_category_2`, _Full_Limit_Buster_Inventory_DS.`child_category_3`, _Full_Limit_Buster_Inventory_DS.`partner name`, _Full_Limit_Buster_Inventory_DS.`country_id`, _Full_Limit_Buster_Inventory_DS.`offer_price`, _Full_Limit_Buster_Inventory_DS.`offer_date_max_price`, _Full_Limit_Buster_Inventory_DS.`Units`, _Full_Limit_Buster_Inventory_DS.`Limit Buster Units`, _Full_Limit_Buster_Inventory_DS.`redirect_asin`, _Full_Limit_Buster_Inventory_DS.`created_date`, _Full_Limit_Buster_Inventory_DS.`created_time`, _Full_Limit_Buster_Inventory_DS.`sku_map`, _Full_Limit_Buster_Inventory_DS.`sku_name`, _Full_Limit_Buster_Inventory_DS.`buy_box_count`, _Full_Limit_Buster_Inventory_DS.`Partner - Brand`, _Full_Limit_Buster_Inventory_DS.`cod_condition`, _Full_Limit_Buster_Inventory_DS.`unit_in_listing`, _Full_Limit_Buster_Inventory_DS.`bp_brand_id`, _Full_Limit_Buster_Inventory_DS.`asin_bp_enforceable`, _Full_Limit_Buster_Inventory_DS.`country`, _Full_Limit_Buster_Inventory_DS.`BBC_ORIGINAL_STATUS`, _Full_Limit_Buster_Inventory_DS.`BBC_2_8_22_STATUS` FROM _Max_Units INNER JOIN _Full_Limit_Buster_Inventory_DS ON _Max_Units.`Brand` = _Full_Limit_Buster_Inventory_DS.`Brand` AND _Max_Units.`sellerId` = _Full_Limit_Buster_Inventory_DS.`sellerId` AND _Max_Units.`Max Units` = _Full_Limit_Buster_Inventory_DS.`Units`
),

_Group_By_5 AS (
  SELECT `Brand`, `Storefront ID`, MAX(`Date`) AS `C&D Date` FROM _Filter_Rows GROUP BY `Brand`, `Storefront ID`
),

_Alter_Columns AS (
  SELECT `Map` AS `Map Airtable`, `Country ID` FROM _Add_Formula_1
),

_Group_by_UPC AS (
  SELECT `upc`, MAX(`Vendor_SKU_Corrected`) AS `vendor_code`, MAX(`map`) AS `catalog_map` FROM _Fix_Vendor_SKU GROUP BY `upc`
),

_ASIN_with_highest_inventory AS (
  SELECT `Max Units`, `sellerId`, `Brand`, `sales_country_id`, MIN(`asin`) AS `ASIN with highest inventory` FROM _Join_Data_7 GROUP BY `Max Units`, `sellerId`, `Brand`, `sales_country_id`
),

_Join_Data_9 AS (
  SELECT _Join_Data_6.`Staff`, _Join_Data_6.`Brand`, _Join_Data_6.`Storefront ID`, _Join_Data_6.`storefront_name`, _Join_Data_6.`ASIN`, _Join_Data_6.`Date of First Message`, _Join_Data_6.`Complaint Date`, _Join_Data_6.`Complaint ID`, _Join_Data_6.`Message`, _Join_Data_6.`Column_10`, _Join_Data_6.`Partner`, _Join_Data_6.`marketplace_channel_id`, _Join_Data_6.`marketplace_channel`, _Join_Data_6.`country_id`, _Join_Data_6.`country`, _Join_Data_6.`Date`, _Join_Data_6.`Type`, _Join_Data_6.`Notes/Comments`, _Join_Data_6.`Invoice ID`, _Join_Data_6.`Job ID`, _Join_Data_6.`USPS Tracking`, _Join_Data_6.`Delivery Status`, _Join_Data_6.`Delivery Date`, _Join_Data_6.`Response Received`, _Join_Data_6.`Order Cost`, _Join_Data_6.`USPS Tracking Type`, _Join_Data_6.`Recipient Address`, _Join_Data_6.`Delivered City`, _Join_Data_6.`ERROR_STATUS`, _Join_Data_6.`RunDateTime`, _Join_Data_6.`return Receipt Downloaded?`, _Join_Data_6.`enforce_by_brand`, _Join_Data_6.`enforce_by`, _Join_Data_6.`_BATCH_ID_`, _Join_Data_6.`_BATCH_LAST_RUN_`, _Group_By_5.`C&D Date` FROM _Join_Data_6 LEFT JOIN _Group_By_5 ON _Join_Data_6.`Brand` = _Group_By_5.`Brand` AND _Join_Data_6.`Storefront ID` = _Group_By_5.`Storefront ID`
),

_Group_By AS (
  SELECT `Brand`, `Storefront ID`, MAX(`Type`) AS `Last Notice Type`, MAX(`Date`) AS `Last Notice Sent`, MAX(`Notes/Comments`) AS `Last Note`, MAX(`Invoice ID`) AS `Invoice ID`, MAX(`Job ID`) AS `Job ID`, MAX(`USPS Tracking`) AS `USPS Tracking`, MAX(`Delivery Status`) AS `Delivery Status`, MAX(`Delivery Date`) AS `Delivery Date`, GROUP_CONCAT(`Type`) AS `Enforcement History`, MAX(`ERROR_STATUS`) AS `C2M ERROR_STATUS`, MAX(`Recipient Address`) AS `Recipient Address`, MAX(`Date of First Message`) AS `Platform Sent?`, GROUP_CONCAT(`Notes/Comments`) AS `Notes`, MAX(`C&D Date`) AS `C&D Date` FROM _Join_Data_9 GROUP BY `Brand`, `Storefront ID`
),

_Join_Data AS (
  SELECT _Full_Limit_Buster_Inventory_DS.`sales_country_id`, _Full_Limit_Buster_Inventory_DS.`revenue`, _Full_Limit_Buster_Inventory_DS.`asins units`, _Full_Limit_Buster_Inventory_DS.`revenue brand`, _Full_Limit_Buster_Inventory_DS.`asins units brand`, _Full_Limit_Buster_Inventory_DS.`Percent Mix of Brand`, _Full_Limit_Buster_Inventory_DS.`Revenue Rank R3MTH`, _Full_Limit_Buster_Inventory_DS.`Revenue Distribution R3MTH`, _Full_Limit_Buster_Inventory_DS.`scraped_date`, _Full_Limit_Buster_Inventory_DS.`amazonID`, _Full_Limit_Buster_Inventory_DS.`sellerId`, _Full_Limit_Buster_Inventory_DS.`sellerName`, _Full_Limit_Buster_Inventory_DS.`storefront_name`, _Full_Limit_Buster_Inventory_DS.`asin`, _Full_Limit_Buster_Inventory_DS.`isQuantityRestricted`, _Full_Limit_Buster_Inventory_DS.`Brand`, _Full_Limit_Buster_Inventory_DS.`isFBA`, _Full_Limit_Buster_Inventory_DS.`upc`, _Full_Limit_Buster_Inventory_DS.`upc_name`, _Full_Limit_Buster_Inventory_DS.`msrp`, _Full_Limit_Buster_Inventory_DS.`srp`, _Full_Limit_Buster_Inventory_DS.`map`, _Full_Limit_Buster_Inventory_DS.`parent_category`, _Full_Limit_Buster_Inventory_DS.`child_category`, _Full_Limit_Buster_Inventory_DS.`child_category_2`, _Full_Limit_Buster_Inventory_DS.`child_category_3`, _Full_Limit_Buster_Inventory_DS.`partner name`, _Full_Limit_Buster_Inventory_DS.`country_id`, _Full_Limit_Buster_Inventory_DS.`offer_price`, _Full_Limit_Buster_Inventory_DS.`offer_date_max_price`, _Full_Limit_Buster_Inventory_DS.`Units`, _Full_Limit_Buster_Inventory_DS.`Limit Buster Units`, _Full_Limit_Buster_Inventory_DS.`redirect_asin`, _Full_Limit_Buster_Inventory_DS.`created_date`, _Full_Limit_Buster_Inventory_DS.`created_time`, _Full_Limit_Buster_Inventory_DS.`sku_map`, _Full_Limit_Buster_Inventory_DS.`sku_name`, _Full_Limit_Buster_Inventory_DS.`buy_box_count`, _Full_Limit_Buster_Inventory_DS.`Partner - Brand`, _Full_Limit_Buster_Inventory_DS.`cod_condition`, _Full_Limit_Buster_Inventory_DS.`unit_in_listing`, _Full_Limit_Buster_Inventory_DS.`bp_brand_id`, _Full_Limit_Buster_Inventory_DS.`asin_bp_enforceable`, _Full_Limit_Buster_Inventory_DS.`country`, _Full_Limit_Buster_Inventory_DS.`BBC_ORIGINAL_STATUS`, _Full_Limit_Buster_Inventory_DS.`BBC_2_8_22_STATUS`, _Group_By.`Storefront ID`, _Group_By.`Last Notice Type`, _Group_By.`Last Notice Sent`, _Group_By.`Last Note`, _Group_By.`Invoice ID`, _Group_By.`Job ID`, _Group_By.`USPS Tracking`, _Group_By.`Delivery Status`, _Group_By.`Delivery Date`, _Group_By.`Enforcement History`, _Group_By.`C2M ERROR_STATUS`, _Group_By.`Recipient Address`, _Group_By.`Platform Sent?`, _Group_By.`Notes`, _Group_By.`C&D Date` FROM _Full_Limit_Buster_Inventory_DS LEFT JOIN _Group_By ON _Full_Limit_Buster_Inventory_DS.`Brand` = _Group_By.`Brand` AND _Full_Limit_Buster_Inventory_DS.`sellerId` = _Group_By.`Storefront ID`
),

_Group_By_1 AS (
  SELECT `Brand`, `amazonID`, MIN(`scraped_date`) AS `First Seen Date`, MAX(`scraped_date`) AS `Last Seen Date` FROM _Join_Data GROUP BY `Brand`, `amazonID`
),

_Join_Data_1 AS (
  SELECT _Join_Data.`sales_country_id`, _Join_Data.`revenue`, _Join_Data.`asins units`, _Join_Data.`revenue brand`, _Join_Data.`asins units brand`, _Join_Data.`Percent Mix of Brand`, _Join_Data.`Revenue Rank R3MTH`, _Join_Data.`Revenue Distribution R3MTH`, _Join_Data.`scraped_date`, _Join_Data.`amazonID`, _Join_Data.`sellerId`, _Join_Data.`sellerName`, _Join_Data.`storefront_name`, _Join_Data.`asin`, _Join_Data.`isQuantityRestricted`, _Join_Data.`Brand`, _Join_Data.`isFBA`, _Join_Data.`upc`, _Join_Data.`upc_name`, _Join_Data.`msrp`, _Join_Data.`srp`, _Join_Data.`map`, _Join_Data.`parent_category`, _Join_Data.`child_category`, _Join_Data.`child_category_2`, _Join_Data.`child_category_3`, _Join_Data.`partner name`, _Join_Data.`country_id`, _Join_Data.`offer_price`, _Join_Data.`offer_date_max_price`, _Join_Data.`Units`, _Join_Data.`Limit Buster Units`, _Join_Data.`redirect_asin`, _Join_Data.`created_date`, _Join_Data.`created_time`, _Join_Data.`sku_map`, _Join_Data.`sku_name`, _Join_Data.`buy_box_count`, _Join_Data.`Partner - Brand`, _Join_Data.`cod_condition`, _Join_Data.`unit_in_listing`, _Join_Data.`bp_brand_id`, _Join_Data.`asin_bp_enforceable`, _Join_Data.`country`, _Join_Data.`BBC_ORIGINAL_STATUS`, _Join_Data.`BBC_2_8_22_STATUS`, _Join_Data.`Storefront ID`, _Join_Data.`Last Notice Type`, _Join_Data.`Last Notice Sent`, _Join_Data.`Last Note`, _Join_Data.`Invoice ID`, _Join_Data.`Job ID`, _Join_Data.`USPS Tracking`, _Join_Data.`Delivery Status`, _Join_Data.`Delivery Date`, _Join_Data.`Enforcement History`, _Join_Data.`C2M ERROR_STATUS`, _Join_Data.`Recipient Address`, _Join_Data.`Platform Sent?`, _Join_Data.`Notes`, _Join_Data.`C&D Date`, _Group_By_1.`First Seen Date`, _Group_By_1.`Last Seen Date` FROM _Join_Data LEFT JOIN _Group_By_1 ON _Join_Data.`amazonID` = _Group_By_1.`amazonID` AND _Join_Data.`Brand` = _Group_By_1.`Brand`
),

_Add_Formula AS (
  SELECT `Brand`, `amazonID`, `First Seen Date`, `Last Seen Date`, `sales_country_id`, `revenue`, `asins units`, `revenue brand`, `asins units brand`, `Percent Mix of Brand`, `Revenue Rank R3MTH`, `Revenue Distribution R3MTH`, `scraped_date`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `isFBA`, `upc`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `cod_condition`, `unit_in_listing`, `bp_brand_id`, `asin_bp_enforceable`, `country`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS`, `Storefront ID`, `Last Notice Type`, `Last Notice Sent`, `Last Note`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Enforcement History`, `C2M ERROR_STATUS`, `Recipient Address`, `Platform Sent?`, `Notes`, `C&D Date`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 7 DAY) then 1 else 0 END) AS `New Storefront within 7 days`, (DATEDIFF(`First Seen Date`,CURRENT_DATE())) AS `Days since first listing`, (DATEDIFF(`Last Seen Date`,CURRENT_DATE())) AS `Days since last listing`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 1 DAY) then 1 else 0 END) AS `New Storefront within 2 days`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 14 DAY) then 1 else 0 END) AS `New Storefront within 14 days`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 28 DAY) then 1 else 0 END) AS `New Storefront within 28 days` FROM _Join_Data_1
),

_Add_Vendor_Code AS (
  SELECT _Add_Formula.`Brand`, _Add_Formula.`amazonID`, _Add_Formula.`First Seen Date`, _Add_Formula.`Last Seen Date`, _Add_Formula.`sales_country_id`, _Add_Formula.`revenue`, _Add_Formula.`asins units`, _Add_Formula.`revenue brand`, _Add_Formula.`asins units brand`, _Add_Formula.`Percent Mix of Brand`, _Add_Formula.`Revenue Rank R3MTH`, _Add_Formula.`Revenue Distribution R3MTH`, _Add_Formula.`scraped_date`, _Add_Formula.`sellerId`, _Add_Formula.`sellerName`, _Add_Formula.`storefront_name`, _Add_Formula.`asin`, _Add_Formula.`isQuantityRestricted`, _Add_Formula.`isFBA`, _Add_Formula.`upc`, _Add_Formula.`upc_name`, _Add_Formula.`msrp`, _Add_Formula.`srp`, _Add_Formula.`map`, _Add_Formula.`parent_category`, _Add_Formula.`child_category`, _Add_Formula.`child_category_2`, _Add_Formula.`child_category_3`, _Add_Formula.`partner name`, _Add_Formula.`country_id`, _Add_Formula.`offer_price`, _Add_Formula.`offer_date_max_price`, _Add_Formula.`Units`, _Add_Formula.`Limit Buster Units`, _Add_Formula.`redirect_asin`, _Add_Formula.`created_date`, _Add_Formula.`created_time`, _Add_Formula.`sku_map`, _Add_Formula.`sku_name`, _Add_Formula.`buy_box_count`, _Add_Formula.`Partner - Brand`, _Add_Formula.`cod_condition`, _Add_Formula.`unit_in_listing`, _Add_Formula.`bp_brand_id`, _Add_Formula.`asin_bp_enforceable`, _Add_Formula.`country`, _Add_Formula.`BBC_ORIGINAL_STATUS`, _Add_Formula.`BBC_2_8_22_STATUS`, _Add_Formula.`Storefront ID`, _Add_Formula.`Last Notice Type`, _Add_Formula.`Last Notice Sent`, _Add_Formula.`Last Note`, _Add_Formula.`Invoice ID`, _Add_Formula.`Job ID`, _Add_Formula.`USPS Tracking`, _Add_Formula.`Delivery Status`, _Add_Formula.`Delivery Date`, _Add_Formula.`Enforcement History`, _Add_Formula.`C2M ERROR_STATUS`, _Add_Formula.`Recipient Address`, _Add_Formula.`Platform Sent?`, _Add_Formula.`Notes`, _Add_Formula.`C&D Date`, _Add_Formula.`New Storefront within 7 days`, _Add_Formula.`Days since first listing`, _Add_Formula.`Days since last listing`, _Add_Formula.`New Storefront within 2 days`, _Add_Formula.`New Storefront within 14 days`, _Add_Formula.`New Storefront within 28 days`, _Group_by_UPC.`vendor_code` AS `Vendor Code`, _Group_by_UPC.`catalog_map` FROM _Add_Formula LEFT JOIN _Group_by_UPC ON _Add_Formula.`upc` = _Group_by_UPC.`upc`
),

_Join_Data_8 AS (
  SELECT _ASIN_with_highest_inventory.`Max Units`, _ASIN_with_highest_inventory.`ASIN with highest inventory`, _Add_Vendor_Code.`upc`, _Add_Vendor_Code.`vendor_code`, _Add_Vendor_Code.`catalog_map`, _Add_Vendor_Code.`Brand`, _Add_Vendor_Code.`amazonID`, _Add_Vendor_Code.`First Seen Date`, _Add_Vendor_Code.`Last Seen Date`, _Add_Vendor_Code.`sales_country_id`, _Add_Vendor_Code.`revenue`, _Add_Vendor_Code.`asins units`, _Add_Vendor_Code.`revenue brand`, _Add_Vendor_Code.`asins units brand`, _Add_Vendor_Code.`Percent Mix of Brand`, _Add_Vendor_Code.`Revenue Rank R3MTH`, _Add_Vendor_Code.`Revenue Distribution R3MTH`, _Add_Vendor_Code.`scraped_date`, _Add_Vendor_Code.`sellerId`, _Add_Vendor_Code.`sellerName`, _Add_Vendor_Code.`storefront_name`, _Add_Vendor_Code.`asin`, _Add_Vendor_Code.`isQuantityRestricted`, _Add_Vendor_Code.`isFBA`, _Add_Vendor_Code.`upc_name`, _Add_Vendor_Code.`msrp`, _Add_Vendor_Code.`srp`, _Add_Vendor_Code.`map`, _Add_Vendor_Code.`parent_category`, _Add_Vendor_Code.`child_category`, _Add_Vendor_Code.`child_category_2`, _Add_Vendor_Code.`child_category_3`, _Add_Vendor_Code.`partner name`, _Add_Vendor_Code.`country_id`, _Add_Vendor_Code.`offer_price`, _Add_Vendor_Code.`offer_date_max_price`, _Add_Vendor_Code.`Units`, _Add_Vendor_Code.`Limit Buster Units`, _Add_Vendor_Code.`redirect_asin`, _Add_Vendor_Code.`created_date`, _Add_Vendor_Code.`created_time`, _Add_Vendor_Code.`sku_map`, _Add_Vendor_Code.`sku_name`, _Add_Vendor_Code.`buy_box_count`, _Add_Vendor_Code.`Partner - Brand`, _Add_Vendor_Code.`cod_condition`, _Add_Vendor_Code.`unit_in_listing`, _Add_Vendor_Code.`bp_brand_id`, _Add_Vendor_Code.`asin_bp_enforceable`, _Add_Vendor_Code.`country`, _Add_Vendor_Code.`BBC_ORIGINAL_STATUS`, _Add_Vendor_Code.`BBC_2_8_22_STATUS`, _Add_Vendor_Code.`Storefront ID`, _Add_Vendor_Code.`Last Notice Type`, _Add_Vendor_Code.`Last Notice Sent`, _Add_Vendor_Code.`Last Note`, _Add_Vendor_Code.`Invoice ID`, _Add_Vendor_Code.`Job ID`, _Add_Vendor_Code.`USPS Tracking`, _Add_Vendor_Code.`Delivery Status`, _Add_Vendor_Code.`Delivery Date`, _Add_Vendor_Code.`Enforcement History`, _Add_Vendor_Code.`C2M ERROR_STATUS`, _Add_Vendor_Code.`Recipient Address`, _Add_Vendor_Code.`Platform Sent?`, _Add_Vendor_Code.`Notes`, _Add_Vendor_Code.`C&D Date`, _Add_Vendor_Code.`New Storefront within 7 days`, _Add_Vendor_Code.`Days since first listing`, _Add_Vendor_Code.`Days since last listing`, _Add_Vendor_Code.`New Storefront within 2 days`, _Add_Vendor_Code.`New Storefront within 14 days`, _Add_Vendor_Code.`New Storefront within 28 days` FROM _ASIN_with_highest_inventory RIGHT JOIN _Add_Vendor_Code ON _ASIN_with_highest_inventory.`sellerId` = _Add_Vendor_Code.`sellerId` AND _ASIN_with_highest_inventory.`Brand` = _Add_Vendor_Code.`Brand` AND _ASIN_with_highest_inventory.`sales_country_id` = _Add_Vendor_Code.`sales_country_id`
),

_Add_Formula_4 AS (
  SELECT `Max Units`, `ASIN with highest inventory`, `upc`, `vendor_code`, `catalog_map`, `Brand`, `amazonID`, `First Seen Date`, `Last Seen Date`, `sales_country_id`, `revenue`, `asins units`, `revenue brand`, `asins units brand`, `Percent Mix of Brand`, `Revenue Rank R3MTH`, `Revenue Distribution R3MTH`, `scraped_date`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `isFBA`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `cod_condition`, `unit_in_listing`, `bp_brand_id`, `asin_bp_enforceable`, `country`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS`, `Storefront ID`, `Last Notice Type`, `Last Notice Sent`, `Last Note`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Enforcement History`, `C2M ERROR_STATUS`, `Recipient Address`, `Platform Sent?`, `Notes`, `C&D Date`, `New Storefront within 7 days`, `Days since first listing`, `Days since last listing`, `New Storefront within 2 days`, `New Storefront within 14 days`, `New Storefront within 28 days`, (Case when `sellerName`='XXXXXXXXX' then CURRENT_DATE() else '' end) AS `Enter Date NEW`, (Case when `sellerName`='XXXXXXXXX' then CURRENT_DATE() else '' end) AS `New Notes NEW`, (Case when `sellerName`='XXXXXXXXX' then CURRENT_DATE() else '' end) AS `New Invoice ID NEW` FROM _Join_Data_8
),

_Join_Data_2 AS (
  SELECT _Add_Formula_4.`Max Units`, _Add_Formula_4.`ASIN with highest inventory`, _Add_Formula_4.`upc`, _Add_Formula_4.`vendor_code`, _Add_Formula_4.`catalog_map`, _Add_Formula_4.`Brand`, _Add_Formula_4.`amazonID`, _Add_Formula_4.`First Seen Date`, _Add_Formula_4.`Last Seen Date`, _Add_Formula_4.`sales_country_id`, _Add_Formula_4.`revenue`, _Add_Formula_4.`asins units`, _Add_Formula_4.`revenue brand`, _Add_Formula_4.`asins units brand`, _Add_Formula_4.`Percent Mix of Brand`, _Add_Formula_4.`Revenue Rank R3MTH`, _Add_Formula_4.`Revenue Distribution R3MTH`, _Add_Formula_4.`scraped_date`, _Add_Formula_4.`sellerId`, _Add_Formula_4.`sellerName`, _Add_Formula_4.`storefront_name`, _Add_Formula_4.`asin`, _Add_Formula_4.`isQuantityRestricted`, _Add_Formula_4.`isFBA`, _Add_Formula_4.`upc_name`, _Add_Formula_4.`msrp`, _Add_Formula_4.`srp`, _Add_Formula_4.`map`, _Add_Formula_4.`parent_category`, _Add_Formula_4.`child_category`, _Add_Formula_4.`child_category_2`, _Add_Formula_4.`child_category_3`, _Add_Formula_4.`partner name`, _Add_Formula_4.`country_id`, _Add_Formula_4.`offer_price`, _Add_Formula_4.`offer_date_max_price`, _Add_Formula_4.`Units`, _Add_Formula_4.`Limit Buster Units`, _Add_Formula_4.`redirect_asin`, _Add_Formula_4.`created_date`, _Add_Formula_4.`created_time`, _Add_Formula_4.`sku_map`, _Add_Formula_4.`sku_name`, _Add_Formula_4.`buy_box_count`, _Add_Formula_4.`Partner - Brand`, _Add_Formula_4.`cod_condition`, _Add_Formula_4.`unit_in_listing`, _Add_Formula_4.`bp_brand_id`, _Add_Formula_4.`asin_bp_enforceable`, _Add_Formula_4.`country`, _Add_Formula_4.`BBC_ORIGINAL_STATUS`, _Add_Formula_4.`BBC_2_8_22_STATUS`, _Add_Formula_4.`Storefront ID`, _Add_Formula_4.`Last Notice Type`, _Add_Formula_4.`Last Notice Sent`, _Add_Formula_4.`Last Note`, _Add_Formula_4.`Invoice ID`, _Add_Formula_4.`Job ID`, _Add_Formula_4.`USPS Tracking`, _Add_Formula_4.`Delivery Status`, _Add_Formula_4.`Delivery Date`, _Add_Formula_4.`Enforcement History`, _Add_Formula_4.`C2M ERROR_STATUS`, _Add_Formula_4.`Recipient Address`, _Add_Formula_4.`Platform Sent?`, _Add_Formula_4.`Notes`, _Add_Formula_4.`C&D Date`, _Add_Formula_4.`New Storefront within 7 days`, _Add_Formula_4.`Days since first listing`, _Add_Formula_4.`Days since last listing`, _Add_Formula_4.`New Storefront within 2 days`, _Add_Formula_4.`New Storefront within 14 days`, _Add_Formula_4.`New Storefront within 28 days`, _Add_Formula_4.`Enter Date NEW`, _Add_Formula_4.`New Notes NEW`, _Add_Formula_4.`New Invoice ID NEW`, _Alter_Columns.`Country ID` FROM _Add_Formula_4 LEFT JOIN _Alter_Columns ON _Add_Formula_4.`asin` = _Alter_Columns.`ASIN` AND _Add_Formula_4.`sales_country_id` = _Alter_Columns.`Country ID`
),

_Full_Enforcement_DS AS (
  SELECT * FROM _Join_Data_2
)

SELECT * FROM _Full_Enforcement_DS