/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 526
Dataflow Name: CA Enforcement DS
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 28
  Successful: 28
  Failed: 0
  Unique Action Types: 5
  Action Types: ExpressionEvaluator, GroupBy, LoadFromVault, MergeJoin, PublishToVault
  Pipelines: 8

Generated: 2025-07-02 10:25:24
================================================================================
*/
WITH _CA_Limit_Buster_Inventory_DS AS (
  SELECT
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    asin_link,
    inventory_value,
    offer_type,
    price_δ_%_-_map,
    price_δ_$_-_map,
    authorized_sellers,
    map_exceptions,
    map_violations_sku_map,
    storefront_db_url
  FROM CA_Limit_Buster_Inventory_DS
), _BP_PlatformNotices_Sent AS (
  SELECT
    staff,
    brand,
    storefront_id,
    storefront_name,
    asin,
    date_of_first_message,
    complaint_date,
    complaint_id,
    message,
    column_10
  FROM BP_PlatformNotices_Sent
), _bp_enforcements AS (
  SELECT
    staff,
    partner,
    brand,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    storefront_id,
    storefront_name,
    date,
    type,
    notes_comments,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    response_received,
    order_cost,
    usps_tracking_type,
    recipient_address,
    delivered_city,
    error_status,
    rundatetime,
    return_receipt_downloaded,
    enforce_by_brand,
    enforce_by,
    batch_id,
    batch_last_run
  FROM bp_enforcements
), _Amazon_Sellers AS (
  SELECT
    internal_id,
    seller_id,
    name,
    storefront_name,
    amazon_businessname,
    amazon_businessaddress,
    last_scraped_at,
    zip_code,
    country,
    state,
    city,
    address_line1,
    address_line2,
    review_count,
    review_count_last_30,
    batch_id,
    batch_last_run
  FROM Amazon_Sellers
), _Amazon_Sellers_Addresses AS (
  SELECT
    internal_id,
    seller_id,
    marketplace,
    storefront_name,
    address,
    city,
    state,
    country,
    zip,
    created_at,
    updated_at,
    batch_id,
    batch_last_run
  FROM Amazon_Sellers_Addresses
), _Amazon_Sellers_Details_Contacts AS (
  SELECT
    internal_id,
    seller_id,
    marketplace,
    storefront_name,
    email,
    extension,
    phone,
    first_name,
    last_name,
    created_at,
    updated_at,
    batch_id,
    batch_last_run
  FROM Amazon_Sellers_Details_Contacts
), _ASIN_Buy_Box_Status AS (
  SELECT
    asin,
    scraped_date,
    brand,
    partner_name,
    upc,
    upc_name,
    country_id,
    brand_assigned_user_initials,
    brand_assigned_user,
    is_buy_box_number_sum,
    map,
    msrp,
    offer_price,
    buy_box_status,
    country_paneu,
    %_active_by_day,
    %_suppressed_by_day
  FROM ASIN_Buy_Box_Status
), _UPCs AS (
  SELECT
    brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    client_id,
    cost,
    created_at,
    created_by,
    default_cost,
    default_discount,
    deleted_at,
    deleted_by,
    id,
    hero,
    map,
    min_order_qty,
    name,
    old_upc,
    parent_upc,
    reorder_comments,
    reorder_status,
    srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upc,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    is_discontinued_status,
    amazon_seller_id,
    unit_count_type_id,
    unit_count,
    batch_id,
    batch_last_run
  FROM UPCs
), _Join_Data_6 AS (
  SELECT
    _bp_enforcements.staff,
    _bp_enforcements.partner,
    _bp_enforcements.brand,
    _bp_enforcements.marketplace_channel_id,
    _bp_enforcements.marketplace_channel,
    _bp_enforcements.country_id,
    _bp_enforcements.country,
    _bp_enforcements.storefront_id,
    _bp_enforcements.storefront_name,
    _bp_enforcements.date,
    _bp_enforcements.type,
    _bp_enforcements.notes_comments,
    _bp_enforcements.invoice_id,
    _bp_enforcements.job_id,
    _bp_enforcements.usps_tracking,
    _bp_enforcements.delivery_status,
    _bp_enforcements.delivery_date,
    _bp_enforcements.response_received,
    _bp_enforcements.order_cost,
    _bp_enforcements.usps_tracking_type,
    _bp_enforcements.recipient_address,
    _bp_enforcements.delivered_city,
    _bp_enforcements.error_status,
    _bp_enforcements.rundatetime,
    _bp_enforcements.return_receipt_downloaded,
    _bp_enforcements.enforce_by_brand,
    _bp_enforcements.enforce_by,
    _bp_enforcements.batch_id,
    _bp_enforcements.batch_last_run,
    _BP_PlatformNotices_Sent.asin,
    _BP_PlatformNotices_Sent.date_of_first_message,
    _BP_PlatformNotices_Sent.complaint_date,
    _BP_PlatformNotices_Sent.complaint_id,
    _BP_PlatformNotices_Sent.message,
    _BP_PlatformNotices_Sent.column_10
  FROM _bp_enforcements
  LEFT JOIN _BP_PlatformNotices_Sent
    ON _bp_enforcements.brand = _BP_PlatformNotices_Sent.brand
    AND _bp_enforcements.storefront_id = _BP_PlatformNotices_Sent.storefront_id
), _Group_By_2 AS (
  SELECT
    internal_id,
    MAX(address) AS address,
    MAX(city) AS city,
    MAX(state) AS state,
    MAX(zip) AS zip,
    MAX(country) AS country
  FROM _Amazon_Sellers_Addresses
  GROUP BY
    internal_id
), _Add_Formula_3 AS (
  SELECT
    internal_id,
    seller_id,
    marketplace,
    storefront_name,
    email,
    extension,
    phone,
    first_name,
    last_name,
    created_at,
    updated_at,
    batch_id,
    batch_last_run,
    (
      CONCAT(first_name, ' ', last_name)
    ) AS seller_contact
  FROM _Amazon_Sellers_Details_Contacts
), _Group_By_6 AS (
  SELECT
    asin,
    MAX(buy_box_status) AS buy_box_status,
    MAX(scraped_date) AS buybox_status_date
  FROM _ASIN_Buy_Box_Status
  GROUP BY
    asin
), _Add_Formula_2 AS (
  SELECT
    brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    client_id,
    cost,
    created_at,
    created_by,
    default_cost,
    default_discount,
    deleted_at,
    deleted_by,
    id,
    hero,
    map,
    min_order_qty,
    name,
    old_upc,
    parent_upc,
    reorder_comments,
    reorder_status,
    srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upc,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    is_discontinued_status,
    amazon_seller_id,
    unit_count_type_id,
    unit_count,
    batch_id,
    batch_last_run,
    (
      CASE
        WHEN brand_id IN (75, 601, 602, 1270, 1936) AND LENGTH(vendor_sku) >= 5
        THEN NULL
        ELSE vendor_sku
      END
    ) AS vendor_sku_corrected
  FROM _UPCs
), _Group_By AS (
  SELECT
    brand,
    storefront_id,
    MAX(type) AS last_notice_type,
    MAX(date) AS last_notice_sent,
    LISTAGG(notes_comments, '') AS notes,
    MAX(invoice_id) AS invoice_id,
    MAX(job_id) AS job_id,
    MAX(usps_tracking) AS usps_tracking,
    MAX(delivery_status) AS delivery_status,
    MAX(delivery_date) AS delivery_date,
    LISTAGG(type, '') AS enforcement_history,
    MAX(error_status) AS c2m_error_status,
    MAX(recipient_address) AS recipient_address,
    MAX(date_of_first_message) AS platform_sent
  FROM _Join_Data_6
  GROUP BY
    brand,
    storefront_id
), _Join_Data_2 AS (
  SELECT
    _Amazon_Sellers.internal_id,
    _Amazon_Sellers.seller_id,
    _Amazon_Sellers.name,
    _Amazon_Sellers.storefront_name,
    _Amazon_Sellers.amazon_businessname,
    _Amazon_Sellers.amazon_businessaddress,
    _Amazon_Sellers.last_scraped_at,
    _Amazon_Sellers.zip_code,
    _Amazon_Sellers.country,
    _Amazon_Sellers.state,
    _Amazon_Sellers.city,
    _Amazon_Sellers.address_line1,
    _Amazon_Sellers.address_line2,
    _Amazon_Sellers.review_count,
    _Amazon_Sellers.review_count_last_30,
    _Amazon_Sellers.batch_id,
    _Amazon_Sellers.batch_last_run,
    _Group_By_2.address,
    _Group_By_2.city AS violator_city,
    _Group_By_2.state AS violator_state,
    _Group_By_2.zip,
    _Group_By_2.country AS violator_country
  FROM _Amazon_Sellers
  LEFT JOIN _Group_By_2
    ON _Amazon_Sellers.internal_id = _Group_By_2.internal_id
), _Group_By_3 AS (
  SELECT
    internal_id,
    MAX(email) AS email,
    MAX(seller_contact) AS seller_contact,
    MAX(phone) AS phone
  FROM _Add_Formula_3
  GROUP BY
    internal_id
), _Group_By_4 AS (
  SELECT
    upc,
    MAX(vendor_sku_corrected) AS vendor_code
  FROM _Add_Formula_2
  GROUP BY
    upc
), _Join_Data AS (
  SELECT
    _CA_Limit_Buster_Inventory_DS.scraped_date,
    _CA_Limit_Buster_Inventory_DS.amazonid,
    _CA_Limit_Buster_Inventory_DS.sellerid,
    _CA_Limit_Buster_Inventory_DS.sellername,
    _CA_Limit_Buster_Inventory_DS.storefront_name,
    _CA_Limit_Buster_Inventory_DS.asin,
    _CA_Limit_Buster_Inventory_DS.isquantityrestricted,
    _CA_Limit_Buster_Inventory_DS.brand,
    _CA_Limit_Buster_Inventory_DS.isfba,
    _CA_Limit_Buster_Inventory_DS.upc,
    _CA_Limit_Buster_Inventory_DS.upc_name,
    _CA_Limit_Buster_Inventory_DS.msrp,
    _CA_Limit_Buster_Inventory_DS.srp,
    _CA_Limit_Buster_Inventory_DS.map,
    _CA_Limit_Buster_Inventory_DS.parent_category,
    _CA_Limit_Buster_Inventory_DS.child_category,
    _CA_Limit_Buster_Inventory_DS.child_category_2,
    _CA_Limit_Buster_Inventory_DS.child_category_3,
    _CA_Limit_Buster_Inventory_DS.partner_name,
    _CA_Limit_Buster_Inventory_DS.country_id,
    _CA_Limit_Buster_Inventory_DS.offer_price,
    _CA_Limit_Buster_Inventory_DS.offer_date_max_price,
    _CA_Limit_Buster_Inventory_DS.units,
    _CA_Limit_Buster_Inventory_DS.limit_buster_units,
    _CA_Limit_Buster_Inventory_DS.redirect_asin,
    _CA_Limit_Buster_Inventory_DS.created_date,
    _CA_Limit_Buster_Inventory_DS.created_time,
    _CA_Limit_Buster_Inventory_DS.sku_map,
    _CA_Limit_Buster_Inventory_DS.sku_name,
    _CA_Limit_Buster_Inventory_DS.buy_box_count,
    _CA_Limit_Buster_Inventory_DS.partner_-_brand,
    _CA_Limit_Buster_Inventory_DS.date,
    _CA_Limit_Buster_Inventory_DS.day_of_week,
    _CA_Limit_Buster_Inventory_DS.month,
    _CA_Limit_Buster_Inventory_DS.445_week,
    _CA_Limit_Buster_Inventory_DS.445_week_number,
    _CA_Limit_Buster_Inventory_DS.445_month,
    _CA_Limit_Buster_Inventory_DS.445_month_number,
    _CA_Limit_Buster_Inventory_DS.445_calendar,
    _CA_Limit_Buster_Inventory_DS.445_year,
    _CA_Limit_Buster_Inventory_DS.bbc_original_status,
    _CA_Limit_Buster_Inventory_DS.bbc_2_8_22_status,
    _CA_Limit_Buster_Inventory_DS.asin_link,
    _CA_Limit_Buster_Inventory_DS.inventory_value,
    _CA_Limit_Buster_Inventory_DS.offer_type,
    _CA_Limit_Buster_Inventory_DS.price_δ_%_-_map,
    _CA_Limit_Buster_Inventory_DS.price_δ_$_-_map,
    _CA_Limit_Buster_Inventory_DS.authorized_sellers,
    _CA_Limit_Buster_Inventory_DS.map_exceptions,
    _CA_Limit_Buster_Inventory_DS.map_violations_sku_map,
    _CA_Limit_Buster_Inventory_DS.storefront_db_url,
    _Group_By.storefront_id,
    _Group_By.last_notice_type,
    _Group_By.last_notice_sent,
    _Group_By.notes,
    _Group_By.invoice_id,
    _Group_By.job_id,
    _Group_By.usps_tracking,
    _Group_By.delivery_status,
    _Group_By.delivery_date,
    _Group_By.enforcement_history,
    _Group_By.c2m_error_status,
    _Group_By.recipient_address,
    _Group_By.platform_sent
  FROM _CA_Limit_Buster_Inventory_DS
  LEFT JOIN _Group_By
    ON _CA_Limit_Buster_Inventory_DS.brand = _Group_By.brand
    AND _CA_Limit_Buster_Inventory_DS.sellerid = _Group_By.storefront_id
), _Join_Data_3 AS (
  SELECT
    _Join_Data_2.internal_id,
    _Join_Data_2.seller_id,
    _Join_Data_2.name,
    _Join_Data_2.storefront_name,
    _Join_Data_2.amazon_businessname,
    _Join_Data_2.amazon_businessaddress,
    _Join_Data_2.last_scraped_at,
    _Join_Data_2.zip_code,
    _Join_Data_2.country,
    _Join_Data_2.state,
    _Join_Data_2.city,
    _Join_Data_2.address_line1,
    _Join_Data_2.address_line2,
    _Join_Data_2.review_count,
    _Join_Data_2.review_count_last_30,
    _Join_Data_2.batch_id,
    _Join_Data_2.batch_last_run,
    _Join_Data_2.address,
    _Join_Data_2.violator_city,
    _Join_Data_2.violator_state,
    _Join_Data_2.zip,
    _Join_Data_2.violator_country,
    _Group_By_3.email,
    _Group_By_3.seller_contact,
    _Group_By_3.phone
  FROM _Join_Data_2
  LEFT JOIN _Group_By_3
    ON _Join_Data_2.internal_id = _Group_By_3.internal_id
), _Group_By_1 AS (
  SELECT
    brand,
    amazonid,
    MIN(scraped_date) AS first_seen_date,
    MAX(scraped_date) AS last_seen_date
  FROM _Join_Data
  GROUP BY
    brand,
    amazonid
), _Add_Formula_1 AS (
  SELECT
    internal_id,
    seller_id,
    name,
    storefront_name,
    amazon_businessname,
    amazon_businessaddress,
    last_scraped_at,
    zip_code,
    country,
    state,
    city,
    address_line1,
    address_line2,
    review_count,
    review_count_last_30,
    batch_id,
    batch_last_run,
    address,
    violator_city,
    violator_state,
    zip,
    violator_country,
    email,
    seller_contact,
    phone,
    (
      CASE WHEN email IS NULL THEN 'No' ELSE 'Yes' END
    ) AS email_available,
    (
      CASE WHEN address IS NULL THEN 'No' ELSE 'Yes' END
    ) AS address_available
  FROM _Join_Data_3
), _Join_Data_1 AS (
  SELECT
    _Join_Data.scraped_date,
    _Join_Data.amazonid,
    _Join_Data.sellerid,
    _Join_Data.sellername,
    _Join_Data.storefront_name,
    _Join_Data.asin,
    _Join_Data.isquantityrestricted,
    _Join_Data.brand,
    _Join_Data.isfba,
    _Join_Data.upc,
    _Join_Data.upc_name,
    _Join_Data.msrp,
    _Join_Data.srp,
    _Join_Data.map,
    _Join_Data.parent_category,
    _Join_Data.child_category,
    _Join_Data.child_category_2,
    _Join_Data.child_category_3,
    _Join_Data.partner_name,
    _Join_Data.country_id,
    _Join_Data.offer_price,
    _Join_Data.offer_date_max_price,
    _Join_Data.units,
    _Join_Data.limit_buster_units,
    _Join_Data.redirect_asin,
    _Join_Data.created_date,
    _Join_Data.created_time,
    _Join_Data.sku_map,
    _Join_Data.sku_name,
    _Join_Data.buy_box_count,
    _Join_Data.partner_-_brand,
    _Join_Data.date,
    _Join_Data.day_of_week,
    _Join_Data.month,
    _Join_Data.445_week,
    _Join_Data.445_week_number,
    _Join_Data.445_month,
    _Join_Data.445_month_number,
    _Join_Data.445_calendar,
    _Join_Data.445_year,
    _Join_Data.bbc_original_status,
    _Join_Data.bbc_2_8_22_status,
    _Join_Data.asin_link,
    _Join_Data.inventory_value,
    _Join_Data.offer_type,
    _Join_Data.price_δ_%_-_map,
    _Join_Data.price_δ_$_-_map,
    _Join_Data.authorized_sellers,
    _Join_Data.map_exceptions,
    _Join_Data.map_violations_sku_map,
    _Join_Data.storefront_db_url,
    _Join_Data.storefront_id,
    _Join_Data.last_notice_type,
    _Join_Data.last_notice_sent,
    _Join_Data.notes,
    _Join_Data.invoice_id,
    _Join_Data.job_id,
    _Join_Data.usps_tracking,
    _Join_Data.delivery_status,
    _Join_Data.delivery_date,
    _Join_Data.enforcement_history,
    _Join_Data.c2m_error_status,
    _Join_Data.recipient_address,
    _Join_Data.platform_sent,
    _Group_By_1.first_seen_date,
    _Group_By_1.last_seen_date
  FROM _Join_Data
  LEFT JOIN _Group_By_1
    ON _Join_Data.amazonid = _Group_By_1.amazonid
    AND _Join_Data.brand = _Group_By_1.brand
), _Add_Formula AS (
  SELECT
    brand,
    amazonid,
    first_seen_date,
    last_seen_date,
    scraped_date,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    asin_link,
    inventory_value,
    offer_type,
    price_δ_%_-_map,
    price_δ_$_-_map,
    authorized_sellers,
    map_exceptions,
    map_violations_sku_map,
    storefront_db_url,
    storefront_id,
    last_notice_type,
    last_notice_sent,
    notes,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    enforcement_history,
    c2m_error_status,
    recipient_address,
    platform_sent,
    (
      CASE
        WHEN first_seen_date >= DATEADD(DAY, '7' * -1, CURRENT_DATE)
        THEN 1
        ELSE 0
      END
    ) AS new_storefront_within_7_days,
    (
      DATEDIFF(DAY, CURRENT_DATE, first_seen_date)
    ) AS days_since_first_listing,
    (
      DATEDIFF(DAY, CURRENT_DATE, last_seen_date)
    ) AS days_since_last_listing,
    (
      CASE
        WHEN first_seen_date >= DATEADD(DAY, '1' * -1, CURRENT_DATE)
        THEN 1
        ELSE 0
      END
    ) AS new_storefront_within_2_days,
    (
      CASE
        WHEN first_seen_date >= DATEADD(DAY, '14' * -1, CURRENT_DATE)
        THEN 1
        ELSE 0
      END
    ) AS new_storefront_within_14_days,
    (
      CASE
        WHEN first_seen_date >= DATEADD(DAY, '28' * -1, CURRENT_DATE)
        THEN 1
        ELSE 0
      END
    ) AS new_storefront_within_28_days
  FROM _Join_Data_1
), _Join_Data_4 AS (
  SELECT
    _Add_Formula.brand,
    _Add_Formula.amazonid,
    _Add_Formula.first_seen_date,
    _Add_Formula.last_seen_date,
    _Add_Formula.scraped_date,
    _Add_Formula.sellerid,
    _Add_Formula.sellername,
    _Add_Formula.storefront_name,
    _Add_Formula.asin,
    _Add_Formula.isquantityrestricted,
    _Add_Formula.isfba,
    _Add_Formula.upc,
    _Add_Formula.upc_name,
    _Add_Formula.msrp,
    _Add_Formula.srp,
    _Add_Formula.map,
    _Add_Formula.parent_category,
    _Add_Formula.child_category,
    _Add_Formula.child_category_2,
    _Add_Formula.child_category_3,
    _Add_Formula.partner_name,
    _Add_Formula.country_id,
    _Add_Formula.offer_price,
    _Add_Formula.offer_date_max_price,
    _Add_Formula.units,
    _Add_Formula.limit_buster_units,
    _Add_Formula.redirect_asin,
    _Add_Formula.created_date,
    _Add_Formula.created_time,
    _Add_Formula.sku_map,
    _Add_Formula.sku_name,
    _Add_Formula.buy_box_count,
    _Add_Formula.partner_-_brand,
    _Add_Formula.date,
    _Add_Formula.day_of_week,
    _Add_Formula.month,
    _Add_Formula.445_week,
    _Add_Formula.445_week_number,
    _Add_Formula.445_month,
    _Add_Formula.445_month_number,
    _Add_Formula.445_calendar,
    _Add_Formula.445_year,
    _Add_Formula.bbc_original_status,
    _Add_Formula.bbc_2_8_22_status,
    _Add_Formula.asin_link,
    _Add_Formula.inventory_value,
    _Add_Formula.offer_type,
    _Add_Formula.price_δ_%_-_map,
    _Add_Formula.price_δ_$_-_map,
    _Add_Formula.authorized_sellers,
    _Add_Formula.map_exceptions,
    _Add_Formula.map_violations_sku_map,
    _Add_Formula.storefront_db_url,
    _Add_Formula.storefront_id,
    _Add_Formula.last_notice_type,
    _Add_Formula.last_notice_sent,
    _Add_Formula.notes,
    _Add_Formula.invoice_id,
    _Add_Formula.job_id,
    _Add_Formula.usps_tracking,
    _Add_Formula.delivery_status,
    _Add_Formula.delivery_date,
    _Add_Formula.enforcement_history,
    _Add_Formula.c2m_error_status,
    _Add_Formula.recipient_address,
    _Add_Formula.platform_sent,
    _Add_Formula.new_storefront_within_7_days,
    _Add_Formula.days_since_first_listing,
    _Add_Formula.days_since_last_listing,
    _Add_Formula.new_storefront_within_2_days,
    _Add_Formula.new_storefront_within_14_days,
    _Add_Formula.new_storefront_within_28_days,
    _Add_Formula_1.internal_id,
    _Add_Formula_1.seller_id,
    _Add_Formula_1.name,
    _Add_Formula_1.last_scraped_at,
    _Add_Formula_1.address_line1,
    _Add_Formula_1.address_line2,
    _Add_Formula_1.review_count,
    _Add_Formula_1.review_count_last_30,
    _Add_Formula_1.batch_id,
    _Add_Formula_1.batch_last_run,
    _Add_Formula_1.address,
    _Add_Formula_1.violator_city,
    _Add_Formula_1.violator_state,
    _Add_Formula_1.zip,
    _Add_Formula_1.violator_country,
    _Add_Formula_1.email,
    _Add_Formula_1.seller_contact,
    _Add_Formula_1.phone,
    _Add_Formula_1.email_available,
    _Add_Formula_1.address_available
  FROM _Add_Formula
  LEFT JOIN _Add_Formula_1
    ON _Add_Formula.amazonid = _Add_Formula_1.seller_id
), _Join_Data_5 AS (
  SELECT
    _Join_Data_4.brand,
    _Join_Data_4.amazonid,
    _Join_Data_4.first_seen_date,
    _Join_Data_4.last_seen_date,
    _Join_Data_4.scraped_date,
    _Join_Data_4.sellerid,
    _Join_Data_4.sellername,
    _Join_Data_4.storefront_name,
    _Join_Data_4.asin,
    _Join_Data_4.isquantityrestricted,
    _Join_Data_4.isfba,
    _Join_Data_4.upc,
    _Join_Data_4.upc_name,
    _Join_Data_4.msrp,
    _Join_Data_4.srp,
    _Join_Data_4.map,
    _Join_Data_4.parent_category,
    _Join_Data_4.child_category,
    _Join_Data_4.child_category_2,
    _Join_Data_4.child_category_3,
    _Join_Data_4.partner_name,
    _Join_Data_4.country_id,
    _Join_Data_4.offer_price,
    _Join_Data_4.offer_date_max_price,
    _Join_Data_4.units,
    _Join_Data_4.limit_buster_units,
    _Join_Data_4.redirect_asin,
    _Join_Data_4.created_date,
    _Join_Data_4.created_time,
    _Join_Data_4.sku_map,
    _Join_Data_4.sku_name,
    _Join_Data_4.buy_box_count,
    _Join_Data_4.partner_-_brand,
    _Join_Data_4.date,
    _Join_Data_4.day_of_week,
    _Join_Data_4.month,
    _Join_Data_4.445_week,
    _Join_Data_4.445_week_number,
    _Join_Data_4.445_month,
    _Join_Data_4.445_month_number,
    _Join_Data_4.445_calendar,
    _Join_Data_4.445_year,
    _Join_Data_4.bbc_original_status,
    _Join_Data_4.bbc_2_8_22_status,
    _Join_Data_4.asin_link,
    _Join_Data_4.inventory_value,
    _Join_Data_4.offer_type,
    _Join_Data_4.price_δ_%_-_map,
    _Join_Data_4.price_δ_$_-_map,
    _Join_Data_4.authorized_sellers,
    _Join_Data_4.map_exceptions,
    _Join_Data_4.map_violations_sku_map,
    _Join_Data_4.storefront_db_url,
    _Join_Data_4.storefront_id,
    _Join_Data_4.last_notice_type,
    _Join_Data_4.last_notice_sent,
    _Join_Data_4.notes,
    _Join_Data_4.invoice_id,
    _Join_Data_4.job_id,
    _Join_Data_4.usps_tracking,
    _Join_Data_4.delivery_status,
    _Join_Data_4.delivery_date,
    _Join_Data_4.enforcement_history,
    _Join_Data_4.c2m_error_status,
    _Join_Data_4.recipient_address,
    _Join_Data_4.platform_sent,
    _Join_Data_4.new_storefront_within_7_days,
    _Join_Data_4.days_since_first_listing,
    _Join_Data_4.days_since_last_listing,
    _Join_Data_4.new_storefront_within_2_days,
    _Join_Data_4.new_storefront_within_14_days,
    _Join_Data_4.new_storefront_within_28_days,
    _Join_Data_4.internal_id,
    _Join_Data_4.seller_id,
    _Join_Data_4.name,
    _Join_Data_4.last_scraped_at,
    _Join_Data_4.address_line1,
    _Join_Data_4.address_line2,
    _Join_Data_4.review_count,
    _Join_Data_4.review_count_last_30,
    _Join_Data_4.batch_id,
    _Join_Data_4.batch_last_run,
    _Join_Data_4.address,
    _Join_Data_4.violator_city,
    _Join_Data_4.violator_state,
    _Join_Data_4.zip,
    _Join_Data_4.violator_country,
    _Join_Data_4.email,
    _Join_Data_4.seller_contact,
    _Join_Data_4.phone,
    _Join_Data_4.email_available,
    _Join_Data_4.address_available,
    _Group_By_6.buy_box_status,
    _Group_By_6.buybox_status_date
  FROM _Join_Data_4
  LEFT JOIN _Group_By_6
    ON _Join_Data_4.asin = _Group_By_6.asin
), _Add_Vendor_Code AS (
  SELECT
    _Join_Data_5.brand,
    _Join_Data_5.amazonid,
    _Join_Data_5.first_seen_date,
    _Join_Data_5.last_seen_date,
    _Join_Data_5.scraped_date,
    _Join_Data_5.sellerid,
    _Join_Data_5.sellername,
    _Join_Data_5.storefront_name,
    _Join_Data_5.asin,
    _Join_Data_5.isquantityrestricted,
    _Join_Data_5.isfba,
    _Join_Data_5.upc,
    _Join_Data_5.upc_name,
    _Join_Data_5.msrp,
    _Join_Data_5.srp,
    _Join_Data_5.map,
    _Join_Data_5.parent_category,
    _Join_Data_5.child_category,
    _Join_Data_5.child_category_2,
    _Join_Data_5.child_category_3,
    _Join_Data_5.partner_name,
    _Join_Data_5.country_id,
    _Join_Data_5.offer_price,
    _Join_Data_5.offer_date_max_price,
    _Join_Data_5.units,
    _Join_Data_5.limit_buster_units,
    _Join_Data_5.redirect_asin,
    _Join_Data_5.created_date,
    _Join_Data_5.created_time,
    _Join_Data_5.sku_map,
    _Join_Data_5.sku_name,
    _Join_Data_5.buy_box_count,
    _Join_Data_5.partner_-_brand,
    _Join_Data_5.date,
    _Join_Data_5.day_of_week,
    _Join_Data_5.month,
    _Join_Data_5.445_week,
    _Join_Data_5.445_week_number,
    _Join_Data_5.445_month,
    _Join_Data_5.445_month_number,
    _Join_Data_5.445_calendar,
    _Join_Data_5.445_year,
    _Join_Data_5.bbc_original_status,
    _Join_Data_5.bbc_2_8_22_status,
    _Join_Data_5.asin_link,
    _Join_Data_5.inventory_value,
    _Join_Data_5.offer_type,
    _Join_Data_5.price_δ_%_-_map,
    _Join_Data_5.price_δ_$_-_map,
    _Join_Data_5.authorized_sellers,
    _Join_Data_5.map_exceptions,
    _Join_Data_5.map_violations_sku_map,
    _Join_Data_5.storefront_db_url,
    _Join_Data_5.storefront_id,
    _Join_Data_5.last_notice_type,
    _Join_Data_5.last_notice_sent,
    _Join_Data_5.notes,
    _Join_Data_5.invoice_id,
    _Join_Data_5.job_id,
    _Join_Data_5.usps_tracking,
    _Join_Data_5.delivery_status,
    _Join_Data_5.delivery_date,
    _Join_Data_5.enforcement_history,
    _Join_Data_5.c2m_error_status,
    _Join_Data_5.recipient_address,
    _Join_Data_5.platform_sent,
    _Join_Data_5.new_storefront_within_7_days,
    _Join_Data_5.days_since_first_listing,
    _Join_Data_5.days_since_last_listing,
    _Join_Data_5.new_storefront_within_2_days,
    _Join_Data_5.new_storefront_within_14_days,
    _Join_Data_5.new_storefront_within_28_days,
    _Join_Data_5.internal_id,
    _Join_Data_5.seller_id,
    _Join_Data_5.name,
    _Join_Data_5.last_scraped_at,
    _Join_Data_5.address_line1,
    _Join_Data_5.address_line2,
    _Join_Data_5.review_count,
    _Join_Data_5.review_count_last_30,
    _Join_Data_5.batch_id,
    _Join_Data_5.batch_last_run,
    _Join_Data_5.address,
    _Join_Data_5.violator_city,
    _Join_Data_5.violator_state,
    _Join_Data_5.zip,
    _Join_Data_5.violator_country,
    _Join_Data_5.email,
    _Join_Data_5.seller_contact,
    _Join_Data_5.phone,
    _Join_Data_5.email_available,
    _Join_Data_5.address_available,
    _Join_Data_5.buy_box_status,
    _Join_Data_5.buybox_status_date,
    _Group_By_4.vendor_code AS vendor_code
  FROM _Join_Data_5
  LEFT JOIN _Group_By_4
    ON _Join_Data_5.upc = _Group_By_4.upc
), _Add_Formula_4 AS (
  SELECT
    brand,
    amazonid,
    first_seen_date,
    last_seen_date,
    scraped_date,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    asin_link,
    inventory_value,
    offer_type,
    price_δ_%_-_map,
    price_δ_$_-_map,
    authorized_sellers,
    map_exceptions,
    map_violations_sku_map,
    storefront_db_url,
    storefront_id,
    last_notice_type,
    last_notice_sent,
    notes,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    enforcement_history,
    c2m_error_status,
    recipient_address,
    platform_sent,
    new_storefront_within_7_days,
    days_since_first_listing,
    days_since_last_listing,
    new_storefront_within_2_days,
    new_storefront_within_14_days,
    new_storefront_within_28_days,
    internal_id,
    seller_id,
    name,
    last_scraped_at,
    address_line1,
    address_line2,
    review_count,
    review_count_last_30,
    batch_id,
    batch_last_run,
    address,
    violator_city,
    violator_state,
    zip,
    violator_country,
    email,
    seller_contact,
    phone,
    email_available,
    address_available,
    buy_box_status,
    buybox_status_date,
    vendor_code,
    (
      CONCAT(
        '<div><a href=https:_www_google_ca_searchtbm=shopandq=',upc,_'andq=',Brand,_'andq=',upc_name,',
        'target=blank>',
        upc,
        '</a></div>'
      )
    ) AS upc_search_google
  FROM _Add_Vendor_Code
), _CA_Enforcement_DS AS (
  SELECT
    *
  FROM _Add_Formula_4
)
SELECT
  *
FROM _CA_Enforcement_DS