/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 708
Dataflow Name: (aDESTROY) BP Storefront Priority Inventory DF
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 7
  Successful: 7
  Failed: 0
  Unique Action Types: 6
  Action Types: DateCalculator, Filter, LoadFromVault, MergeJoin, PublishToVault, SelectValues
  Pipelines: 2

Generated: 2025-07-02 10:26:03
================================================================================
*/
WITH _Limit_Buster_Inventory_DS AS (
  SELECT
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    bp_brand_id,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_id,
    storefront_enforceable,
    storefront_enforceable_code
  FROM Limit_Buster_Inventory_DS
), _BP_Storefront_Priority AS (
  SELECT
    *
  FROM BP_Storefront_Priority
), _Calculate_Date_Difference AS (
  SELECT
    DATEDIFF(DAY, scraped_date, NULL) AS days_ago,
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    bp_brand_id,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_id,
    storefront_enforceable,
    storefront_enforceable_code
  FROM _Limit_Buster_Inventory_DS
), _Filter_Last_30_Days AS (
  SELECT
    *
  FROM _Calculate_Date_Difference
  WHERE
    days_ago >= '-30'
), _Select_Columns AS (
  SELECT
    sellerid,
    sellername,
    scraped_date,
    units,
    revenue,
    storefront_name,
    sales_country_id,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    amazonid,
    asin,
    redirect_asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    limit_buster_units,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    days_ago
  FROM _Filter_Last_30_Days
), _Join_Data AS (
  SELECT
    bp_storefront_priority_*,
    _Select_Columns.sellerid,
    _Select_Columns.sellername,
    _Select_Columns.scraped_date,
    _Select_Columns.units,
    _Select_Columns.revenue,
    _Select_Columns.storefront_name,
    _Select_Columns.sales_country_id,
    _Select_Columns.asins_units,
    _Select_Columns.revenue_brand,
    _Select_Columns.asins_units_brand,
    _Select_Columns.percent_mix_of_brand,
    _Select_Columns.revenue_rank_r3mth,
    _Select_Columns.revenue_distribution_r3mth,
    _Select_Columns.amazonid,
    _Select_Columns.asin,
    _Select_Columns.redirect_asin,
    _Select_Columns.isquantityrestricted,
    _Select_Columns.brand,
    _Select_Columns.isfba,
    _Select_Columns.upc,
    _Select_Columns.upc_name,
    _Select_Columns.msrp,
    _Select_Columns.srp,
    _Select_Columns.map,
    _Select_Columns.parent_category,
    _Select_Columns.child_category,
    _Select_Columns.child_category_2,
    _Select_Columns.child_category_3,
    _Select_Columns.partner_name,
    _Select_Columns.country_id,
    _Select_Columns.offer_price,
    _Select_Columns.offer_date_max_price,
    _Select_Columns.limit_buster_units,
    _Select_Columns.created_date,
    _Select_Columns.created_time,
    _Select_Columns.sku_map,
    _Select_Columns.sku_name,
    _Select_Columns.buy_box_count,
    _Select_Columns.partner_-_brand,
    _Select_Columns.cod_condition,
    _Select_Columns.unit_in_listing,
    _Select_Columns.date,
    _Select_Columns.day_of_week,
    _Select_Columns.month,
    _Select_Columns.445_week,
    _Select_Columns.445_week_number,
    _Select_Columns.445_month,
    _Select_Columns.445_month_number,
    _Select_Columns.445_calendar,
    _Select_Columns.445_year,
    _Select_Columns.bbc_original_status,
    _Select_Columns.bbc_2_8_22_status,
    _Select_Columns.days_ago
  FROM _BP_Storefront_Priority
  FULL JOIN _Select_Columns
    ON _BP_Storefront_Priority.seller_id = _Select_Columns.sellerid
), _aDESTROY_BP_Storefront_Priority_Inventory_DS AS (
  SELECT
    *
  FROM _Join_Data
)
SELECT
  *
FROM _aDESTROY_BP_Storefront_Priority_Inventory_DS