/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 695
Dataflow Name: Fill Rate Builder
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 59
  Successful: 59
  Failed: 0
  Unique Action Types: 9
  Action Types: Constant, ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, PublishToVault, SelectValues, UnionAll
  Pipelines: 4

Generated: 2025-07-02 10:24:16
================================================================================
*/
WITH _ns_po_data_wHistory AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    date_arrived,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date
  FROM ns_po_data_wHistory
), _Product_List_DataSet AS (
  SELECT
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    deleted_at,
    fnsku,
    id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    batch_id,
    batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name
  FROM Product_List_DataSet
), _purchase_orders AS (
  SELECT
    cancelled,
    carrier,
    created_at,
    deleted_at,
    estimated_arrival,
    fba_ship_from_id,
    id,
    inventory_vendor_id,
    is_partial_order,
    name,
    vendor,
    number,
    order_total,
    other_fees,
    po_bill_to_id,
    po_ship_to_id,
    shipping_total,
    shipping_total_3rd_party,
    status,
    status_changed_at,
    target_days_coverage,
    tax,
    total_lead_time,
    tracking_number,
    updated_at,
    vendor_invoice_date,
    vendor_invoice_number,
    status_name,
    first_po_date,
    amazon_seller_id,
    type_id,
    type,
    priority_id,
    priority,
    shipping_method_id,
    shipping_method,
    memo,
    is_msku_changeover,
    netsuite_id,
    batch_id,
    batch_last_run
  FROM purchase_orders
), _purchase_order_line_items AS (
  SELECT
    cost,
    created_at,
    created_by,
    daily_velocity,
    deleted_at,
    deleted_by,
    discount,
    fnsku,
    id,
    kit_qty,
    msku,
    purchase_order_id,
    reorder_qty_msku,
    reorder_qty_upc,
    total_inventory,
    upc,
    upc_name,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    batch_id,
    batch_last_run
  FROM purchase_order_line_items
), _Join_Data_4 AS (
  SELECT
    _ns_po_data_wHistory.id,
    _ns_po_data_wHistory.internal_id,
    _ns_po_data_wHistory.line_id,
    _ns_po_data_wHistory.subsidiary,
    _ns_po_data_wHistory.date,
    _ns_po_data_wHistory.date_created,
    _ns_po_data_wHistory.vendor_internal_id,
    _ns_po_data_wHistory.vendor_number,
    _ns_po_data_wHistory.vendor_name,
    _ns_po_data_wHistory.status,
    _ns_po_data_wHistory.due_date_or_receive_by,
    _ns_po_data_wHistory.expiration_date,
    _ns_po_data_wHistory.document_number,
    _ns_po_data_wHistory.currency,
    _ns_po_data_wHistory.location_id,
    _ns_po_data_wHistory.item_internal_id,
    _ns_po_data_wHistory.original_ordered,
    _ns_po_data_wHistory.quantity,
    _ns_po_data_wHistory.quantity_fulfilled_or_received,
    _ns_po_data_wHistory.quantity_billed,
    _ns_po_data_wHistory.rate,
    _ns_po_data_wHistory.created_by,
    _ns_po_data_wHistory.transfer_reference_id,
    _ns_po_data_wHistory.created_at,
    _ns_po_data_wHistory.updated_at,
    _ns_po_data_wHistory.subsidiary_name,
    _ns_po_data_wHistory.created_by_id,
    _ns_po_data_wHistory.created_by_name,
    _ns_po_data_wHistory.vid_po_number,
    _ns_po_data_wHistory.deleted_at,
    _ns_po_data_wHistory.date_arrived,
    _ns_po_data_wHistory.additional_arrival_details,
    _ns_po_data_wHistory.ns_instance,
    _ns_po_data_wHistory.internal_notes,
    _ns_po_data_wHistory.memo,
    _ns_po_data_wHistory.batch_id,
    _ns_po_data_wHistory.batch_last_run,
    _ns_po_data_wHistory.receipts_purchase_order_internal_id,
    _ns_po_data_wHistory.receipts_item_internal_id,
    _ns_po_data_wHistory.receipts_quantity,
    _ns_po_data_wHistory.receipts_date_created,
    _ns_po_data_wHistory.receipts_rate,
    _ns_po_data_wHistory.last_receipt_date,
    _ns_po_data_wHistory.ns_locations_created_at,
    _ns_po_data_wHistory.fbaprep_warehouse_id,
    _ns_po_data_wHistory.ns_locations_id,
    _ns_po_data_wHistory.is_3pl_inventory,
    _ns_po_data_wHistory.is_active,
    _ns_po_data_wHistory.is_available_inventory,
    _ns_po_data_wHistory.is_canada_3pl,
    _ns_po_data_wHistory.is_canada_3pl_nonsellable,
    _ns_po_data_wHistory.is_do_not_count,
    _ns_po_data_wHistory.is_domestic_3pl,
    _ns_po_data_wHistory.is_domestic_3pl_nonsellable,
    _ns_po_data_wHistory.is_eu_3pl,
    _ns_po_data_wHistory.is_eu_3pl_nonsellable,
    _ns_po_data_wHistory.is_fbm_only,
    _ns_po_data_wHistory.is_international_available,
    _ns_po_data_wHistory.is_international_fba,
    _ns_po_data_wHistory.is_international_fba_nonsellable,
    _ns_po_data_wHistory.is_international_nonsellable,
    _ns_po_data_wHistory.is_local_available,
    _ns_po_data_wHistory.is_local_nonsellable,
    _ns_po_data_wHistory.is_nonsellable_inventory,
    _ns_po_data_wHistory.is_uk_3pl,
    _ns_po_data_wHistory.is_uk_3pl_nonsellable,
    _ns_po_data_wHistory.is_us_fba,
    _ns_po_data_wHistory.is_us_fba_nonsellable,
    _ns_po_data_wHistory.is_wfs,
    _ns_po_data_wHistory.is_wfs_nonsellable,
    _ns_po_data_wHistory.location_name,
    _ns_po_data_wHistory.ns_locations_subsidiary,
    _ns_po_data_wHistory.subsidiary_id,
    _ns_po_data_wHistory.type_catalog_ns_location_id,
    _ns_po_data_wHistory.ns_locations_updated_at,
    _ns_po_data_wHistory.ns_locations_batch_id,
    _ns_po_data_wHistory.ns_locations_batch_last_run,
    _ns_po_data_wHistory.item_activate_item_for_sale,
    _ns_po_data_wHistory.item_amazon_fba_price,
    _ns_po_data_wHistory.item_amazon_active,
    _ns_po_data_wHistory.item_asin,
    _ns_po_data_wHistory.item_average_cost,
    _ns_po_data_wHistory.item_description,
    _ns_po_data_wHistory.ns_item_internal_id,
    _ns_po_data_wHistory.item_external_id,
    _ns_po_data_wHistory.item_created_at,
    _ns_po_data_wHistory.item_item_status,
    _ns_po_data_wHistory.item_item_status_text,
    _ns_po_data_wHistory.item_name,
    _ns_po_data_wHistory.item_upc_code,
    _ns_po_data_wHistory.item_fba_fnsku,
    _ns_po_data_wHistory.brand,
    _ns_po_data_wHistory.partner,
    _ns_po_data_wHistory.amazon_price,
    _ns_po_data_wHistory.cart_price,
    _ns_po_data_wHistory.purchase_price,
    _ns_po_data_wHistory.last_order_date,
    _ns_po_data_wHistory.upc_last_order_last_receipt_date,
    _ns_po_data_wHistory.po_year,
    _ns_po_data_wHistory.po_month,
    _ns_po_data_wHistory.received_year,
    _ns_po_data_wHistory.recevied_month,
    _ns_po_data_wHistory.received_flag,
    _ns_po_data_wHistory.lead_time,
    _ns_po_data_wHistory.data_source,
    _ns_po_data_wHistory.receiving_time,
    _ns_po_data_wHistory.lead_time2,
    _ns_po_data_wHistory.yesterday,
    _ns_po_data_wHistory.yesterdayfilter,
    _ns_po_data_wHistory.yesterdayarrived,
    _ns_po_data_wHistory.po_internal_id,
    _ns_po_data_wHistory.terms,
    _ns_po_data_wHistory.inv_ref_status,
    _ns_po_data_wHistory.terms_-_days,
    _ns_po_data_wHistory.inv_transfer_number,
    _ns_po_data_wHistory.inv_status,
    _ns_po_data_wHistory.po_amount,
    _ns_po_data_wHistory.po_expected_ship_date,
    _ns_po_data_wHistory.expected_payment_due_date,
    _ns_po_data_wHistory.po_expected_receipt_date,
    _Product_List_DataSet.amazon_seller_id,
    _Product_List_DataSet.asin,
    _Product_List_DataSet.brand_id,
    _Product_List_DataSet.client_id,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at AS product_list_dataset_deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.id AS product_list_dataset_id,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.sku,
    _Product_List_DataSet.units_in_listing,
    _Product_List_DataSet.upc,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.batch_id AS product_list_dataset_batch_id,
    _Product_List_DataSet.batch_last_run AS product_list_dataset_batch_last_run,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency AS product_list_dataset_currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.brand AS product_list_dataset_brand,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.country_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.name,
    _Product_List_DataSet.upc_name
  FROM _ns_po_data_wHistory
  INNER JOIN _Product_List_DataSet
    ON _ns_po_data_wHistory.item_upc_code = _Product_List_DataSet.upc
), _PO_Created AS (
  SELECT
    *
  FROM _purchase_orders
  WHERE
    (
      status = '1' AND created_at >= CURRENT_DATE - 120
    )
), _PO_Approved AS (
  SELECT
    *
  FROM _purchase_orders
  WHERE
    created_at >= CURRENT_DATE - 120
), _Filter_Rows AS (
  SELECT
    *
  FROM _purchase_order_line_items
  WHERE
    NOT upc IS NULL
), _Group_By_1 AS (
  SELECT
    document_number,
    MAX(receipts_date_created) AS max_receipt_date
  FROM _Join_Data_4
  GROUP BY
    document_number
), _Join_Data AS (
  SELECT
    _PO_Created.cancelled,
    _PO_Created.carrier,
    _PO_Created.created_at,
    _PO_Created.deleted_at,
    _PO_Created.estimated_arrival,
    _PO_Created.fba_ship_from_id,
    _PO_Created.id,
    _PO_Created.inventory_vendor_id,
    _PO_Created.is_partial_order,
    _PO_Created.name,
    _PO_Created.vendor,
    _PO_Created.number,
    _PO_Created.order_total,
    _PO_Created.other_fees,
    _PO_Created.po_bill_to_id,
    _PO_Created.po_ship_to_id,
    _PO_Created.shipping_total,
    _PO_Created.shipping_total_3rd_party,
    _PO_Created.status,
    _PO_Created.status_changed_at,
    _PO_Created.target_days_coverage,
    _PO_Created.tax,
    _PO_Created.total_lead_time,
    _PO_Created.tracking_number,
    _PO_Created.updated_at,
    _PO_Created.vendor_invoice_date,
    _PO_Created.vendor_invoice_number,
    _PO_Created.status_name,
    _PO_Created.first_po_date,
    _PO_Created.amazon_seller_id,
    _PO_Created.type_id,
    _PO_Created.type,
    _PO_Created.priority_id,
    _PO_Created.priority,
    _PO_Created.shipping_method_id,
    _PO_Created.shipping_method,
    _PO_Created.memo,
    _PO_Created.is_msku_changeover,
    _PO_Created.netsuite_id,
    _PO_Created.batch_id,
    _PO_Created.batch_last_run,
    _Filter_Rows.cost,
    _Filter_Rows.created_at AS purchase_order_line_items_created_at,
    _Filter_Rows.created_by,
    _Filter_Rows.daily_velocity,
    _Filter_Rows.deleted_at AS purchase_order_line_items_deleted_at,
    _Filter_Rows.deleted_by,
    _Filter_Rows.discount,
    _Filter_Rows.fnsku,
    _Filter_Rows.id AS purchase_order_line_items_id,
    _Filter_Rows.kit_qty,
    _Filter_Rows.msku,
    _Filter_Rows.purchase_order_id,
    _Filter_Rows.reorder_qty_msku,
    _Filter_Rows.reorder_qty_upc,
    _Filter_Rows.total_inventory,
    _Filter_Rows.upc,
    _Filter_Rows.upc_name,
    _Filter_Rows.updated_at AS purchase_order_line_items_updated_at,
    _Filter_Rows.updated_by,
    _Filter_Rows.vendor_sku,
    _Filter_Rows.wholesale_price,
    _Filter_Rows.batch_id AS purchase_order_line_items_batch_id,
    _Filter_Rows.batch_last_run AS purchase_order_line_items_batch_last_run
  FROM _PO_Created
  INNER JOIN _Filter_Rows
    ON _PO_Created.id = _Filter_Rows.purchase_order_id
), _Join_Data_1 AS (
  SELECT
    _PO_Approved.cancelled,
    _PO_Approved.carrier,
    _PO_Approved.created_at,
    _PO_Approved.deleted_at,
    _PO_Approved.estimated_arrival,
    _PO_Approved.fba_ship_from_id,
    _PO_Approved.id,
    _PO_Approved.inventory_vendor_id,
    _PO_Approved.is_partial_order,
    _PO_Approved.name,
    _PO_Approved.vendor,
    _PO_Approved.number,
    _PO_Approved.order_total,
    _PO_Approved.other_fees,
    _PO_Approved.po_bill_to_id,
    _PO_Approved.po_ship_to_id,
    _PO_Approved.shipping_total,
    _PO_Approved.shipping_total_3rd_party,
    _PO_Approved.status,
    _PO_Approved.status_changed_at,
    _PO_Approved.target_days_coverage,
    _PO_Approved.tax,
    _PO_Approved.total_lead_time,
    _PO_Approved.tracking_number,
    _PO_Approved.updated_at,
    _PO_Approved.vendor_invoice_date,
    _PO_Approved.vendor_invoice_number,
    _PO_Approved.status_name,
    _PO_Approved.first_po_date,
    _PO_Approved.amazon_seller_id,
    _PO_Approved.type_id,
    _PO_Approved.type,
    _PO_Approved.priority_id,
    _PO_Approved.priority,
    _PO_Approved.shipping_method_id,
    _PO_Approved.shipping_method,
    _PO_Approved.memo,
    _PO_Approved.is_msku_changeover,
    _PO_Approved.netsuite_id,
    _PO_Approved.batch_id,
    _PO_Approved.batch_last_run,
    _Filter_Rows.cost,
    _Filter_Rows.created_at AS purchase_order_line_items_created_at,
    _Filter_Rows.created_by,
    _Filter_Rows.daily_velocity,
    _Filter_Rows.deleted_at AS purchase_order_line_items_deleted_at,
    _Filter_Rows.deleted_by,
    _Filter_Rows.discount,
    _Filter_Rows.fnsku,
    _Filter_Rows.id AS purchase_order_line_items_id,
    _Filter_Rows.kit_qty,
    _Filter_Rows.msku,
    _Filter_Rows.purchase_order_id,
    _Filter_Rows.reorder_qty_msku,
    _Filter_Rows.reorder_qty_upc,
    _Filter_Rows.total_inventory,
    _Filter_Rows.upc,
    _Filter_Rows.upc_name,
    _Filter_Rows.updated_at AS purchase_order_line_items_updated_at,
    _Filter_Rows.updated_by,
    _Filter_Rows.vendor_sku,
    _Filter_Rows.wholesale_price,
    _Filter_Rows.batch_id AS purchase_order_line_items_batch_id,
    _Filter_Rows.batch_last_run AS purchase_order_line_items_batch_last_run
  FROM _PO_Approved
  INNER JOIN _Filter_Rows
    ON _PO_Approved.id = _Filter_Rows.purchase_order_id
), _Join_Data_5 AS (
  SELECT
    _Join_Data_4.id,
    _Join_Data_4.internal_id,
    _Join_Data_4.line_id,
    _Join_Data_4.subsidiary,
    _Join_Data_4.date,
    _Join_Data_4.date_created,
    _Join_Data_4.vendor_internal_id,
    _Join_Data_4.vendor_number,
    _Join_Data_4.vendor_name,
    _Join_Data_4.status,
    _Join_Data_4.due_date_or_receive_by,
    _Join_Data_4.expiration_date,
    _Join_Data_4.document_number,
    _Join_Data_4.currency,
    _Join_Data_4.location_id,
    _Join_Data_4.item_internal_id,
    _Join_Data_4.original_ordered,
    _Join_Data_4.quantity,
    _Join_Data_4.quantity_fulfilled_or_received,
    _Join_Data_4.quantity_billed,
    _Join_Data_4.rate,
    _Join_Data_4.created_by,
    _Join_Data_4.transfer_reference_id,
    _Join_Data_4.created_at,
    _Join_Data_4.updated_at,
    _Join_Data_4.subsidiary_name,
    _Join_Data_4.created_by_id,
    _Join_Data_4.created_by_name,
    _Join_Data_4.vid_po_number,
    _Join_Data_4.deleted_at,
    _Join_Data_4.date_arrived,
    _Join_Data_4.additional_arrival_details,
    _Join_Data_4.ns_instance,
    _Join_Data_4.internal_notes,
    _Join_Data_4.memo,
    _Join_Data_4.batch_id,
    _Join_Data_4.batch_last_run,
    _Join_Data_4.receipts_purchase_order_internal_id,
    _Join_Data_4.receipts_item_internal_id,
    _Join_Data_4.receipts_quantity,
    _Join_Data_4.receipts_date_created,
    _Join_Data_4.receipts_rate,
    _Join_Data_4.last_receipt_date,
    _Join_Data_4.ns_locations_created_at,
    _Join_Data_4.fbaprep_warehouse_id,
    _Join_Data_4.ns_locations_id,
    _Join_Data_4.is_3pl_inventory,
    _Join_Data_4.is_active,
    _Join_Data_4.is_available_inventory,
    _Join_Data_4.is_canada_3pl,
    _Join_Data_4.is_canada_3pl_nonsellable,
    _Join_Data_4.is_do_not_count,
    _Join_Data_4.is_domestic_3pl,
    _Join_Data_4.is_domestic_3pl_nonsellable,
    _Join_Data_4.is_eu_3pl,
    _Join_Data_4.is_eu_3pl_nonsellable,
    _Join_Data_4.is_fbm_only,
    _Join_Data_4.is_international_available,
    _Join_Data_4.is_international_fba,
    _Join_Data_4.is_international_fba_nonsellable,
    _Join_Data_4.is_international_nonsellable,
    _Join_Data_4.is_local_available,
    _Join_Data_4.is_local_nonsellable,
    _Join_Data_4.is_nonsellable_inventory,
    _Join_Data_4.is_uk_3pl,
    _Join_Data_4.is_uk_3pl_nonsellable,
    _Join_Data_4.is_us_fba,
    _Join_Data_4.is_us_fba_nonsellable,
    _Join_Data_4.is_wfs,
    _Join_Data_4.is_wfs_nonsellable,
    _Join_Data_4.location_name,
    _Join_Data_4.ns_locations_subsidiary,
    _Join_Data_4.subsidiary_id,
    _Join_Data_4.type_catalog_ns_location_id,
    _Join_Data_4.ns_locations_updated_at,
    _Join_Data_4.ns_locations_batch_id,
    _Join_Data_4.ns_locations_batch_last_run,
    _Join_Data_4.item_activate_item_for_sale,
    _Join_Data_4.item_amazon_fba_price,
    _Join_Data_4.item_amazon_active,
    _Join_Data_4.item_asin,
    _Join_Data_4.item_average_cost,
    _Join_Data_4.item_description,
    _Join_Data_4.ns_item_internal_id,
    _Join_Data_4.item_external_id,
    _Join_Data_4.item_created_at,
    _Join_Data_4.item_item_status,
    _Join_Data_4.item_item_status_text,
    _Join_Data_4.item_name,
    _Join_Data_4.item_upc_code,
    _Join_Data_4.item_fba_fnsku,
    _Join_Data_4.brand,
    _Join_Data_4.partner,
    _Join_Data_4.amazon_price,
    _Join_Data_4.cart_price,
    _Join_Data_4.purchase_price,
    _Join_Data_4.last_order_date,
    _Join_Data_4.upc_last_order_last_receipt_date,
    _Join_Data_4.po_year,
    _Join_Data_4.po_month,
    _Join_Data_4.received_year,
    _Join_Data_4.recevied_month,
    _Join_Data_4.received_flag,
    _Join_Data_4.lead_time,
    _Join_Data_4.data_source,
    _Join_Data_4.receiving_time,
    _Join_Data_4.lead_time2,
    _Join_Data_4.yesterday,
    _Join_Data_4.yesterdayfilter,
    _Join_Data_4.yesterdayarrived,
    _Join_Data_4.po_internal_id,
    _Join_Data_4.terms,
    _Join_Data_4.inv_ref_status,
    _Join_Data_4.terms_-_days,
    _Join_Data_4.inv_transfer_number,
    _Join_Data_4.inv_status,
    _Join_Data_4.po_amount,
    _Join_Data_4.po_expected_ship_date,
    _Join_Data_4.expected_payment_due_date,
    _Join_Data_4.po_expected_receipt_date,
    _Join_Data_4.amazon_seller_id,
    _Join_Data_4.asin,
    _Join_Data_4.brand_id,
    _Join_Data_4.client_id,
    _Join_Data_4.cost,
    _Join_Data_4.product_list_dataset_deleted_at,
    _Join_Data_4.fnsku,
    _Join_Data_4.product_list_dataset_id,
    _Join_Data_4.is_bundle,
    _Join_Data_4.reorder_status,
    _Join_Data_4.sku,
    _Join_Data_4.units_in_listing,
    _Join_Data_4.upc,
    _Join_Data_4.vendor_parameter_id,
    _Join_Data_4.vendor_sku,
    _Join_Data_4.product_list_dataset_batch_id,
    _Join_Data_4.product_list_dataset_batch_last_run,
    _Join_Data_4.advertisement_enabled,
    _Join_Data_4.description,
    _Join_Data_4.estimated_annual_sales,
    _Join_Data_4.member_since,
    _Join_Data_4.partner_name,
    _Join_Data_4.product_list_dataset_currency,
    _Join_Data_4.estimated_anual_sales,
    _Join_Data_4.legacy_brand_id,
    _Join_Data_4.map_formula,
    _Join_Data_4.product_list_dataset_brand,
    _Join_Data_4.category,
    _Join_Data_4.subcategory,
    _Join_Data_4.brand_growth_target,
    _Join_Data_4.msrp,
    _Join_Data_4.map,
    _Join_Data_4.amazon_asin_id,
    _Join_Data_4.upc_id,
    _Join_Data_4.country_id,
    _Join_Data_4.srp,
    _Join_Data_4.upc_srp,
    _Join_Data_4.upc_default_cost,
    _Join_Data_4.upc_default_discount,
    _Join_Data_4.default_cost,
    _Join_Data_4.default_discount,
    _Join_Data_4.upc_map,
    _Join_Data_4.wholesale_price,
    _Join_Data_4.parent_asin,
    _Join_Data_4.catalog_source,
    _Join_Data_4.country_of_origin,
    _Join_Data_4.min_order_qty,
    _Join_Data_4.units_per_case,
    _Join_Data_4.unit_lxwxh_inches,
    _Join_Data_4.unit_weight_lb,
    _Join_Data_4.sku_reorder_status,
    _Join_Data_4.upc_reorder_status,
    _Join_Data_4.is_discontinued_status,
    _Join_Data_4.upc_components,
    _Join_Data_4.catalog_last_appearance,
    _Join_Data_4.parent_category,
    _Join_Data_4.child_category,
    _Join_Data_4.child_category_3,
    _Join_Data_4.child_category_2,
    _Join_Data_4.sku_reorder_comments,
    _Join_Data_4.upc_reorder_comments,
    _Join_Data_4.is_preferred_sku_by_asin,
    _Join_Data_4.seller_name,
    _Join_Data_4.countries_name,
    _Join_Data_4.sku_created_date,
    _Join_Data_4.upc_created_date,
    _Join_Data_4.sku_cost,
    _Join_Data_4.is_current,
    _Join_Data_4.fulfillment_channel,
    _Join_Data_4.last_seen_price,
    _Join_Data_4.last_known_price,
    _Join_Data_4.estimated_units_sold_last_month,
    _Join_Data_4.hero,
    _Join_Data_4.upc_count_total_components,
    _Join_Data_4.brand_created_at,
    _Join_Data_4.seller_start_date,
    _Join_Data_4.brand_start_date,
    _Join_Data_4.amazon_seller_central_accounts_created_at,
    _Join_Data_4.bp_partner_name,
    _Join_Data_4.bp_brand_name,
    _Join_Data_4.partner_-_brand,
    _Join_Data_4.seller_created_at,
    _Join_Data_4.preferred_skus_on_asin,
    _Join_Data_4.qa_-_count_fbm_offers_current,
    _Join_Data_4.qa_-_count_fba_offers_current,
    _Join_Data_4.qa_-count_reorder_status_yes,
    _Join_Data_4.qa_-count_preferred_skus,
    _Join_Data_4.qa_-current_preferred_skus,
    _Join_Data_4.is_current_asin,
    _Join_Data_4.name,
    _Join_Data_4.upc_name,
    _Group_By_1.max_receipt_date
  FROM _Join_Data_4
  INNER JOIN _Group_By_1
    ON _Join_Data_4.document_number = _Group_By_1.document_number
), _PO_Creation AS (
  SELECT
    id,
    number,
    upc,
    purchase_order_id,
    vendor,
    created_at,
    SUM(reorder_qty_upc) AS created_qty_upc
  FROM _Join_Data
  GROUP BY
    id,
    number,
    upc,
    purchase_order_id,
    vendor,
    created_at
), _PO_Approved AS (
  SELECT
    number,
    upc,
    cancelled,
    SUM(reorder_qty_upc) AS approved_qty_upc,
    MIN(netsuite_id) AS netsuite_id
  FROM _Join_Data_1
  GROUP BY
    number,
    upc,
    cancelled
), _Add_Formula AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date,
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    product_list_dataset_deleted_at,
    fnsku,
    product_list_dataset_id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    product_list_dataset_batch_id,
    product_list_dataset_batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    product_list_dataset_currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    product_list_dataset_brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name,
    max_receipt_date,
    (
      COALESCE(date_arrived, receipts_date_created, max_receipt_date)
    ) AS date_arrived
  FROM _Join_Data_5
), _Join_Data_2 AS (
  SELECT
    _PO_Creation.id,
    _PO_Creation.number,
    _PO_Creation.upc,
    _PO_Creation.purchase_order_id,
    _PO_Creation.vendor,
    _PO_Creation.created_at,
    _PO_Creation.created_qty_upc,
    _PO_Approved.cancelled,
    _PO_Approved.approved_qty_upc,
    _PO_Approved.netsuite_id
  FROM _PO_Creation
  LEFT JOIN _PO_Approved
    ON _PO_Creation.number = _PO_Approved.number
    AND _PO_Creation.upc = _PO_Approved.upc
), _step_120_Days_1 AS (
  SELECT
    *
  FROM _Add_Formula
  WHERE
    date_arrived > TODAY() - 120
), _step_90_Days_1 AS (
  SELECT
    *
  FROM _Add_Formula
  WHERE
    date_arrived > TODAY() - 90
), _step_60_Days_1 AS (
  SELECT
    *
  FROM _Add_Formula
  WHERE
    date_arrived > TODAY() - 60
), _All_Time_1 AS (
  SELECT
    *
  FROM _Add_Formula
  WHERE
    (
      NOT item_upc_code IS NULL
      AND status IN (
        'fullyBilled',
        'partiallyReceived',
        'pendingBilling',
        'pendingBillPartReceived',
        'closed'
      )
    )
), _Output_QA1 AS (
  SELECT
    *
  FROM _Add_Formula
), _Add_Constants AS (
  SELECT
    1 AS constant_value
), _QA_UPC_Lokkup AS (
  SELECT
    *
  FROM _Join_Data_2
), _Calculate_Fill_Rate_121 AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    date_arrived,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date,
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    product_list_dataset_deleted_at,
    fnsku,
    product_list_dataset_id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    product_list_dataset_batch_id,
    product_list_dataset_batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    product_list_dataset_currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    product_list_dataset_brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name,
    max_receipt_date,
    (
      CASE
        WHEN COALESCE(quantity, 0) > COALESCE(original_ordered, 0)
        THEN COALESCE(quantity, 0)
        ELSE COALESCE(original_ordered, 0)
      END
    ) AS updated_order_qty
  FROM _step_120_Days_1
), _Calculate_Fill_Rate_91 AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    date_arrived,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date,
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    product_list_dataset_deleted_at,
    fnsku,
    product_list_dataset_id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    product_list_dataset_batch_id,
    product_list_dataset_batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    product_list_dataset_currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    product_list_dataset_brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name,
    max_receipt_date,
    (
      CASE
        WHEN COALESCE(quantity, 0) > COALESCE(original_ordered, 0)
        THEN COALESCE(quantity, 0)
        ELSE COALESCE(original_ordered, 0)
      END
    ) AS updated_order_qty
  FROM _step_90_Days_1
), _Calculate_Fill_Rate_61 AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    date_arrived,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date,
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    product_list_dataset_deleted_at,
    fnsku,
    product_list_dataset_id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    product_list_dataset_batch_id,
    product_list_dataset_batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    product_list_dataset_currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    product_list_dataset_brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name,
    max_receipt_date,
    (
      CASE
        WHEN COALESCE(quantity, 0) > COALESCE(original_ordered, 0)
        THEN COALESCE(quantity, 0)
        ELSE COALESCE(original_ordered, 0)
      END
    ) AS updated_order_qty
  FROM _step_60_Days_1
), _Calculate_Fill_Rate_All_Time_1 AS (
  SELECT
    id,
    internal_id,
    line_id,
    subsidiary,
    date,
    date_created,
    vendor_internal_id,
    vendor_number,
    vendor_name,
    status,
    due_date_or_receive_by,
    expiration_date,
    document_number,
    currency,
    location_id,
    item_internal_id,
    original_ordered,
    quantity,
    quantity_fulfilled_or_received,
    quantity_billed,
    rate,
    created_by,
    transfer_reference_id,
    created_at,
    updated_at,
    subsidiary_name,
    created_by_id,
    created_by_name,
    vid_po_number,
    deleted_at,
    date_arrived,
    additional_arrival_details,
    ns_instance,
    internal_notes,
    memo,
    batch_id,
    batch_last_run,
    receipts_purchase_order_internal_id,
    receipts_item_internal_id,
    receipts_quantity,
    receipts_date_created,
    receipts_rate,
    last_receipt_date,
    ns_locations_created_at,
    fbaprep_warehouse_id,
    ns_locations_id,
    is_3pl_inventory,
    is_active,
    is_available_inventory,
    is_canada_3pl,
    is_canada_3pl_nonsellable,
    is_do_not_count,
    is_domestic_3pl,
    is_domestic_3pl_nonsellable,
    is_eu_3pl,
    is_eu_3pl_nonsellable,
    is_fbm_only,
    is_international_available,
    is_international_fba,
    is_international_fba_nonsellable,
    is_international_nonsellable,
    is_local_available,
    is_local_nonsellable,
    is_nonsellable_inventory,
    is_uk_3pl,
    is_uk_3pl_nonsellable,
    is_us_fba,
    is_us_fba_nonsellable,
    is_wfs,
    is_wfs_nonsellable,
    location_name,
    ns_locations_subsidiary,
    subsidiary_id,
    type_catalog_ns_location_id,
    ns_locations_updated_at,
    ns_locations_batch_id,
    ns_locations_batch_last_run,
    item_activate_item_for_sale,
    item_amazon_fba_price,
    item_amazon_active,
    item_asin,
    item_average_cost,
    item_description,
    ns_item_internal_id,
    item_external_id,
    item_created_at,
    item_item_status,
    item_item_status_text,
    item_name,
    item_upc_code,
    item_fba_fnsku,
    brand,
    partner,
    amazon_price,
    cart_price,
    purchase_price,
    last_order_date,
    upc_last_order_last_receipt_date,
    po_year,
    po_month,
    received_year,
    recevied_month,
    received_flag,
    lead_time,
    data_source,
    receiving_time,
    lead_time2,
    yesterday,
    yesterdayfilter,
    yesterdayarrived,
    po_internal_id,
    terms,
    inv_ref_status,
    terms_-_days,
    inv_transfer_number,
    inv_status,
    po_amount,
    po_expected_ship_date,
    expected_payment_due_date,
    po_expected_receipt_date,
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    product_list_dataset_deleted_at,
    fnsku,
    product_list_dataset_id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    product_list_dataset_batch_id,
    product_list_dataset_batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    product_list_dataset_currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    product_list_dataset_brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name,
    max_receipt_date,
    (
      CASE
        WHEN COALESCE(quantity, 0) > COALESCE(original_ordered, 0)
        THEN COALESCE(quantity, 0)
        ELSE COALESCE(original_ordered, 0)
      END
    ) AS updated_order_qty
  FROM _All_Time_1
), _Clean_Up AS (
  SELECT
    number AS purchase_order_number,
    upc AS upc,
    created_qty_upc AS created_qty_upc,
    approved_qty_upc AS approved_qty_upc,
    vendor,
    created_at AS date_arrived,
    netsuite_id,
    quantity_fulfilled_or_received,
    cancelled
  FROM _Add_Constants
), _Select_121 AS (
  SELECT
    item_upc_code AS upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    product_list_dataset_brand AS brand,
    partner AS partner
  FROM _Calculate_Fill_Rate_121
), _Select_91 AS (
  SELECT
    item_upc_code AS upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    product_list_dataset_brand AS brand,
    partner
  FROM _Calculate_Fill_Rate_91
), _Select_61 AS (
  SELECT
    item_upc_code AS upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    product_list_dataset_brand AS brand,
    partner
  FROM _Calculate_Fill_Rate_61
), _Select_All_Time_1 AS (
  SELECT
    item_upc_code AS upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    product_list_dataset_brand AS brand,
    partner
  FROM _Calculate_Fill_Rate_All_Time_1
), _Filter_Rows_1 AS (
  SELECT
    *
  FROM _Clean_Up
  WHERE
    netsuite_id IS NULL OR netsuite_id = ''
), _Join_Data_3 AS (
  SELECT
    _Filter_Rows_1.purchase_order_number,
    _Filter_Rows_1.upc,
    _Filter_Rows_1.created_qty_upc,
    _Filter_Rows_1.approved_qty_upc,
    _Filter_Rows_1.vendor,
    _Filter_Rows_1.date_arrived,
    _Filter_Rows_1.netsuite_id,
    _Filter_Rows_1.cancelled,
    _Product_List_DataSet.amazon_seller_id,
    _Product_List_DataSet.asin,
    _Product_List_DataSet.brand_id,
    _Product_List_DataSet.client_id,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.id,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.sku,
    _Product_List_DataSet.units_in_listing,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.batch_id,
    _Product_List_DataSet.batch_last_run,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.brand,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.country_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.name,
    _Product_List_DataSet.upc_name
  FROM _Filter_Rows_1
  INNER JOIN _Product_List_DataSet
    ON _Filter_Rows_1.upc = _Product_List_DataSet.upc
), _QA_Missing_UPCs AS (
  SELECT
    *
  FROM _Filter_Rows_1
), _Select_Columns AS (
  SELECT
    upc,
    created_qty_upc,
    approved_qty_upc,
    vendor,
    date_arrived,
    netsuite_id,
    quantity_fulfilled_or_received,
    brand,
    partner_name AS partner
  FROM _Join_Data_3
), _Group_By AS (
  SELECT
    upc,
    date_arrived,
    SUM(created_qty_upc) AS updated_order_qty,
    SUM(quantity_fulfilled_or_received) AS quantity_fulfilled_or_received,
    MIN(brand) AS brand,
    MIN(partner) AS partner
  FROM _Select_Columns
  GROUP BY
    upc,
    date_arrived
), _PO_Creation_QA AS (
  SELECT
    *
  FROM _Group_By
), _Created_QTY_L120 AS (
  SELECT
    *
  FROM _Group_By
  WHERE
    date_arrived > TODAY() - 120
), _Created_QTY_L90 AS (
  SELECT
    *
  FROM _Group_By
  WHERE
    date_arrived > TODAY() - 90
), _Created_QTY_L60 AS (
  SELECT
    *
  FROM _Group_By
  WHERE
    date_arrived > TODAY() - 60
), _Created_QTY_L720 AS (
  SELECT
    *
  FROM _Group_By
  WHERE
    date_arrived > TODAY() - 722
), _Append_Rows AS (
  SELECT
    upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    brand,
    partner
  FROM _Select_121
  UNION ALL
  SELECT
    upc,
    CAST(updated_order_qty AS VARCHAR) AS updated_order_qty,
    CAST(quantity_fulfilled_or_received AS BIGINT) AS quantity_fulfilled_or_received,
    CAST(brand AS VARCHAR) AS brand,
    CAST(partner AS VARCHAR) AS partner
  FROM _Created_QTY_L120
), _Append_Rows_1 AS (
  SELECT
    upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    brand,
    partner
  FROM _Select_91
  UNION ALL
  SELECT
    upc,
    CAST(updated_order_qty AS VARCHAR) AS updated_order_qty,
    CAST(quantity_fulfilled_or_received AS BIGINT) AS quantity_fulfilled_or_received,
    CAST(brand AS VARCHAR) AS brand,
    CAST(NULL AS VARCHAR) AS partner
  FROM _Created_QTY_L90
), _Append_Rows_2 AS (
  SELECT
    upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    brand,
    partner
  FROM _Select_61
  UNION ALL
  SELECT
    upc,
    CAST(updated_order_qty AS VARCHAR) AS updated_order_qty,
    CAST(quantity_fulfilled_or_received AS BIGINT) AS quantity_fulfilled_or_received,
    CAST(brand AS VARCHAR) AS brand,
    CAST(NULL AS VARCHAR) AS partner
  FROM _Created_QTY_L60
), _Append_Rows_3 AS (
  SELECT
    upc,
    updated_order_qty,
    quantity_fulfilled_or_received,
    brand,
    partner
  FROM _Select_All_Time_1
  UNION ALL
  SELECT
    upc,
    CAST(updated_order_qty AS VARCHAR) AS updated_order_qty,
    CAST(quantity_fulfilled_or_received AS BIGINT) AS quantity_fulfilled_or_received,
    CAST(brand AS VARCHAR) AS brand,
    CAST(NULL AS VARCHAR) AS partner
  FROM _Created_QTY_L720
), _Group_120_Days AS (
  SELECT
    upc,
    SUM(l120_avg_fill_rate) AS l120_avg_fill_rate,
    MIN(brand) AS brand,
    SUM(total_qty_received) AS total_qty_received,
    SUM(total_qty_ordered) AS total_qty_ordered,
    MIN(partner) AS partner
  FROM _Append_Rows
  GROUP BY
    upc
), _Group_90_Days AS (
  SELECT
    upc,
    SUM(l90_avg_fill_rate) AS l90_avg_fill_rate,
    MIN(brand) AS brand,
    SUM(total_qty_received) AS total_qty_received,
    SUM(total_qty_ordered) AS total_qty_ordered,
    MIN(partner) AS partner
  FROM _Append_Rows_1
  GROUP BY
    upc
), _Group_60_Days AS (
  SELECT
    upc,
    SUM(l60_avg_fill_rate) AS l60_avg_fill_rate,
    MIN(brand) AS brand,
    SUM(total_qty_ordered) AS total_qty_ordered,
    SUM(total_qty_received) AS total_qty_received,
    MIN(partner) AS partner
  FROM _Append_Rows_2
  GROUP BY
    upc
), _Group_All_Time_2 AS (
  SELECT
    upc,
    SUM(all_time_avg_fill_rate) AS all_time_avg_fill_rate,
    MIN(brand) AS brand,
    SUM(total_qty_received) AS total_qty_received,
    SUM(total_qty_ordered) AS total_qty_ordered,
    MIN(partner) AS partner
  FROM _Append_Rows_3
  GROUP BY
    upc
), _UPC_Fill_Rate_120_Days_2 AS (
  SELECT
    *
  FROM _Group_120_Days
), _UPC_Fill_Rate_90_Days_2 AS (
  SELECT
    *
  FROM _Group_90_Days
), _UPC_Fill_Rate_60_Days_2 AS (
  SELECT
    *
  FROM _Group_60_Days
), _Join_All_time_and_120 AS (
  SELECT
    _Group_All_Time_2.upc,
    _Group_All_Time_2.all_time_avg_fill_rate,
    _Group_All_Time_2.brand,
    _Group_All_Time_2.total_qty_received,
    _Group_All_Time_2.total_qty_ordered,
    _Group_All_Time_2.partner,
    _Group_120_Days.l120_avg_fill_rate,
    _Group_120_Days.total_qty_received AS group_120_days_total_qty_received,
    _Group_120_Days.total_qty_ordered AS group_120_days_total_qty_ordered
  FROM _Group_All_Time_2
  LEFT JOIN _Group_120_Days
    ON _Group_All_Time_2.upc = _Group_120_Days.upc
    AND _Group_All_Time_2.brand = _Group_120_Days.brand
    AND _Group_All_Time_2.partner = _Group_120_Days.partner
), _UPC_Fill_Rate_All_Time_2 AS (
  SELECT
    *
  FROM _Group_All_Time_2
), _Join_All_120_90 AS (
  SELECT
    _Join_All_time_and_120.upc,
    _Join_All_time_and_120.all_time_avg_fill_rate,
    _Join_All_time_and_120.brand,
    _Join_All_time_and_120.total_qty_received,
    _Join_All_time_and_120.total_qty_ordered,
    _Join_All_time_and_120.partner,
    _Join_All_time_and_120.l120_avg_fill_rate,
    _Join_All_time_and_120.group_120_days_total_qty_received,
    _Join_All_time_and_120.group_120_days_total_qty_ordered,
    _Group_90_Days.l90_avg_fill_rate,
    _Group_90_Days.total_qty_received AS group_90_days_total_qty_received,
    _Group_90_Days.total_qty_ordered AS group_90_days_total_qty_ordered
  FROM _Join_All_time_and_120
  LEFT JOIN _Group_90_Days
    ON _Join_All_time_and_120.upc = _Group_90_Days.upc
    AND _Join_All_time_and_120.brand = _Group_90_Days.brand
    AND _Join_All_time_and_120.partner = _Group_90_Days.partner
), _Consolidate_All AS (
  SELECT
    _Join_All_120_90.upc,
    _Join_All_120_90.all_time_avg_fill_rate,
    _Join_All_120_90.brand,
    _Join_All_120_90.total_qty_received,
    _Join_All_120_90.total_qty_ordered,
    _Join_All_120_90.partner,
    _Join_All_120_90.l120_avg_fill_rate,
    _Join_All_120_90.group_120_days_total_qty_received,
    _Join_All_120_90.group_120_days_total_qty_ordered,
    _Join_All_120_90.l90_avg_fill_rate,
    _Join_All_120_90.group_90_days_total_qty_received,
    _Join_All_120_90.group_90_days_total_qty_ordered,
    _Group_60_Days.l60_avg_fill_rate,
    _Group_60_Days.total_qty_ordered AS group_60_days_total_qty_ordered,
    _Group_60_Days.total_qty_received AS group_60_days_total_qty_received
  FROM _Join_All_120_90
  LEFT JOIN _Group_60_Days
    ON _Join_All_120_90.upc = _Group_60_Days.upc
    AND _Join_All_120_90.brand = _Group_60_Days.brand
    AND _Join_All_120_90.partner = _Group_60_Days.partner
), _Fill_Rate_Aggregate AS (
  SELECT
    brand,
    upc,
    all_time_avg_fill_rate,
    total_qty_received AS all_time_qty_received,
    total_qty_ordered AS all_time_qty_ordered,
    l120_avg_fill_rate,
    group_120_days_total_qty_received AS l120_qty_received,
    group_120_days_total_qty_ordered AS l120_qty_ordered,
    l90_avg_fill_rate,
    group_90_days_total_qty_received AS l90_qty_received,
    group_90_days_total_qty_ordered AS l90_qty_ordered,
    l60_avg_fill_rate,
    group_60_days_total_qty_ordered AS l60_qty_received,
    group_60_days_total_qty_received AS l60_qty_ordered,
    partner
  FROM _Consolidate_All
), _Fill_Rate_Aggregate AS (
  SELECT
    *
  FROM _Fill_Rate_Aggregate
)
SELECT
  *
FROM _Fill_Rate_Aggregate