/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 183
Dataflow Name: Purchase Orders Details DF
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 86
  Successful: 86
  Failed: 0
  Unique Action Types: 10
  Action Types: ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, Metadata, PublishToVault, SelectValues, UnionAll, Unique
  Pipelines: 8

Generated: 2025-07-02 10:24:31
================================================================================
*/
WITH _purchase_orders AS (
  SELECT
    cancelled,
    carrier,
    created_at,
    deleted_at,
    estimated_arrival,
    fba_ship_from_id,
    id,
    inventory_vendor_id,
    is_partial_order,
    name,
    vendor,
    number,
    order_total,
    other_fees,
    po_bill_to_id,
    po_ship_to_id,
    shipping_total,
    shipping_total_3rd_party,
    status,
    status_changed_at,
    target_days_coverage,
    tax,
    total_lead_time,
    tracking_number,
    updated_at,
    vendor_invoice_date,
    vendor_invoice_number,
    status_name,
    first_po_date,
    amazon_seller_id,
    type_id,
    type,
    priority_id,
    priority,
    shipping_method_id,
    shipping_method,
    memo,
    is_msku_changeover,
    netsuite_id,
    batch_id,
    batch_last_run
  FROM purchase_orders
), _purchase_order_line_items AS (
  SELECT
    cost,
    created_at,
    created_by,
    daily_velocity,
    deleted_at,
    deleted_by,
    discount,
    fnsku,
    id,
    kit_qty,
    msku,
    purchase_order_id,
    reorder_qty_msku,
    reorder_qty_upc,
    total_inventory,
    upc,
    upc_name,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    batch_id,
    batch_last_run
  FROM purchase_order_line_items
), _inventory_vendors AS (
  SELECT
    deleted_at,
    fba_ship_from_id,
    id,
    local_inventory,
    name,
    non_accounting,
    po_bill_to_id,
    po_ship_to_id,
    target_days_coverage,
    total_lead_time,
    batch_id,
    batch_last_run
  FROM inventory_vendors
), _UPCs AS (
  SELECT
    brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    client_id,
    cost,
    created_at,
    created_by,
    default_cost,
    default_discount,
    deleted_at,
    deleted_by,
    id,
    hero,
    map,
    min_order_qty,
    name,
    old_upc,
    parent_upc,
    reorder_comments,
    reorder_status,
    srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upc,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    is_discontinued_status,
    amazon_seller_id,
    unit_count_type_id,
    unit_count,
    batch_id,
    batch_last_run
  FROM UPCs
), _clients AS (
  SELECT
    advertisement_document_url,
    advertisement_enabled,
    amazon_seller_id,
    avatar,
    created_at,
    created_by,
    deleted_at,
    deleted_by,
    description,
    estimated_annual_sales,
    export_view_enabled,
    id,
    insights_view_enabled,
    map_view_enabled,
    member_since,
    name,
    ss_invoicing_view_enabled,
    ss_subscriptions_view_enabled,
    updated_at,
    updated_by,
    website,
    batch_id,
    batch_last_run
  FROM clients
), _Brands AS (
  SELECT
    amazon_seller_id,
    baseline_date,
    client_id,
    created_at,
    created_by,
    currency,
    deleted_at,
    deleted_by,
    enabled_executive_report,
    enabled_projections,
    estimated_anual_sales,
    growth_target,
    id,
    legacy_brand_id,
    map_formula,
    name,
    start_date,
    updated_at,
    updated_by,
    batch_id,
    batch_last_run
  FROM Brands
), _Daily_Performance_DS AS (
  SELECT
    velocities_by_asin_upc,
    velocities_by_asin_upc_name,
    v_1,
    v_2,
    v_3,
    v_4,
    v_5,
    velocities_by_asin_date,
    velocities_by_asin_brand,
    sku,
    currency,
    enabled,
    id,
    country,
    sales_channel,
    short_name,
    asin,
    cost,
    fnsku,
    is_bundle,
    sku_name,
    reorder_status,
    join_data_1_sku,
    units_in_listing,
    upc,
    vendor_sku,
    upc_name,
    po_approved,
    po_created,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    qty_with_removals_in_progress,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    inventory_date,
    cogs,
    purchase_date,
    expanded_units,
    item_price,
    units,
    week_number,
    child_asin,
    total_order_items,
    total_order_items_b2b,
    page_views,
    sessions,
    active_subscriptions,
    snapshot_date,
    week_1_start_date,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    map_formula,
    brand,
    buy_box_percentage,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    regular_average_bbp,
    weighted_average_bbp,
    sc_ordered_product_sales,
    sc_ordered_product_sales_b2b,
    sc_units_ordered,
    sc_units_orderded_b2b,
    cvr_page_views,
    cvr_session_views,
    sc_date,
    year,
    upcs_w_categories_brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    upcs_w_categories_client_id,
    upcs_w_categories_cost,
    upcs_w_categories_created_at,
    upcs_w_categories_created_by,
    default_cost,
    default_discount,
    upcs_w_categories_deleted_at,
    upcs_w_categories_deleted_by,
    upcs_w_categories_id,
    map,
    min_order_qty,
    upcs_w_categories_name,
    old_upc,
    parent_upc,
    upcs_w_categories_reorder_status,
    sku_srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upcs_w_categories_updated_at,
    upcs_w_categories_updated_by,
    upcs_w_categories_vendor_sku,
    wholesale_price,
    upcs_w_categories_batch_id,
    upcs_w_categories_batch_last_run,
    avg_daily_active_subscriptions,
    asin_inventory,
    asin_sales_last28,
    asin_expanded_units_last28,
    brand_doh_min,
    brand_doh_max,
    brand_doh_avg,
    brand_doh_fulfillable_weighted_l28,
    brand_doh_fulfillable_weighted_l7,
    brand_doh_total_weighted_l28,
    brand_doh_total_weighted_l7,
    doh_fulfillable_weighted_l28,
    doh_fulfillable_weighted_l7,
    doh_total_weighted_l28,
    doh_total_weighted_l7,
    asin_title,
    asin_description,
    sales_sdly,
    units_sdly,
    expanded_units_sdly,
    idq_report_date,
    sales_country_id,
    product_id,
    max_daily_velocity,
    loreal_media_pillar_goals,
    loreal_media_categories,
    loreal_class_media,
    loreal_franchise,
    loreal_sub_franchise,
    loreal_division,
    loreal_axe_media,
    loreal_sub_axe_media,
    loreal_hero_cmo_mapping,
    amazon_asin_id,
    upc_id,
    srp,
    amazon_seller_id,
    account_name,
    parent_asin,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    pym,
    page_views_browser,
    page_views_mobile_app,
    sessions_browser,
    sessions_mobile_app,
    bullet_points_count,
    date,
    has_brand,
    has_bullet_points,
    has_description,
    has_emc_aplus,
    has_image,
    has_keywords,
    has_leaf_node,
    has_main_image_zoom,
    idq_grade,
    idq_score,
    is_search_indexed,
    marketplace_id,
    quarantined,
    review_avg_rating,
    review_ratings,
    title,
    total_images,
    row_count,
    advertised_rows,
    isadvertised,
    brand_id,
    client_id,
    old_product_id,
    ss_orders,
    ss_principal_amount,
    ss_promotion_amount,
    ss_units,
    sands_flag,
    month,
    stokke_week,
    purchaseyyymm,
    upc_date_match,
    asin_date_match,
    owned_page_views,
    relative_date,
    relative_month,
    units_per_upc_pack,
    brandid_01,
    brandid_02,
    pld_amazon_seller_id,
    original_brand_id,
    partner_-_brand,
    upc_components,
    fulfillment_channel,
    sku_cost,
    brand_created_at,
    brand_start_date,
    seller_start_date,
    seller_created_at,
    item_price_local,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    amazon_seller_id_combined,
    portfolio,
    revenue_flag,
    lfw_units,
    lfw_sessions,
    lfw_sales,
    lfw_date,
    pfw_units,
    pfw_sessions,
    pfw_sales,
    pfw_date,
    fwow_units,
    fwow_sales,
    fwow_sessions,
    lfw_bba,
    pfw_bba,
    fwow_bba,
    account_seller,
    parent_node,
    leaf_node_01,
    leaf_node_02,
    leaf_node_03,
    leaf_node_04,
    country_id,
    no_inventory,
    no_inv_n_rf_proc,
    l7_no_inventory,
    l28_no_inventory,
    l56_no_inventory,
    fba_fulfillable_doh,
    inbound_at_amazon_doh,
    inbound_in_transit_doh,
    rc_doh,
    on_order_doh,
    id_to_merge,
    asin_ad_spend,
    asin_transparency_status
  FROM Daily_Performance_DS
), _Product_List_DataSet AS (
  SELECT
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    deleted_at,
    fnsku,
    id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    batch_id,
    batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name
  FROM Product_List_DataSet
), _Alter_Columns_2 AS (
  SELECT
    CAST(created_at AS DATE),
    CAST(deleted_at AS DATE),
    CAST(estimated_arrival AS DATE),
    CAST(status_changed_at AS DATE),
    CAST(updated_at AS DATE),
    CAST(vendor_invoice_date AS DATE),
    CAST(first_po_date AS DATE),
    CAST(batch_last_run AS DATE),
    cancelled,
    carrier,
    fba_ship_from_id,
    id,
    inventory_vendor_id,
    is_partial_order,
    name,
    vendor,
    number,
    order_total,
    other_fees,
    po_bill_to_id,
    po_ship_to_id,
    shipping_total,
    shipping_total_3rd_party,
    status,
    target_days_coverage,
    tax,
    total_lead_time,
    tracking_number,
    vendor_invoice_number,
    status_name,
    amazon_seller_id,
    type_id,
    type,
    priority_id,
    priority,
    shipping_method_id,
    shipping_method,
    memo,
    is_msku_changeover,
    netsuite_id,
    batch_id
  FROM _purchase_orders
), _po_items AS (
  SELECT
    purchase_order_id,
    reorder_qty_upc,
    upc,
    msku
  FROM _purchase_order_line_items
), _UPCs_Clients AS (
  SELECT
    _UPCs.brand_id,
    _UPCs.cases_per_layer,
    _UPCs.cases_per_pallet,
    _UPCs.catalog_source,
    _UPCs.client_id,
    _UPCs.cost,
    _UPCs.created_at,
    _UPCs.created_by,
    _UPCs.default_cost,
    _UPCs.default_discount,
    _UPCs.deleted_at,
    _UPCs.deleted_by,
    _UPCs.id,
    _UPCs.hero,
    _UPCs.map,
    _UPCs.min_order_qty,
    _UPCs.name,
    _UPCs.old_upc,
    _UPCs.parent_upc,
    _UPCs.reorder_comments,
    _UPCs.reorder_status,
    _UPCs.srp,
    _UPCs.unit_lxwxh_inches,
    _UPCs.unit_weight_lb,
    _UPCs.units_per_case,
    _UPCs.upc,
    _UPCs.updated_at,
    _UPCs.updated_by,
    _UPCs.vendor_sku,
    _UPCs.wholesale_price,
    _UPCs.is_discontinued_status,
    _UPCs.amazon_seller_id,
    _UPCs.unit_count_type_id,
    _UPCs.unit_count,
    _UPCs.batch_id,
    _UPCs.batch_last_run,
    _clients.advertisement_document_url,
    _clients.advertisement_enabled,
    _clients.avatar,
    _clients.description,
    _clients.estimated_annual_sales,
    _clients.export_view_enabled,
    _clients.insights_view_enabled,
    _clients.map_view_enabled,
    _clients.member_since,
    _clients.name AS partner_name,
    _clients.ss_invoicing_view_enabled,
    _clients.ss_subscriptions_view_enabled,
    _clients.website
  FROM _UPCs
  INNER JOIN _clients
    ON _UPCs.client_id = _clients.id
), _Group_By_3 AS (
  SELECT
    partner_name,
    brand,
    AVG(item_price) AS sales,
    STDDEV(item_price) AS sales_std
  FROM _Daily_Performance_DS
  GROUP BY
    partner_name,
    brand
), _Add_Formula_4 AS (
  SELECT
    velocities_by_asin_upc,
    velocities_by_asin_upc_name,
    v_1,
    v_2,
    v_3,
    v_4,
    v_5,
    velocities_by_asin_date,
    velocities_by_asin_brand,
    sku,
    currency,
    enabled,
    id,
    country,
    sales_channel,
    short_name,
    asin,
    cost,
    fnsku,
    is_bundle,
    sku_name,
    reorder_status,
    join_data_1_sku,
    units_in_listing,
    upc,
    vendor_sku,
    upc_name,
    po_approved,
    po_created,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    qty_with_removals_in_progress,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    inventory_date,
    cogs,
    purchase_date,
    expanded_units,
    item_price,
    units,
    week_number,
    child_asin,
    total_order_items,
    total_order_items_b2b,
    page_views,
    sessions,
    active_subscriptions,
    snapshot_date,
    week_1_start_date,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    map_formula,
    brand,
    buy_box_percentage,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    regular_average_bbp,
    weighted_average_bbp,
    sc_ordered_product_sales,
    sc_ordered_product_sales_b2b,
    sc_units_ordered,
    sc_units_orderded_b2b,
    cvr_page_views,
    cvr_session_views,
    sc_date,
    year,
    upcs_w_categories_brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    upcs_w_categories_client_id,
    upcs_w_categories_cost,
    upcs_w_categories_created_at,
    upcs_w_categories_created_by,
    default_cost,
    default_discount,
    upcs_w_categories_deleted_at,
    upcs_w_categories_deleted_by,
    upcs_w_categories_id,
    map,
    min_order_qty,
    upcs_w_categories_name,
    old_upc,
    parent_upc,
    upcs_w_categories_reorder_status,
    sku_srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upcs_w_categories_updated_at,
    upcs_w_categories_updated_by,
    upcs_w_categories_vendor_sku,
    wholesale_price,
    upcs_w_categories_batch_id,
    upcs_w_categories_batch_last_run,
    avg_daily_active_subscriptions,
    asin_inventory,
    asin_sales_last28,
    asin_expanded_units_last28,
    brand_doh_min,
    brand_doh_max,
    brand_doh_avg,
    brand_doh_fulfillable_weighted_l28,
    brand_doh_fulfillable_weighted_l7,
    brand_doh_total_weighted_l28,
    brand_doh_total_weighted_l7,
    doh_fulfillable_weighted_l28,
    doh_fulfillable_weighted_l7,
    doh_total_weighted_l28,
    doh_total_weighted_l7,
    asin_title,
    asin_description,
    sales_sdly,
    units_sdly,
    expanded_units_sdly,
    idq_report_date,
    sales_country_id,
    product_id,
    max_daily_velocity,
    loreal_media_pillar_goals,
    loreal_media_categories,
    loreal_class_media,
    loreal_franchise,
    loreal_sub_franchise,
    loreal_division,
    loreal_axe_media,
    loreal_sub_axe_media,
    loreal_hero_cmo_mapping,
    amazon_asin_id,
    upc_id,
    srp,
    amazon_seller_id,
    account_name,
    parent_asin,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    pym,
    page_views_browser,
    page_views_mobile_app,
    sessions_browser,
    sessions_mobile_app,
    bullet_points_count,
    date,
    has_brand,
    has_bullet_points,
    has_description,
    has_emc_aplus,
    has_image,
    has_keywords,
    has_leaf_node,
    has_main_image_zoom,
    idq_grade,
    idq_score,
    is_search_indexed,
    marketplace_id,
    quarantined,
    review_avg_rating,
    review_ratings,
    title,
    total_images,
    row_count,
    advertised_rows,
    isadvertised,
    brand_id,
    client_id,
    old_product_id,
    ss_orders,
    ss_principal_amount,
    ss_promotion_amount,
    ss_units,
    sands_flag,
    month,
    stokke_week,
    purchaseyyymm,
    upc_date_match,
    asin_date_match,
    owned_page_views,
    relative_date,
    relative_month,
    units_per_upc_pack,
    brandid_01,
    brandid_02,
    pld_amazon_seller_id,
    original_brand_id,
    partner_-_brand,
    upc_components,
    fulfillment_channel,
    sku_cost,
    brand_created_at,
    brand_start_date,
    seller_start_date,
    seller_created_at,
    item_price_local,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    amazon_seller_id_combined,
    portfolio,
    revenue_flag,
    lfw_units,
    lfw_sessions,
    lfw_sales,
    lfw_date,
    pfw_units,
    pfw_sessions,
    pfw_sales,
    pfw_date,
    fwow_units,
    fwow_sales,
    fwow_sessions,
    lfw_bba,
    pfw_bba,
    fwow_bba,
    account_seller,
    parent_node,
    leaf_node_01,
    leaf_node_02,
    leaf_node_03,
    leaf_node_04,
    country_id,
    no_inventory,
    no_inv_n_rf_proc,
    l7_no_inventory,
    l28_no_inventory,
    l56_no_inventory,
    fba_fulfillable_doh,
    inbound_at_amazon_doh,
    inbound_in_transit_doh,
    rc_doh,
    on_order_doh,
    id_to_merge,
    asin_ad_spend,
    asin_transparency_status,
    (
      TO_CHAR(purchase_date, 'mmmm-yyyy')
    ) AS month-year
  FROM _Daily_Performance_DS
), _PO_Vendor AS (
  SELECT
    _Alter_Columns_2.cancelled,
    _Alter_Columns_2.carrier,
    _Alter_Columns_2.created_at,
    _Alter_Columns_2.deleted_at,
    _Alter_Columns_2.estimated_arrival,
    _Alter_Columns_2.fba_ship_from_id,
    _Alter_Columns_2.id,
    _Alter_Columns_2.inventory_vendor_id,
    _Alter_Columns_2.is_partial_order,
    _Alter_Columns_2.name,
    _Alter_Columns_2.vendor,
    _Alter_Columns_2.number,
    _Alter_Columns_2.order_total,
    _Alter_Columns_2.other_fees,
    _Alter_Columns_2.po_bill_to_id,
    _Alter_Columns_2.po_ship_to_id,
    _Alter_Columns_2.shipping_total,
    _Alter_Columns_2.shipping_total_3rd_party,
    _Alter_Columns_2.status,
    _Alter_Columns_2.status_changed_at,
    _Alter_Columns_2.target_days_coverage,
    _Alter_Columns_2.tax,
    _Alter_Columns_2.total_lead_time,
    _Alter_Columns_2.tracking_number,
    _Alter_Columns_2.updated_at,
    _Alter_Columns_2.vendor_invoice_date,
    _Alter_Columns_2.vendor_invoice_number,
    _Alter_Columns_2.status_name,
    _Alter_Columns_2.first_po_date,
    _Alter_Columns_2.amazon_seller_id,
    _Alter_Columns_2.type_id,
    _Alter_Columns_2.type,
    _Alter_Columns_2.priority_id,
    _Alter_Columns_2.priority,
    _Alter_Columns_2.shipping_method_id,
    _Alter_Columns_2.shipping_method,
    _Alter_Columns_2.memo,
    _Alter_Columns_2.is_msku_changeover,
    _Alter_Columns_2.netsuite_id,
    _Alter_Columns_2.batch_id,
    _Alter_Columns_2.batch_last_run,
    _inventory_vendors.local_inventory,
    _inventory_vendors.name AS vendor_name,
    _inventory_vendors.non_accounting
  FROM _Alter_Columns_2
  INNER JOIN _inventory_vendors
    ON _Alter_Columns_2.inventory_vendor_id = _inventory_vendors.id
), _UPCs_Brands AS (
  SELECT
    _UPCs_Clients.brand_id,
    _UPCs_Clients.cases_per_layer,
    _UPCs_Clients.cases_per_pallet,
    _UPCs_Clients.catalog_source,
    _UPCs_Clients.client_id,
    _UPCs_Clients.cost,
    _UPCs_Clients.created_at,
    _UPCs_Clients.created_by,
    _UPCs_Clients.default_cost,
    _UPCs_Clients.default_discount,
    _UPCs_Clients.deleted_at,
    _UPCs_Clients.deleted_by,
    _UPCs_Clients.id,
    _UPCs_Clients.hero,
    _UPCs_Clients.map,
    _UPCs_Clients.min_order_qty,
    _UPCs_Clients.name,
    _UPCs_Clients.old_upc,
    _UPCs_Clients.parent_upc,
    _UPCs_Clients.reorder_comments,
    _UPCs_Clients.reorder_status,
    _UPCs_Clients.srp,
    _UPCs_Clients.unit_lxwxh_inches,
    _UPCs_Clients.unit_weight_lb,
    _UPCs_Clients.units_per_case,
    _UPCs_Clients.upc,
    _UPCs_Clients.updated_at,
    _UPCs_Clients.updated_by,
    _UPCs_Clients.vendor_sku,
    _UPCs_Clients.wholesale_price,
    _UPCs_Clients.is_discontinued_status,
    _UPCs_Clients.amazon_seller_id,
    _UPCs_Clients.unit_count_type_id,
    _UPCs_Clients.unit_count,
    _UPCs_Clients.batch_id,
    _UPCs_Clients.batch_last_run,
    _UPCs_Clients.advertisement_document_url,
    _UPCs_Clients.advertisement_enabled,
    _UPCs_Clients.avatar,
    _UPCs_Clients.description,
    _UPCs_Clients.estimated_annual_sales,
    _UPCs_Clients.export_view_enabled,
    _UPCs_Clients.insights_view_enabled,
    _UPCs_Clients.map_view_enabled,
    _UPCs_Clients.member_since,
    _UPCs_Clients.partner_name,
    _UPCs_Clients.ss_invoicing_view_enabled,
    _UPCs_Clients.ss_subscriptions_view_enabled,
    _UPCs_Clients.website,
    _Brands.baseline_date,
    _Brands.currency,
    _Brands.enabled_executive_report,
    _Brands.enabled_projections,
    _Brands.estimated_anual_sales,
    _Brands.growth_target,
    _Brands.legacy_brand_id,
    _Brands.map_formula,
    _Brands.name AS brand,
    _Brands.start_date
  FROM _UPCs_Clients
  INNER JOIN _Brands
    ON _UPCs_Clients.brand_id = _Brands.id
), _Group_By_5 AS (
  SELECT
    brand,
    month-year,
    SUM(item_price) AS item_price
  FROM _Add_Formula_4
  GROUP BY
    brand,
    month-year
), _Group_by_PO_Vendor_And_Status AS (
  SELECT
    number,
    inventory_vendor_id,
    status,
    COUNT(status) AS count,
    MAX(cancelled) AS last_cancelled
  FROM _PO_Vendor
  GROUP BY
    number,
    inventory_vendor_id,
    status
), _upcs_fields AS (
  SELECT
    amazon_seller_id,
    upc,
    partner_name,
    brand,
    name AS upc_name,
    cost,
    wholesale_price,
    map,
    srp
  FROM _UPCs_Brands
), _PO_with_repeated_status AS (
  SELECT
    *
  FROM _Group_by_PO_Vendor_And_Status
  WHERE
    count > '1'
), _PO_PO_Repeated AS (
  SELECT
    _PO_Vendor.deleted_at,
    _PO_Vendor.fba_ship_from_id,
    _PO_Vendor.id,
    _PO_Vendor.local_inventory,
    _PO_Vendor.name,
    _PO_Vendor.non_accounting,
    _PO_Vendor.po_bill_to_id,
    _PO_Vendor.po_ship_to_id,
    _PO_Vendor.target_days_coverage,
    _PO_Vendor.total_lead_time,
    _PO_Vendor.batch_id,
    _PO_Vendor.batch_last_run,
    _PO_Vendor.cancelled,
    _PO_Vendor.carrier,
    _PO_Vendor.created_at,
    _PO_Vendor.estimated_arrival,
    _PO_Vendor.inventory_vendor_id,
    _PO_Vendor.is_partial_order,
    _PO_Vendor.vendor_name,
    _PO_Vendor.vendor,
    _PO_Vendor.number,
    _PO_Vendor.order_total,
    _PO_Vendor.other_fees,
    _PO_Vendor.shipping_total,
    _PO_Vendor.shipping_total_3rd_party,
    _PO_Vendor.status,
    _PO_Vendor.status_changed_at,
    _PO_Vendor.tax,
    _PO_Vendor.tracking_number,
    _PO_Vendor.updated_at,
    _PO_Vendor.vendor_invoice_date,
    _PO_Vendor.vendor_invoice_number,
    _PO_Vendor.status_name,
    _PO_Vendor.first_po_date,
    _PO_Vendor.amazon_seller_id,
    _PO_Vendor.type_id,
    _PO_Vendor.type,
    _PO_Vendor.priority_id,
    _PO_Vendor.priority,
    _PO_Vendor.shipping_method_id,
    _PO_Vendor.shipping_method,
    _PO_Vendor.memo,
    _PO_Vendor.is_msku_changeover,
    _PO_Vendor.netsuite_id,
    _PO_with_repeated_status.count,
    _PO_with_repeated_status.last_cancelled
  FROM _PO_Vendor
  INNER JOIN _PO_with_repeated_status
    ON _PO_Vendor.number = _PO_with_repeated_status.number
    AND _PO_Vendor.inventory_vendor_id = _PO_with_repeated_status.inventory_vendor_id
    AND _PO_Vendor.status = _PO_with_repeated_status.status
), _PO_and_PO_with_Repeated_status AS (
  SELECT
    _PO_Vendor.deleted_at,
    _PO_Vendor.fba_ship_from_id,
    _PO_Vendor.id,
    _PO_Vendor.local_inventory,
    _PO_Vendor.name,
    _PO_Vendor.non_accounting,
    _PO_Vendor.po_bill_to_id,
    _PO_Vendor.po_ship_to_id,
    _PO_Vendor.target_days_coverage,
    _PO_Vendor.total_lead_time,
    _PO_Vendor.batch_id,
    _PO_Vendor.batch_last_run,
    _PO_Vendor.cancelled,
    _PO_Vendor.carrier,
    _PO_Vendor.created_at,
    _PO_Vendor.estimated_arrival,
    _PO_Vendor.inventory_vendor_id,
    _PO_Vendor.is_partial_order,
    _PO_Vendor.vendor_name,
    _PO_Vendor.vendor,
    _PO_Vendor.number,
    _PO_Vendor.order_total,
    _PO_Vendor.other_fees,
    _PO_Vendor.shipping_total,
    _PO_Vendor.shipping_total_3rd_party,
    _PO_Vendor.status,
    _PO_Vendor.status_changed_at,
    _PO_Vendor.tax,
    _PO_Vendor.tracking_number,
    _PO_Vendor.updated_at,
    _PO_Vendor.vendor_invoice_date,
    _PO_Vendor.vendor_invoice_number,
    _PO_Vendor.status_name,
    _PO_Vendor.first_po_date,
    _PO_Vendor.amazon_seller_id,
    _PO_Vendor.type_id,
    _PO_Vendor.type,
    _PO_Vendor.priority_id,
    _PO_Vendor.priority,
    _PO_Vendor.shipping_method_id,
    _PO_Vendor.shipping_method,
    _PO_Vendor.memo,
    _PO_Vendor.is_msku_changeover,
    _PO_Vendor.netsuite_id,
    _PO_with_repeated_status.number AS null_number,
    _PO_with_repeated_status.count,
    _PO_with_repeated_status.last_cancelled
  FROM _PO_Vendor
  LEFT JOIN _PO_with_repeated_status
    ON _PO_Vendor.inventory_vendor_id = _PO_with_repeated_status.inventory_vendor_id
    AND _PO_Vendor.number = _PO_with_repeated_status.number
    AND _PO_Vendor.status = _PO_with_repeated_status.status
), _PO_no_cancelled AS (
  SELECT
    *
  FROM _PO_PO_Repeated
  WHERE
    cancelled = '0'
), _Ignore_duplicated_records AS (
  SELECT
    *
  FROM _PO_and_PO_with_Repeated_status
  WHERE
    null_number IS NULL
), _Append_Rows AS (
  SELECT
    number,
    inventory_vendor_id,
    status,
    count,
    last_cancelled,
    deleted_at,
    fba_ship_from_id,
    id,
    local_inventory,
    name,
    non_accounting,
    po_bill_to_id,
    po_ship_to_id,
    target_days_coverage,
    total_lead_time,
    batch_id,
    batch_last_run,
    cancelled,
    carrier,
    created_at,
    estimated_arrival,
    is_partial_order,
    vendor_name,
    vendor,
    order_total,
    other_fees,
    shipping_total,
    shipping_total_3rd_party,
    status_changed_at,
    tax,
    tracking_number,
    updated_at,
    vendor_invoice_date,
    vendor_invoice_number,
    status_name,
    first_po_date,
    amazon_seller_id,
    type_id,
    type,
    priority_id,
    priority,
    shipping_method_id,
    shipping_method,
    memo,
    is_msku_changeover,
    netsuite_id
  FROM _PO_no_cancelled
  UNION ALL
  SELECT
    number,
    inventory_vendor_id,
    status,
    count,
    last_cancelled,
    deleted_at,
    fba_ship_from_id,
    id,
    local_inventory,
    name,
    non_accounting,
    po_bill_to_id,
    po_ship_to_id,
    target_days_coverage,
    total_lead_time,
    batch_id,
    batch_last_run,
    cancelled,
    carrier,
    created_at,
    estimated_arrival,
    is_partial_order,
    vendor_name,
    vendor,
    order_total,
    other_fees,
    shipping_total,
    shipping_total_3rd_party,
    status_changed_at,
    tax,
    tracking_number,
    updated_at,
    vendor_invoice_date,
    vendor_invoice_number,
    status_name,
    first_po_date,
    amazon_seller_id,
    type_id,
    type,
    priority_id,
    priority,
    shipping_method_id,
    shipping_method,
    memo,
    is_msku_changeover,
    netsuite_id
  FROM _Ignore_duplicated_records
), _Purchase_Number AS (
  SELECT
    number,
    id AS purchase_order_id,
    status_name,
    amazon_seller_id,
    status,
    created_at AS status_at,
    order_total,
    cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    inventory_vendor_id,
    type,
    priority,
    shipping_method,
    memo
  FROM _Append_Rows
), _PO_Shipped AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '6'
), _PO_Processed AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '5'
), _PO_Received AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '4'
), _PO_Invoiced AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '3'
), _PO_Approved AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '2'
), _PO_created AS (
  SELECT
    *
  FROM _Purchase_Number
  WHERE
    status = '1'
), _set_created_status AS (
  SELECT
    status_at AS created,
    purchase_order_id AS created_po_id,
    cancelled AS created_cancelled,
    type AS created_type,
    priority AS created_priority,
    shipping_method AS created_shipping_method,
    memo AS created_memo,
    number,
    status_name,
    amazon_seller_id,
    status,
    order_total,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    inventory_vendor_id
  FROM _PO_created
), _po_Created_Approved AS (
  SELECT
    _set_created_status.number,
    _set_created_status.purchase_order_id,
    _set_created_status.status_name,
    _set_created_status.amazon_seller_id,
    _set_created_status.status,
    _set_created_status.status_at,
    _set_created_status.order_total,
    _set_created_status.cancelled,
    _set_created_status.vendor_invoice_date,
    _set_created_status.vendor_invoice_number,
    _set_created_status.vendor_name,
    _set_created_status.inventory_vendor_id,
    _set_created_status.type,
    _set_created_status.priority,
    _set_created_status.shipping_method,
    _set_created_status.memo,
    _PO_Approved.purchase_order_id AS approved_po_id,
    _PO_Approved.status_name AS approved_status_name,
    _PO_Approved.status_at AS approved,
    _PO_Approved.cancelled AS approved_cancelled,
    _PO_Approved.type AS approved_type,
    _PO_Approved.priority AS approved_priority,
    _PO_Approved.shipping_method AS approved_shipping_method,
    _PO_Approved.memo AS approved_memo
  FROM _set_created_status
  LEFT JOIN _PO_Approved
    ON _set_created_status.number = _PO_Approved.number
    AND _set_created_status.vendor_name = _PO_Approved.vendor_name
), _po_invoiced_join AS (
  SELECT
    _po_Created_Approved.number,
    _po_Created_Approved.purchase_order_id,
    _po_Created_Approved.status_name,
    _po_Created_Approved.amazon_seller_id,
    _po_Created_Approved.status,
    _po_Created_Approved.status_at,
    _po_Created_Approved.order_total,
    _po_Created_Approved.cancelled,
    _po_Created_Approved.vendor_invoice_date,
    _po_Created_Approved.vendor_invoice_number,
    _po_Created_Approved.vendor_name,
    _po_Created_Approved.inventory_vendor_id,
    _po_Created_Approved.type,
    _po_Created_Approved.priority,
    _po_Created_Approved.shipping_method,
    _po_Created_Approved.memo,
    _po_Created_Approved.approved_po_id,
    _po_Created_Approved.approved_status_name,
    _po_Created_Approved.approved,
    _po_Created_Approved.approved_cancelled,
    _po_Created_Approved.approved_type,
    _po_Created_Approved.approved_priority,
    _po_Created_Approved.approved_shipping_method,
    _po_Created_Approved.approved_memo,
    _PO_Invoiced.purchase_order_id AS invoiced_po_id,
    _PO_Invoiced.status_name AS invoiced_status_name,
    _PO_Invoiced.status_at AS invoiced,
    _PO_Invoiced.order_total AS invoiced_invoice_total,
    _PO_Invoiced.cancelled AS invoiced_cancelled,
    _PO_Invoiced.vendor_invoice_date AS invoiced_vendor_invoice_date,
    _PO_Invoiced.vendor_invoice_number AS invoiced_vendor_invoice_number,
    _PO_Invoiced.type AS invoiced_type,
    _PO_Invoiced.priority AS invoiced_priority,
    _PO_Invoiced.shipping_method AS invoiced_shipping_method,
    _PO_Invoiced.memo AS invoiced_memo
  FROM _po_Created_Approved
  LEFT JOIN _PO_Invoiced
    ON _po_Created_Approved.number = _PO_Invoiced.number
    AND _po_Created_Approved.vendor_name = _PO_Invoiced.vendor_name
), _po_received_join AS (
  SELECT
    _po_invoiced_join.number,
    _po_invoiced_join.purchase_order_id,
    _po_invoiced_join.status_name,
    _po_invoiced_join.amazon_seller_id,
    _po_invoiced_join.status,
    _po_invoiced_join.status_at,
    _po_invoiced_join.order_total,
    _po_invoiced_join.cancelled,
    _po_invoiced_join.vendor_invoice_date,
    _po_invoiced_join.vendor_invoice_number,
    _po_invoiced_join.vendor_name,
    _po_invoiced_join.inventory_vendor_id,
    _po_invoiced_join.type,
    _po_invoiced_join.priority,
    _po_invoiced_join.shipping_method,
    _po_invoiced_join.memo,
    _po_invoiced_join.invoiced_po_id,
    _po_invoiced_join.invoiced_status_name,
    _po_invoiced_join.invoiced,
    _po_invoiced_join.invoiced_invoice_total,
    _po_invoiced_join.invoiced_cancelled,
    _po_invoiced_join.invoiced_vendor_invoice_date,
    _po_invoiced_join.invoiced_vendor_invoice_number,
    _po_invoiced_join.invoiced_type,
    _po_invoiced_join.invoiced_priority,
    _po_invoiced_join.invoiced_shipping_method,
    _po_invoiced_join.invoiced_memo,
    _po_invoiced_join.approved_po_id,
    _po_invoiced_join.approved_status_name,
    _po_invoiced_join.approved,
    _po_invoiced_join.approved_cancelled,
    _po_invoiced_join.approved_type,
    _po_invoiced_join.approved_priority,
    _po_invoiced_join.approved_shipping_method,
    _po_invoiced_join.approved_memo,
    _PO_Received.purchase_order_id AS received_po_id,
    _PO_Received.status_name AS received_status_name,
    _PO_Received.status_at AS received,
    _PO_Received.cancelled AS received_cancelled,
    _PO_Received.type AS received_type,
    _PO_Received.priority AS received_priority,
    _PO_Received.shipping_method AS received_shipping_method,
    _PO_Received.memo AS received_memo
  FROM _po_invoiced_join
  LEFT JOIN _PO_Received
    ON _po_invoiced_join.number = _PO_Received.number
    AND _po_invoiced_join.vendor_name = _PO_Received.vendor_name
), _po_processed_join AS (
  SELECT
    _po_received_join.number,
    _po_received_join.purchase_order_id,
    _po_received_join.status_name,
    _po_received_join.amazon_seller_id,
    _po_received_join.status,
    _po_received_join.status_at,
    _po_received_join.order_total,
    _po_received_join.cancelled,
    _po_received_join.vendor_invoice_date,
    _po_received_join.vendor_invoice_number,
    _po_received_join.vendor_name,
    _po_received_join.inventory_vendor_id,
    _po_received_join.type,
    _po_received_join.priority,
    _po_received_join.shipping_method,
    _po_received_join.memo,
    _po_received_join.received_po_id,
    _po_received_join.received_status_name,
    _po_received_join.received,
    _po_received_join.received_cancelled,
    _po_received_join.received_type,
    _po_received_join.received_priority,
    _po_received_join.received_shipping_method,
    _po_received_join.received_memo,
    _po_received_join.invoiced_po_id,
    _po_received_join.invoiced_status_name,
    _po_received_join.invoiced,
    _po_received_join.invoiced_invoice_total,
    _po_received_join.invoiced_cancelled,
    _po_received_join.invoiced_vendor_invoice_date,
    _po_received_join.invoiced_vendor_invoice_number,
    _po_received_join.invoiced_type,
    _po_received_join.invoiced_priority,
    _po_received_join.invoiced_shipping_method,
    _po_received_join.invoiced_memo,
    _po_received_join.approved_po_id,
    _po_received_join.approved_status_name,
    _po_received_join.approved,
    _po_received_join.approved_cancelled,
    _po_received_join.approved_type,
    _po_received_join.approved_priority,
    _po_received_join.approved_shipping_method,
    _po_received_join.approved_memo,
    _PO_Processed.purchase_order_id AS processed_po_id,
    _PO_Processed.status_name AS processed_status_name,
    _PO_Processed.status_at AS processed,
    _PO_Processed.cancelled AS processed_cancelled,
    _PO_Processed.type AS processed_type,
    _PO_Processed.priority AS processed_priority,
    _PO_Processed.shipping_method AS processed_shipping_method,
    _PO_Processed.memo AS processed_memo
  FROM _po_received_join
  LEFT JOIN _PO_Processed
    ON _po_received_join.number = _PO_Processed.number
    AND _po_received_join.vendor_name = _PO_Processed.vendor_name
), _po_shipped_join AS (
  SELECT
    _po_processed_join.number,
    _po_processed_join.purchase_order_id,
    _po_processed_join.status_name,
    _po_processed_join.amazon_seller_id,
    _po_processed_join.status,
    _po_processed_join.status_at,
    _po_processed_join.order_total,
    _po_processed_join.cancelled,
    _po_processed_join.vendor_invoice_date,
    _po_processed_join.vendor_invoice_number,
    _po_processed_join.vendor_name,
    _po_processed_join.inventory_vendor_id,
    _po_processed_join.type,
    _po_processed_join.priority,
    _po_processed_join.shipping_method,
    _po_processed_join.memo,
    _po_processed_join.processed_po_id,
    _po_processed_join.processed_status_name,
    _po_processed_join.processed,
    _po_processed_join.processed_cancelled,
    _po_processed_join.processed_type,
    _po_processed_join.processed_priority,
    _po_processed_join.processed_shipping_method,
    _po_processed_join.processed_memo,
    _po_processed_join.received_po_id,
    _po_processed_join.received_status_name,
    _po_processed_join.received,
    _po_processed_join.received_cancelled,
    _po_processed_join.received_type,
    _po_processed_join.received_priority,
    _po_processed_join.received_shipping_method,
    _po_processed_join.received_memo,
    _po_processed_join.invoiced_po_id,
    _po_processed_join.invoiced_status_name,
    _po_processed_join.invoiced,
    _po_processed_join.invoiced_invoice_total,
    _po_processed_join.invoiced_cancelled,
    _po_processed_join.invoiced_vendor_invoice_date,
    _po_processed_join.invoiced_vendor_invoice_number,
    _po_processed_join.invoiced_type,
    _po_processed_join.invoiced_priority,
    _po_processed_join.invoiced_shipping_method,
    _po_processed_join.invoiced_memo,
    _po_processed_join.approved_po_id,
    _po_processed_join.approved_status_name,
    _po_processed_join.approved,
    _po_processed_join.approved_cancelled,
    _po_processed_join.approved_type,
    _po_processed_join.approved_priority,
    _po_processed_join.approved_shipping_method,
    _po_processed_join.approved_memo,
    _PO_Shipped.purchase_order_id AS shipped_po_id,
    _PO_Shipped.status_name AS shipped_status_name,
    _PO_Shipped.status_at AS shipped,
    _PO_Shipped.cancelled AS shipped_cancelled,
    _PO_Shipped.type AS shipped_type,
    _PO_Shipped.priority AS shipped_priority,
    _PO_Shipped.shipping_method AS shipped_shipping_method,
    _PO_Shipped.memo AS shipped_memo
  FROM _po_processed_join
  LEFT JOIN _PO_Shipped
    ON _po_processed_join.number = _PO_Shipped.number
    AND _po_processed_join.vendor_name = _PO_Shipped.vendor_name
), _set_current_status AS (
  SELECT
    number,
    purchase_order_id,
    status_name,
    amazon_seller_id,
    status,
    status_at,
    order_total,
    cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    inventory_vendor_id,
    shipped_po_id,
    shipped_status_name,
    shipped,
    shipped_cancelled,
    shipped_type,
    shipped_priority,
    shipped_shipping_method,
    shipped_memo,
    processed_po_id,
    processed_status_name,
    processed,
    processed_cancelled,
    processed_type,
    processed_priority,
    processed_shipping_method,
    processed_memo,
    received_po_id,
    received_status_name,
    received,
    received_cancelled,
    received_type,
    received_priority,
    received_shipping_method,
    received_memo,
    invoiced_po_id,
    invoiced_status_name,
    invoiced,
    invoiced_invoice_total,
    invoiced_cancelled,
    invoiced_vendor_invoice_date,
    invoiced_vendor_invoice_number,
    invoiced_type,
    invoiced_priority,
    invoiced_shipping_method,
    invoiced_memo,
    approved_po_id,
    approved_status_name,
    approved,
    approved_cancelled,
    approved_type,
    approved_priority,
    approved_shipping_method,
    approved_memo,
    (
      COALESCE(
        shipped_status_name,
        COALESCE(
          processed_status_name,
          COALESCE(
            received_status_name,
            COALESCE(invoiced_status_name, COALESCE(approved_status_name, status_name))
          )
        )
      )
    ) AS current_status,
    (
      COALESCE(
        shipped_cancelled,
        COALESCE(
          processed_cancelled,
          COALESCE(
            received_cancelled,
            COALESCE(invoiced_cancelled, COALESCE(approved_cancelled, created_cancelled))
          )
        )
      )
    ) AS po_cancelled,
    (
      COALESCE(
        shipped_type,
        COALESCE(
          processed_type,
          COALESCE(
            received_type,
            COALESCE(invoiced_type, COALESCE(approved_type, created_type))
          )
        )
      )
    ) AS type,
    (
      COALESCE(
        shipped_priority,
        COALESCE(
          processed_priority,
          COALESCE(
            received_priority,
            COALESCE(invoiced_priority, COALESCE(approved_priority, created_priority))
          )
        )
      )
    ) AS priority,
    (
      COALESCE(
        shipped_shipping_method,
        COALESCE(
          processed_shipping_method,
          COALESCE(
            received_shipping_method,
            COALESCE(
              invoiced_shipping_method,
              COALESCE(approved_shipping_method, created_shipping_method)
            )
          )
        )
      )
    ) AS shipping_method,
    (
      COALESCE(
        shipped_memo,
        COALESCE(
          processed_memo,
          COALESCE(
            received_memo,
            COALESCE(invoiced_memo, COALESCE(approved_memo, created_memo))
          )
        )
      )
    ) AS memo
  FROM _po_shipped_join
), _created_join AS (
  SELECT
    _set_current_status.number,
    _set_current_status.purchase_order_id,
    _set_current_status.status_name,
    _set_current_status.amazon_seller_id,
    _set_current_status.status,
    _set_current_status.status_at,
    _set_current_status.order_total,
    _set_current_status.cancelled,
    _set_current_status.vendor_invoice_date,
    _set_current_status.vendor_invoice_number,
    _set_current_status.vendor_name,
    _set_current_status.inventory_vendor_id,
    _set_current_status.type,
    _set_current_status.priority,
    _set_current_status.shipping_method,
    _set_current_status.memo,
    _set_current_status.shipped_po_id,
    _set_current_status.shipped_status_name,
    _set_current_status.shipped,
    _set_current_status.shipped_cancelled,
    _set_current_status.shipped_type,
    _set_current_status.shipped_priority,
    _set_current_status.shipped_shipping_method,
    _set_current_status.shipped_memo,
    _set_current_status.processed_po_id,
    _set_current_status.processed_status_name,
    _set_current_status.processed,
    _set_current_status.processed_cancelled,
    _set_current_status.processed_type,
    _set_current_status.processed_priority,
    _set_current_status.processed_shipping_method,
    _set_current_status.processed_memo,
    _set_current_status.received_po_id,
    _set_current_status.received_status_name,
    _set_current_status.received,
    _set_current_status.received_cancelled,
    _set_current_status.received_type,
    _set_current_status.received_priority,
    _set_current_status.received_shipping_method,
    _set_current_status.received_memo,
    _set_current_status.invoiced_po_id,
    _set_current_status.invoiced_status_name,
    _set_current_status.invoiced,
    _set_current_status.invoiced_invoice_total,
    _set_current_status.invoiced_cancelled,
    _set_current_status.invoiced_vendor_invoice_date,
    _set_current_status.invoiced_vendor_invoice_number,
    _set_current_status.invoiced_type,
    _set_current_status.invoiced_priority,
    _set_current_status.invoiced_shipping_method,
    _set_current_status.invoiced_memo,
    _set_current_status.approved_po_id,
    _set_current_status.approved_status_name,
    _set_current_status.approved,
    _set_current_status.approved_cancelled,
    _set_current_status.approved_type,
    _set_current_status.approved_priority,
    _set_current_status.approved_shipping_method,
    _set_current_status.approved_memo,
    _set_current_status.current_status,
    _set_current_status.po_cancelled,
    _po_items.purchase_order_id,
    _po_items.reorder_qty_upc AS created_qty,
    _po_items.upc,
    _po_items.msku
  FROM _set_current_status
  LEFT JOIN _po_items
    ON _set_current_status.created_po_id = _po_items.purchase_order_id
), _approved_join AS (
  SELECT
    _created_join.purchase_order_id,
    _created_join.reorder_qty_upc,
    _created_join.upc,
    _created_join.msku,
    _created_join.number,
    _created_join.status_name,
    _created_join.amazon_seller_id,
    _created_join.status,
    _created_join.status_at,
    _created_join.order_total,
    _created_join.cancelled,
    _created_join.vendor_invoice_date,
    _created_join.vendor_invoice_number,
    _created_join.vendor_name,
    _created_join.inventory_vendor_id,
    _created_join.type,
    _created_join.priority,
    _created_join.shipping_method,
    _created_join.memo,
    _created_join.shipped_po_id,
    _created_join.shipped_status_name,
    _created_join.shipped,
    _created_join.shipped_cancelled,
    _created_join.shipped_type,
    _created_join.shipped_priority,
    _created_join.shipped_shipping_method,
    _created_join.shipped_memo,
    _created_join.processed_po_id,
    _created_join.processed_status_name,
    _created_join.processed,
    _created_join.processed_cancelled,
    _created_join.processed_type,
    _created_join.processed_priority,
    _created_join.processed_shipping_method,
    _created_join.processed_memo,
    _created_join.received_po_id,
    _created_join.received_status_name,
    _created_join.received,
    _created_join.received_cancelled,
    _created_join.received_type,
    _created_join.received_priority,
    _created_join.received_shipping_method,
    _created_join.received_memo,
    _created_join.invoiced_po_id,
    _created_join.invoiced_status_name,
    _created_join.invoiced,
    _created_join.invoiced_invoice_total,
    _created_join.invoiced_cancelled,
    _created_join.invoiced_vendor_invoice_date,
    _created_join.invoiced_vendor_invoice_number,
    _created_join.invoiced_type,
    _created_join.invoiced_priority,
    _created_join.invoiced_shipping_method,
    _created_join.invoiced_memo,
    _created_join.approved_po_id,
    _created_join.approved_status_name,
    _created_join.approved,
    _created_join.approved_cancelled,
    _created_join.approved_type,
    _created_join.approved_priority,
    _created_join.approved_shipping_method,
    _created_join.approved_memo,
    _created_join.current_status,
    _created_join.po_cancelled,
    _po_items.reorder_qty_upc AS approved_qty
  FROM _created_join
  LEFT JOIN _po_items
    ON _created_join.approved_po_id = _po_items.purchase_order_id
    AND _created_join.upc = _po_items.upc
    AND _created_join.msku = _po_items.msku
), _Join_Invoiced AS (
  SELECT
    _approved_join.purchase_order_id,
    _approved_join.reorder_qty_upc,
    _approved_join.upc,
    _approved_join.msku,
    _approved_join.approved_qty,
    _approved_join.number,
    _approved_join.status_name,
    _approved_join.amazon_seller_id,
    _approved_join.status,
    _approved_join.status_at,
    _approved_join.order_total,
    _approved_join.cancelled,
    _approved_join.vendor_invoice_date,
    _approved_join.vendor_invoice_number,
    _approved_join.vendor_name,
    _approved_join.inventory_vendor_id,
    _approved_join.type,
    _approved_join.priority,
    _approved_join.shipping_method,
    _approved_join.memo,
    _approved_join.shipped_po_id,
    _approved_join.shipped_status_name,
    _approved_join.shipped,
    _approved_join.shipped_cancelled,
    _approved_join.shipped_type,
    _approved_join.shipped_priority,
    _approved_join.shipped_shipping_method,
    _approved_join.shipped_memo,
    _approved_join.processed_po_id,
    _approved_join.processed_status_name,
    _approved_join.processed,
    _approved_join.processed_cancelled,
    _approved_join.processed_type,
    _approved_join.processed_priority,
    _approved_join.processed_shipping_method,
    _approved_join.processed_memo,
    _approved_join.received_po_id,
    _approved_join.received_status_name,
    _approved_join.received,
    _approved_join.received_cancelled,
    _approved_join.received_type,
    _approved_join.received_priority,
    _approved_join.received_shipping_method,
    _approved_join.received_memo,
    _approved_join.invoiced_po_id,
    _approved_join.invoiced_status_name,
    _approved_join.invoiced,
    _approved_join.invoiced_invoice_total,
    _approved_join.invoiced_cancelled,
    _approved_join.invoiced_vendor_invoice_date,
    _approved_join.invoiced_vendor_invoice_number,
    _approved_join.invoiced_type,
    _approved_join.invoiced_priority,
    _approved_join.invoiced_shipping_method,
    _approved_join.invoiced_memo,
    _approved_join.approved_po_id,
    _approved_join.approved_status_name,
    _approved_join.approved,
    _approved_join.approved_cancelled,
    _approved_join.approved_type,
    _approved_join.approved_priority,
    _approved_join.approved_shipping_method,
    _approved_join.approved_memo,
    _approved_join.current_status,
    _approved_join.po_cancelled,
    _po_items.reorder_qty_upc AS invoiced_qty
  FROM _approved_join
  LEFT JOIN _po_items
    ON _approved_join.upc = _po_items.upc
    AND _approved_join.invoiced_po_id = _po_items.purchase_order_id
    AND _approved_join.msku = _po_items.msku
), _Join_Received AS (
  SELECT
    _Join_Invoiced.purchase_order_id,
    _Join_Invoiced.reorder_qty_upc,
    _Join_Invoiced.upc,
    _Join_Invoiced.msku,
    _Join_Invoiced.approved_qty,
    _Join_Invoiced.number,
    _Join_Invoiced.status_name,
    _Join_Invoiced.amazon_seller_id,
    _Join_Invoiced.status,
    _Join_Invoiced.status_at,
    _Join_Invoiced.order_total,
    _Join_Invoiced.cancelled,
    _Join_Invoiced.vendor_invoice_date,
    _Join_Invoiced.vendor_invoice_number,
    _Join_Invoiced.vendor_name,
    _Join_Invoiced.inventory_vendor_id,
    _Join_Invoiced.type,
    _Join_Invoiced.priority,
    _Join_Invoiced.shipping_method,
    _Join_Invoiced.memo,
    _Join_Invoiced.shipped_po_id,
    _Join_Invoiced.shipped_status_name,
    _Join_Invoiced.shipped,
    _Join_Invoiced.shipped_cancelled,
    _Join_Invoiced.shipped_type,
    _Join_Invoiced.shipped_priority,
    _Join_Invoiced.shipped_shipping_method,
    _Join_Invoiced.shipped_memo,
    _Join_Invoiced.processed_po_id,
    _Join_Invoiced.processed_status_name,
    _Join_Invoiced.processed,
    _Join_Invoiced.processed_cancelled,
    _Join_Invoiced.processed_type,
    _Join_Invoiced.processed_priority,
    _Join_Invoiced.processed_shipping_method,
    _Join_Invoiced.processed_memo,
    _Join_Invoiced.received_po_id,
    _Join_Invoiced.received_status_name,
    _Join_Invoiced.received,
    _Join_Invoiced.received_cancelled,
    _Join_Invoiced.received_type,
    _Join_Invoiced.received_priority,
    _Join_Invoiced.received_shipping_method,
    _Join_Invoiced.received_memo,
    _Join_Invoiced.invoiced_po_id,
    _Join_Invoiced.invoiced_status_name,
    _Join_Invoiced.invoiced,
    _Join_Invoiced.invoiced_invoice_total,
    _Join_Invoiced.invoiced_cancelled,
    _Join_Invoiced.invoiced_vendor_invoice_date,
    _Join_Invoiced.invoiced_vendor_invoice_number,
    _Join_Invoiced.invoiced_type,
    _Join_Invoiced.invoiced_priority,
    _Join_Invoiced.invoiced_shipping_method,
    _Join_Invoiced.invoiced_memo,
    _Join_Invoiced.approved_po_id,
    _Join_Invoiced.approved_status_name,
    _Join_Invoiced.approved,
    _Join_Invoiced.approved_cancelled,
    _Join_Invoiced.approved_type,
    _Join_Invoiced.approved_priority,
    _Join_Invoiced.approved_shipping_method,
    _Join_Invoiced.approved_memo,
    _Join_Invoiced.current_status,
    _Join_Invoiced.po_cancelled,
    _Join_Invoiced.invoiced_qty,
    _po_items.reorder_qty_upc AS received_qty
  FROM _Join_Invoiced
  LEFT JOIN _po_items
    ON _Join_Invoiced.upc = _po_items.upc
    AND _Join_Invoiced.received_po_id = _po_items.purchase_order_id
    AND _Join_Invoiced.msku = _po_items.msku
), _Join_Processed AS (
  SELECT
    _Join_Received.purchase_order_id,
    _Join_Received.reorder_qty_upc,
    _Join_Received.upc,
    _Join_Received.msku,
    _Join_Received.approved_qty,
    _Join_Received.number,
    _Join_Received.status_name,
    _Join_Received.amazon_seller_id,
    _Join_Received.status,
    _Join_Received.status_at,
    _Join_Received.order_total,
    _Join_Received.cancelled,
    _Join_Received.vendor_invoice_date,
    _Join_Received.vendor_invoice_number,
    _Join_Received.vendor_name,
    _Join_Received.inventory_vendor_id,
    _Join_Received.type,
    _Join_Received.priority,
    _Join_Received.shipping_method,
    _Join_Received.memo,
    _Join_Received.shipped_po_id,
    _Join_Received.shipped_status_name,
    _Join_Received.shipped,
    _Join_Received.shipped_cancelled,
    _Join_Received.shipped_type,
    _Join_Received.shipped_priority,
    _Join_Received.shipped_shipping_method,
    _Join_Received.shipped_memo,
    _Join_Received.processed_po_id,
    _Join_Received.processed_status_name,
    _Join_Received.processed,
    _Join_Received.processed_cancelled,
    _Join_Received.processed_type,
    _Join_Received.processed_priority,
    _Join_Received.processed_shipping_method,
    _Join_Received.processed_memo,
    _Join_Received.received_po_id,
    _Join_Received.received_status_name,
    _Join_Received.received,
    _Join_Received.received_cancelled,
    _Join_Received.received_type,
    _Join_Received.received_priority,
    _Join_Received.received_shipping_method,
    _Join_Received.received_memo,
    _Join_Received.invoiced_po_id,
    _Join_Received.invoiced_status_name,
    _Join_Received.invoiced,
    _Join_Received.invoiced_invoice_total,
    _Join_Received.invoiced_cancelled,
    _Join_Received.invoiced_vendor_invoice_date,
    _Join_Received.invoiced_vendor_invoice_number,
    _Join_Received.invoiced_type,
    _Join_Received.invoiced_priority,
    _Join_Received.invoiced_shipping_method,
    _Join_Received.invoiced_memo,
    _Join_Received.approved_po_id,
    _Join_Received.approved_status_name,
    _Join_Received.approved,
    _Join_Received.approved_cancelled,
    _Join_Received.approved_type,
    _Join_Received.approved_priority,
    _Join_Received.approved_shipping_method,
    _Join_Received.approved_memo,
    _Join_Received.current_status,
    _Join_Received.po_cancelled,
    _Join_Received.invoiced_qty,
    _Join_Received.received_qty,
    _po_items.reorder_qty_upc AS processed_qty
  FROM _Join_Received
  LEFT JOIN _po_items
    ON _Join_Received.upc = _po_items.upc
    AND _Join_Received.processed_po_id = _po_items.purchase_order_id
    AND _Join_Received.msku = _po_items.msku
), _Join_Shipped AS (
  SELECT
    _Join_Processed.purchase_order_id,
    _Join_Processed.reorder_qty_upc,
    _Join_Processed.upc,
    _Join_Processed.msku,
    _Join_Processed.approved_qty,
    _Join_Processed.number,
    _Join_Processed.status_name,
    _Join_Processed.amazon_seller_id,
    _Join_Processed.status,
    _Join_Processed.status_at,
    _Join_Processed.order_total,
    _Join_Processed.cancelled,
    _Join_Processed.vendor_invoice_date,
    _Join_Processed.vendor_invoice_number,
    _Join_Processed.vendor_name,
    _Join_Processed.inventory_vendor_id,
    _Join_Processed.type,
    _Join_Processed.priority,
    _Join_Processed.shipping_method,
    _Join_Processed.memo,
    _Join_Processed.shipped_po_id,
    _Join_Processed.shipped_status_name,
    _Join_Processed.shipped,
    _Join_Processed.shipped_cancelled,
    _Join_Processed.shipped_type,
    _Join_Processed.shipped_priority,
    _Join_Processed.shipped_shipping_method,
    _Join_Processed.shipped_memo,
    _Join_Processed.processed_po_id,
    _Join_Processed.processed_status_name,
    _Join_Processed.processed,
    _Join_Processed.processed_cancelled,
    _Join_Processed.processed_type,
    _Join_Processed.processed_priority,
    _Join_Processed.processed_shipping_method,
    _Join_Processed.processed_memo,
    _Join_Processed.received_po_id,
    _Join_Processed.received_status_name,
    _Join_Processed.received,
    _Join_Processed.received_cancelled,
    _Join_Processed.received_type,
    _Join_Processed.received_priority,
    _Join_Processed.received_shipping_method,
    _Join_Processed.received_memo,
    _Join_Processed.invoiced_po_id,
    _Join_Processed.invoiced_status_name,
    _Join_Processed.invoiced,
    _Join_Processed.invoiced_invoice_total,
    _Join_Processed.invoiced_cancelled,
    _Join_Processed.invoiced_vendor_invoice_date,
    _Join_Processed.invoiced_vendor_invoice_number,
    _Join_Processed.invoiced_type,
    _Join_Processed.invoiced_priority,
    _Join_Processed.invoiced_shipping_method,
    _Join_Processed.invoiced_memo,
    _Join_Processed.approved_po_id,
    _Join_Processed.approved_status_name,
    _Join_Processed.approved,
    _Join_Processed.approved_cancelled,
    _Join_Processed.approved_type,
    _Join_Processed.approved_priority,
    _Join_Processed.approved_shipping_method,
    _Join_Processed.approved_memo,
    _Join_Processed.current_status,
    _Join_Processed.po_cancelled,
    _Join_Processed.invoiced_qty,
    _Join_Processed.received_qty,
    _Join_Processed.processed_qty,
    _po_items.reorder_qty_upc AS shipped_qty
  FROM _Join_Processed
  LEFT JOIN _po_items
    ON _Join_Processed.upc = _po_items.upc
    AND _Join_Processed.shipped_po_id = _po_items.purchase_order_id
    AND _Join_Processed.msku = _po_items.msku
), _select_by_msku AS (
  SELECT
    amazon_seller_id,
    number AS po_number,
    current_status,
    created,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    upc,
    msku,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    po_cancelled,
    vendor_name,
    type,
    priority,
    shipping_method,
    memo
  FROM _Join_Shipped
), _Group_By_UPC AS (
  SELECT
    number,
    amazon_seller_id,
    upc,
    created,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    SUM(created_qty) AS created_qty,
    SUM(approved_qty) AS approved_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(received_qty) AS received_qty,
    SUM(processed_qty) AS processed_qty,
    SUM(shipped_qty) AS shipped_qty,
    MAX(type) AS type,
    MAX(priority) AS priority,
    MAX(shipping_method) AS shipping_method,
    MAX(memo) AS memo
  FROM _Join_Shipped
  GROUP BY
    number,
    amazon_seller_id,
    upc,
    created,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name
), _Purchase_Orders_Details_by_MSKU_DS AS (
  SELECT
    *
  FROM _select_by_msku
), _Group_By_MSKU AS (
  SELECT
    msku,
    MAX(invoiced) AS last_invoice_date,
    MAX(memo) AS most_recent_memo,
    MAX(po_number) AS most_recent_po_number
  FROM _select_by_msku
  GROUP BY
    msku
), _Join_Data AS (
  SELECT
    _Group_By_UPC.number,
    _Group_By_UPC.amazon_seller_id,
    _Group_By_UPC.upc,
    _Group_By_UPC.approved,
    _Group_By_UPC.invoiced,
    _Group_By_UPC.received,
    _Group_By_UPC.processed,
    _Group_By_UPC.shipped,
    _Group_By_UPC.current_status,
    _Group_By_UPC.invoiced_invoice_total,
    _Group_By_UPC.po_cancelled,
    _Group_By_UPC.vendor_invoice_date,
    _Group_By_UPC.vendor_invoice_number,
    _Group_By_UPC.vendor_name,
    _Group_By_UPC.created_qty,
    _Group_By_UPC.approved_qty,
    _Group_By_UPC.invoiced_qty,
    _Group_By_UPC.received_qty,
    _Group_By_UPC.processed_qty,
    _Group_By_UPC.shipped_qty,
    _Group_By_UPC.type,
    _Group_By_UPC.priority,
    _Group_By_UPC.shipping_method,
    _Group_By_UPC.memo,
    _upcs_fields.partner_name,
    _upcs_fields.brand,
    _upcs_fields.upc_name,
    _upcs_fields.cost,
    _upcs_fields.wholesale_price,
    _upcs_fields.map,
    _upcs_fields.srp
  FROM _Group_By_UPC
  LEFT JOIN _upcs_fields
    ON _Group_By_UPC.upc = _upcs_fields.upc
    AND _Group_By_UPC.amazon_seller_id = _upcs_fields.amazon_seller_id
), _Alter_Columns AS (
  SELECT
    CAST(last_invoice_date AS DATE),
    msku,
    most_recent_memo,
    most_recent_po_number
  FROM _Group_By_MSKU
), _Extended_Cost AS (
  SELECT
    number,
    amazon_seller_id,
    upc,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    type,
    priority,
    shipping_method,
    memo,
    partner_name,
    brand,
    upc_name,
    cost,
    wholesale_price,
    map,
    srp,
    (
      cost * invoiced_qty
    ) AS extended_cost_invoiced,
    (
      cost * approved_qty
    ) AS extended_cost_approved,
    (
      DATEDIFF(DAY, approved, received)
    ) AS lead_time
  FROM _Join_Data
), _Extended_Cost_1 AS (
  SELECT
    number,
    amazon_seller_id,
    upc,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    type,
    priority,
    shipping_method,
    memo,
    partner_name,
    brand,
    upc_name,
    cost,
    wholesale_price,
    map,
    srp,
    (
      cost * invoiced_qty
    ) AS extended_cost
  FROM _Join_Data
), _Join_Data_1 AS (
  SELECT
    _Alter_Columns.msku,
    _Alter_Columns.last_invoice_date,
    _Alter_Columns.most_recent_memo,
    _Alter_Columns.most_recent_po_number,
    _Product_List_DataSet.amazon_seller_id,
    _Product_List_DataSet.asin,
    _Product_List_DataSet.brand_id,
    _Product_List_DataSet.client_id,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.id,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.sku,
    _Product_List_DataSet.units_in_listing,
    _Product_List_DataSet.upc,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.batch_id,
    _Product_List_DataSet.batch_last_run,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.brand,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.country_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.name,
    _Product_List_DataSet.upc_name
  FROM _Alter_Columns
  LEFT JOIN _Product_List_DataSet
    ON _Alter_Columns.msku = _Product_List_DataSet.sku
), _Group_By_PO_and_partner AS (
  SELECT
    number,
    invoiced,
    current_status,
    created,
    processed,
    shipped,
    approved,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    partner_name,
    vendor_name,
    received,
    brand,
    SUM(extended_cost_invoiced) AS extended_cost_invoiced,
    SUM(created_qty) AS created_qty,
    SUM(approved_qty) AS approved_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(received_qty) AS received_qty,
    SUM(extended_cost_approved) AS extended_cost_approved,
    MAX(type) AS type,
    MAX(priority) AS priority,
    MAX(shipping_method) AS shipping_method,
    MAX(memo) AS memo,
    AVG(lead_time) AS lead_time,
    AVG(invoiced_invoice_total) AS invoiced_invoice_total
  FROM _Extended_Cost
  GROUP BY
    number,
    invoiced,
    current_status,
    created,
    processed,
    shipped,
    approved,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    partner_name,
    vendor_name,
    received,
    brand
), _Add_Formula_5 AS (
  SELECT
    number,
    amazon_seller_id,
    upc,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    vendor_name,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    type,
    priority,
    shipping_method,
    memo,
    partner_name,
    brand,
    upc_name,
    cost,
    wholesale_price,
    map,
    srp,
    extended_cost_invoiced,
    extended_cost_approved,
    lead_time,
    (
      TO_CHAR(invoiced, 'mmmm-yyyy')
    ) AS month-year
  FROM _Extended_Cost
), _select_by_upc AS (
  SELECT
    amazon_seller_id,
    number AS po_number,
    po_cancelled,
    current_status,
    created,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    upc,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    brand,
    partner_name,
    cost,
    wholesale_price,
    map,
    upc_name,
    extended_cost,
    invoiced_invoice_total,
    vendor_invoice_date,
    vendor_invoice_number,
    srp AS msrp,
    vendor_name,
    priority,
    type,
    shipping_method,
    memo
  FROM _Extended_Cost_1
), _Select_Columns_1 AS (
  SELECT
    msku,
    asin,
    last_invoice_date,
    upc,
    upc_name,
    most_recent_memo,
    most_recent_po_number
  FROM _Join_Data_1
), _Select_Columns AS (
  SELECT
    number AS po_number,
    invoiced,
    current_status,
    created,
    processed,
    shipped,
    invoiced_invoice_total,
    approved,
    po_cancelled,
    vendor_invoice_date,
    vendor_invoice_number,
    partner_name,
    vendor_name,
    extended_cost_invoiced,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    extended_cost_approved,
    type,
    priority,
    shipping_method,
    memo,
    received,
    lead_time,
    brand
  FROM _Group_By_PO_and_partner
), _Group_By_4 AS (
  SELECT
    brand,
    month-year,
    SUM(approved_qty) AS approved_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(received_qty) AS received_qty,
    AVG(invoiced_invoice_total) AS invoiced_invoice_total
  FROM _Add_Formula_5
  GROUP BY
    brand,
    month-year
), _Filter_Rows_1 AS (
  SELECT
    *
  FROM _select_by_upc
  WHERE
    (
      NOT current_status LIKE '%approved%'
    )
    OR (
      NOT current_status LIKE '%created%'
    )
    OR (
      NOT vendor_invoice_date IS NULL
    )
), _MSKU_w_ASIN_Last_Order_Date AS (
  SELECT
    *
  FROM _Select_Columns_1
), _Alter_Columns_1 AS (
  SELECT
    CAST(invoiced AS DATE),
    CAST(created AS DATE),
    CAST(processed AS DATE),
    CAST(shipped AS DATE),
    CAST(approved AS DATE),
    CAST(vendor_invoice_date AS DATE),
    CAST(received AS DATE),
    po_number,
    current_status,
    invoiced_invoice_total,
    po_cancelled,
    vendor_invoice_number,
    partner_name,
    vendor_name,
    extended_cost_invoiced,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    extended_cost_approved,
    type,
    priority,
    shipping_method,
    memo,
    lead_time,
    brand
  FROM _Select_Columns
), _Join_Data_3 AS (
  SELECT
    _Group_By_5.brand,
    _Group_By_5.month-year,
    _Group_By_5.item_price,
    _Group_By_4.approved_qty,
    _Group_By_4.invoiced_qty,
    _Group_By_4.received_qty,
    _Group_By_4.invoiced_invoice_total
  FROM _Group_By_5
  INNER JOIN _Group_By_4
    ON _Group_By_5.month-year = _Group_By_4.month-year
    AND _Group_By_5.brand = _Group_By_4.brand
), _step_180_Days AS (
  SELECT
    *
  FROM _Filter_Rows_1
  WHERE
    invoiced > CURRENT_DATE - 180
), _step_60_Day AS (
  SELECT
    *
  FROM _Filter_Rows_1
  WHERE
    invoiced > CURRENT_DATE - 60
), _Jan_Feb_22_Fill_Rate_by_UPC_1 AS (
  SELECT
    *
  FROM _Filter_Rows_1
  WHERE
    (
      invoiced >= '2022-01-01' AND invoiced <= '2022-02-25'
    )
), _Group_By AS (
  SELECT
    partner_name,
    brand,
    AVG(lead_time) AS lead_time_avg,
    STDDEV(lead_time) AS lead_time_std
  FROM _Alter_Columns_1
  GROUP BY
    partner_name,
    brand
), _Remove_Duplicates AS (
  SELECT DISTINCT
    *
  FROM _Alter_Columns_1
), _Sales_Purchases_draft AS (
  SELECT
    *
  FROM _Join_Data_3
), _Add_Formula AS (
  SELECT
    amazon_seller_id,
    po_number,
    po_cancelled,
    current_status,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    upc,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    brand,
    partner_name,
    cost,
    wholesale_price,
    map,
    upc_name,
    extended_cost,
    invoiced_invoice_total,
    vendor_invoice_date,
    vendor_invoice_number,
    msrp,
    vendor_name,
    priority,
    type,
    shipping_method,
    memo,
    (
      MONTH(TO_DATE(approved))
    ) AS month,
    (
      YEAR(TO_DATE(approved))
    ) AS year
  FROM _step_180_Days
), _Add_Formula_2 AS (
  SELECT
    amazon_seller_id,
    po_number,
    po_cancelled,
    current_status,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    upc,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    brand,
    partner_name,
    cost,
    wholesale_price,
    map,
    upc_name,
    extended_cost,
    invoiced_invoice_total,
    vendor_invoice_date,
    vendor_invoice_number,
    msrp,
    vendor_name,
    priority,
    type,
    shipping_method,
    memo,
    (
      MONTH(TO_DATE(approved))
    ) AS month,
    (
      YEAR(TO_DATE(approved))
    ) AS year
  FROM _step_60_Day
), _Add_Formula_6 AS (
  SELECT
    amazon_seller_id,
    po_number,
    po_cancelled,
    current_status,
    approved,
    invoiced,
    received,
    processed,
    shipped,
    upc,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    processed_qty,
    shipped_qty,
    brand,
    partner_name,
    cost,
    wholesale_price,
    map,
    upc_name,
    extended_cost,
    invoiced_invoice_total,
    vendor_invoice_date,
    vendor_invoice_number,
    msrp,
    vendor_name,
    priority,
    type,
    shipping_method,
    memo,
    (
      MONTH(TO_DATE(approved))
    ) AS month,
    (
      YEAR(TO_DATE(approved))
    ) AS year
  FROM _Jan_Feb_22_Fill_Rate_by_UPC_1
), _Join_Data_2 AS (
  SELECT
    _Group_By_3.partner_name,
    _Group_By_3.brand,
    _Group_By_3.sales,
    _Group_By_3.sales_std,
    _Group_By.lead_time_avg,
    _Group_By.lead_time_std
  FROM _Group_By_3
  RIGHT JOIN _Group_By
    ON _Group_By_3.partner_name = _Group_By.partner_name
    AND _Group_By_3.brand = _Group_By.brand
), _PO_Invoices_by_Partner AS (
  SELECT
    *
  FROM _Remove_Duplicates
), _Group_By_1 AS (
  SELECT
    upc,
    brand,
    upc_name,
    partner_name,
    amazon_seller_id,
    SUM(approved_qty) AS approved_qty,
    SUM(received_qty) AS received_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(created_qty) AS created_qty
  FROM _Add_Formula
  GROUP BY
    upc,
    brand,
    upc_name,
    partner_name,
    amazon_seller_id
), _Group_By_2 AS (
  SELECT
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id,
    SUM(created_qty) AS created_qty,
    SUM(approved_qty) AS approved_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(received_qty) AS received_qty
  FROM _Add_Formula_2
  GROUP BY
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id
), _Group_By_6 AS (
  SELECT
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id,
    SUM(created_qty) AS created_qty,
    SUM(approved_qty) AS approved_qty,
    SUM(invoiced_qty) AS invoiced_qty,
    SUM(received_qty) AS received_qty
  FROM _Add_Formula_6
  GROUP BY
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id
), _Join_vendor_lead_times AS (
  SELECT
    _select_by_upc.amazon_seller_id,
    _select_by_upc.po_number,
    _select_by_upc.po_cancelled,
    _select_by_upc.current_status,
    _select_by_upc.approved,
    _select_by_upc.invoiced,
    _select_by_upc.received,
    _select_by_upc.processed,
    _select_by_upc.shipped,
    _select_by_upc.upc,
    _select_by_upc.created_qty,
    _select_by_upc.approved_qty,
    _select_by_upc.invoiced_qty,
    _select_by_upc.received_qty,
    _select_by_upc.processed_qty,
    _select_by_upc.shipped_qty,
    _select_by_upc.brand,
    _select_by_upc.partner_name,
    _select_by_upc.cost,
    _select_by_upc.wholesale_price,
    _select_by_upc.map,
    _select_by_upc.upc_name,
    _select_by_upc.extended_cost,
    _select_by_upc.invoiced_invoice_total,
    _select_by_upc.vendor_invoice_date,
    _select_by_upc.vendor_invoice_number,
    _select_by_upc.msrp,
    _select_by_upc.vendor_name,
    _select_by_upc.priority,
    _select_by_upc.type,
    _select_by_upc.shipping_method,
    _select_by_upc.memo,
    _Join_Data_2.sales,
    _Join_Data_2.sales_std,
    _Join_Data_2.lead_time_avg,
    _Join_Data_2.lead_time_std
  FROM _select_by_upc
  LEFT JOIN _Join_Data_2
    ON _select_by_upc.partner_name = _Join_Data_2.partner_name
    AND _select_by_upc.brand = _Join_Data_2.brand
), _Partner_Lead_Times AS (
  SELECT
    *
  FROM _Join_Data_2
), _Add_Formula_1 AS (
  SELECT
    upc,
    brand,
    upc_name,
    partner_name,
    amazon_seller_id,
    approved_qty,
    received_qty,
    invoiced_qty,
    created_qty,
    (
      invoiced_qty / NULLIF(created_qty, 0)
    ) AS 180_day_fill_rate,
    (
      created_qty / NULLIF(approved_qty, 0)
    ) AS 180_day_cut_rate
  FROM _Group_By_1
), _Add_Formula_3 AS (
  SELECT
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    (
      invoiced_qty / NULLIF(created_qty, 0)
    ) AS 60_day_fill_rate,
    (
      created_qty / NULLIF(approved_qty, 0)
    ) AS 60_day_cut_rate
  FROM _Group_By_2
), _Add_Formula_7 AS (
  SELECT
    upc,
    brand,
    partner_name,
    upc_name,
    amazon_seller_id,
    created_qty,
    approved_qty,
    invoiced_qty,
    received_qty,
    (
      invoiced_qty / NULLIF(created_qty, 0)
    ) AS fill_rate
  FROM _Group_By_6
), _Purchase_Orders_Details_by_UPC_DS AS (
  SELECT
    *
  FROM _Join_vendor_lead_times
), _step_180_Day_Fill_Rate_by_UPC AS (
  SELECT
    *
  FROM _Add_Formula_1
), _step_60_Day_Fill_Rate_by_UPC AS (
  SELECT
    *
  FROM _Add_Formula_3
), _Jan_Feb_22_Fill_Rate_by_UPC AS (
  SELECT
    *
  FROM _Add_Formula_7
)
SELECT
  *
FROM _Jan_Feb_22_Fill_Rate_by_UPC