/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 358
Dataflow Name: Inventory at Amazon Report DF
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 57
  Successful: 57
  Failed: 0
  Unique Action Types: 10
  Action Types: Constant, ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, PublishToVault, SelectValues, UnionAll, Unique
  Pipelines: 10

Generated: 2025-07-02 10:24:36
================================================================================
*/
WITH _vw_inventory_reordering AS (
  SELECT
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    amazon_seller_id,
    asin,
    brand,
    brandid,
    cost,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    sku,
    replenishment_plan,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run
  FROM vw_inventory_reordering
), _NS_Local_Inventory_by_SKU AS (
  SELECT
    asin,
    sku,
    units_in_listing,
    is_bundle,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    upc,
    id
  FROM NS_Local_Inventory_by_SKU
), _ns_po_qty_by_sku AS (
  SELECT
    asin,
    created_at,
    id,
    ns_upc_fulfilled,
    ns_upc_qty,
    past_sales_sku_qty,
    past_sales_upc_qty,
    po_sku_inventory,
    po_upc_inventory,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc,
    upc_percentage,
    updated_at,
    batch_id,
    batch_last_run
  FROM ns_po_qty_by_sku
), _ns_local_inventory_mfn_by_sku AS (
  SELECT
    asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc,
    upc_percentage,
    updated_at,
    firefly_ignore_mfn,
    batch_id,
    batch_last_run
  FROM ns_local_inventory_mfn_by_sku
), _amazon_skus AS (
  SELECT
    amazon_asin_id,
    amazon_seller_id,
    asin,
    amazon_1,
    brand_id,
    catalog_last_appearance,
    client_id,
    comments,
    country_id,
    created_at,
    created_by,
    date_of_first_sale,
    date_of_last_sale,
    deleted_at,
    deleted_by,
    fnsku,
    fulfillment_channel,
    id,
    is_bundle,
    last_referral_fee,
    last_seen_price,
    last_shipping_fee,
    map,
    max_reorder_daily_velocity,
    min_order_qty,
    min_reorder_daily_velocity,
    name,
    old_sku,
    parent_variation,
    reorder_comments,
    reorder_status,
    sku,
    srp,
    status,
    test_merge,
    units_in_listing,
    upc,
    upc_id,
    updated_at,
    updated_by,
    vendor_parameter_id,
    is_preferred_sku_by_asin,
    is_relist_authorized,
    is_inbounding_authorized,
    is_delete_once_sold_out,
    is_agency,
    is_dangerous_good,
    is_apparel,
    is_certified_renewed,
    lithium_battery_fee,
    velocity,
    primary_velocity,
    discontinued_reason_id,
    not_sellable_reason,
    is_virtual_tracking,
    transparency_label_type_id,
    batch_id,
    batch_last_run
  FROM amazon_skus
), _ns_nonsellable_inventory_by_sku AS (
  SELECT
    asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc,
    upc_percentage,
    updated_at,
    batch_id,
    batch_last_run
  FROM ns_nonsellable_inventory_by_sku
), _ware2go_inventory AS (
  SELECT
    amazon_seller_id,
    created_at,
    description,
    id,
    name,
    product_id,
    quantity_available_to_promise,
    quantity_on_hand,
    sku,
    upc,
    updated_at,
    batch_id,
    batch_last_run
  FROM ware2go_inventory
), _amazon_seller_central_accounts AS (
  SELECT
    amazon_seller_id,
    created_at,
    enable_report_gathering,
    end_date,
    id,
    market_place_id,
    merchant_id,
    name,
    secret_access_key,
    selling_partner_id,
    start_date,
    batch_id,
    batch_last_run
  FROM amazon_seller_central_accounts
), _product_upcs AS (
  SELECT
    cost,
    deleted_at,
    id,
    name,
    old_product_id,
    product_id,
    units_in_listing,
    upc,
    upc_id,
    batch_id,
    batch_last_run
  FROM product_upcs
), _countries AS (
  SELECT
    created_at,
    currency,
    enabled,
    id,
    marketplace_id,
    name,
    sales_channel,
    short_name,
    updated_at,
    batch_id,
    batch_last_run
  FROM countries
), _Everything_else AS (
  SELECT
    *
  FROM _vw_inventory_reordering
  WHERE
    partnerid <> '2604'
), _Mission AS (
  SELECT
    *
  FROM _vw_inventory_reordering
  WHERE
    partnerid = '2604'
), _Group_By AS (
  SELECT
    asin,
    upc,
    sku,
    SUM(po_sku_inventory) AS po_sku_inventory,
    SUM(po_upc_inventory) AS po_upc_inventory,
    SUM(ns_upc_qty) AS ns_upc_qty,
    SUM(ns_upc_fulfilled) AS ns_upc_fulfilled
  FROM _ns_po_qty_by_sku
  GROUP BY
    asin,
    upc,
    sku
), _Non_FF AS (
  SELECT
    *
  FROM _ns_local_inventory_mfn_by_sku
  WHERE
    firefly_ignore_mfn = '0'
), _FF AS (
  SELECT
    *
  FROM _ns_local_inventory_mfn_by_sku
  WHERE
    firefly_ignore_mfn = '1'
), _FF_Specific_US_Offers AS (
  SELECT
    *
  FROM _amazon_skus
  WHERE
    (
      amazon_seller_id = '17'
      AND (
        country_id = '1'
        AND (
          status <> 'deleted'
          AND (
            parent_variation = '0'
            AND (
              deleted_at IS NULL AND NOT sku LIKE 'amzn%'
            )
          )
        )
      )
    )
), _Add_Constants_1 AS (
  SELECT
    1 AS constant_value
), _Join_Data_2 AS (
  SELECT
    _amazon_skus.amazon_asin_id,
    _amazon_skus.amazon_seller_id,
    _amazon_skus.asin,
    _amazon_skus.amazon_1,
    _amazon_skus.brand_id,
    _amazon_skus.catalog_last_appearance,
    _amazon_skus.client_id,
    _amazon_skus.comments,
    _amazon_skus.country_id,
    _amazon_skus.created_at,
    _amazon_skus.created_by,
    _amazon_skus.date_of_first_sale,
    _amazon_skus.date_of_last_sale,
    _amazon_skus.deleted_at,
    _amazon_skus.deleted_by,
    _amazon_skus.fnsku,
    _amazon_skus.fulfillment_channel,
    _amazon_skus.id,
    _amazon_skus.is_bundle,
    _amazon_skus.last_referral_fee,
    _amazon_skus.last_seen_price,
    _amazon_skus.last_shipping_fee,
    _amazon_skus.map,
    _amazon_skus.max_reorder_daily_velocity,
    _amazon_skus.min_order_qty,
    _amazon_skus.min_reorder_daily_velocity,
    _amazon_skus.name,
    _amazon_skus.old_sku,
    _amazon_skus.parent_variation,
    _amazon_skus.reorder_comments,
    _amazon_skus.reorder_status,
    _amazon_skus.sku,
    _amazon_skus.srp,
    _amazon_skus.status,
    _amazon_skus.test_merge,
    _amazon_skus.units_in_listing,
    _amazon_skus.upc,
    _amazon_skus.upc_id,
    _amazon_skus.updated_at,
    _amazon_skus.updated_by,
    _amazon_skus.vendor_parameter_id,
    _amazon_skus.is_preferred_sku_by_asin,
    _amazon_skus.is_relist_authorized,
    _amazon_skus.is_inbounding_authorized,
    _amazon_skus.is_delete_once_sold_out,
    _amazon_skus.is_agency,
    _amazon_skus.is_dangerous_good,
    _amazon_skus.is_apparel,
    _amazon_skus.is_certified_renewed,
    _amazon_skus.lithium_battery_fee,
    _amazon_skus.velocity,
    _amazon_skus.primary_velocity,
    _amazon_skus.discontinued_reason_id,
    _amazon_skus.not_sellable_reason,
    _amazon_skus.is_virtual_tracking,
    _amazon_skus.transparency_label_type_id,
    _amazon_skus.batch_id,
    _amazon_skus.batch_last_run,
    _product_upcs.cost,
    _product_upcs.deleted_at AS product_upcs_deleted_at,
    _product_upcs.old_product_id,
    _product_upcs.product_id,
    _product_upcs.units_in_listing AS product_upcs_units_in_listing,
    _product_upcs.upc AS product_upcs_upc,
    _product_upcs.upc_id AS product_upcs_upc_id
  FROM _amazon_skus
  LEFT JOIN _product_upcs
    ON _amazon_skus.id = _product_upcs.product_id
), _Flatten_Inv_metrics AS (
  SELECT
    asin,
    brand,
    brandid,
    partner,
    partnerid,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run,
    amazon_seller_id,
    marketplace_id,
    SUM(sku) AS sku_list,
    MAX(po_approved) AS po_approved,
    MAX(po_invoiced) AS po_invoiced,
    MAX(po_processed) AS po_processed,
    MAX(po_received) AS po_received,
    MAX(afn_fulfillable_quantity) AS afn_fulfillable_quantity,
    MAX(afn_researching_quantity) AS afn_researching_quantity,
    MAX(afn_unsellable_quantity) AS afn_unsellable_quantity,
    MIN(sku) AS sku,
    MAX(inbound_checked_in) AS inbound_checked_in,
    MAX(inbound_delivered) AS inbound_delivered,
    MAX(inbound_in_transit) AS inbound_in_transit,
    MAX(inbound_receiving) AS inbound_receiving,
    MAX(inbound_shipped) AS inbound_shipped,
    MAX(inbound_working) AS inbound_working,
    MAX(inv_age_0_to_90_days) AS inv_age_0_to_90_days,
    MAX(inv_age_91_to_180_days) AS inv_age_91_to_180_days,
    MAX(inv_age_181_to_270_days) AS inv_age_181_to_270_days,
    MAX(inv_age_271_to_365_days) AS inv_age_271_to_365_days,
    MAX(inv_age_365_plus_days) AS inv_age_365_plus_days,
    MAX(reserved_customerorders) AS reserved_customerorders,
    MAX(reserved_fc_processing) AS reserved_fc_processing,
    MAX(reserved_fc_transfers) AS reserved_fc_transfers,
    MAX(cost) AS cost
  FROM _Mission
  GROUP BY
    asin,
    brand,
    brandid,
    partner,
    partnerid,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run,
    amazon_seller_id,
    marketplace_id
), _Add_Constants AS (
  SELECT
    1 AS constant_value
), _Add_Formula_1 AS (
  SELECT
    amazon_seller_id,
    created_at,
    description,
    id,
    name,
    product_id,
    quantity_available_to_promise,
    quantity_on_hand,
    sku,
    upc,
    updated_at,
    batch_id,
    batch_last_run,
    (
      UPPER(sku)
    ) AS clean_sku
  FROM _Add_Constants_1
), _Add_Formula AS (
  SELECT
    amazon_asin_id,
    amazon_seller_id,
    asin,
    amazon_1,
    brand_id,
    catalog_last_appearance,
    client_id,
    comments,
    country_id,
    created_at,
    created_by,
    date_of_first_sale,
    date_of_last_sale,
    deleted_at,
    deleted_by,
    fnsku,
    fulfillment_channel,
    id,
    is_bundle,
    last_referral_fee,
    last_seen_price,
    last_shipping_fee,
    map,
    max_reorder_daily_velocity,
    min_order_qty,
    min_reorder_daily_velocity,
    name,
    old_sku,
    parent_variation,
    reorder_comments,
    reorder_status,
    sku,
    srp,
    status,
    test_merge,
    upc,
    upc_id,
    updated_at,
    updated_by,
    vendor_parameter_id,
    is_preferred_sku_by_asin,
    is_relist_authorized,
    is_inbounding_authorized,
    is_delete_once_sold_out,
    is_agency,
    is_dangerous_good,
    is_apparel,
    is_certified_renewed,
    lithium_battery_fee,
    velocity,
    primary_velocity,
    discontinued_reason_id,
    not_sellable_reason,
    is_virtual_tracking,
    transparency_label_type_id,
    batch_id,
    batch_last_run,
    cost,
    product_upcs_deleted_at,
    old_product_id,
    product_id,
    product_upcs_units_in_listing,
    product_upcs_upc,
    product_upcs_upc_id,
    (
      COALESCE(product_upcs_units_in_listing, units_in_listing)
    ) AS units_in_listing
  FROM _Join_Data_2
), _Get_flatten_Inv AS (
  SELECT
    _Mission.amazon_seller_id,
    _Mission.asin,
    _Mission.brand,
    _Mission.brandid,
    _Mission.cost,
    _Mission.marketplace_id,
    _Mission.partner,
    _Mission.partnerid,
    _Mission.sku,
    _Mission.replenishment_plan,
    _Mission.submitted_date,
    _Mission.imported_at,
    _Mission.updated_at,
    _Mission.batch_id,
    _Mission.batch_last_run,
    _Flatten_Inv_metrics.po_approved,
    _Flatten_Inv_metrics.po_invoiced,
    _Flatten_Inv_metrics.po_processed,
    _Flatten_Inv_metrics.po_received,
    _Flatten_Inv_metrics.afn_fulfillable_quantity,
    _Flatten_Inv_metrics.afn_researching_quantity,
    _Flatten_Inv_metrics.afn_unsellable_quantity,
    _Flatten_Inv_metrics.inbound_checked_in,
    _Flatten_Inv_metrics.inbound_delivered,
    _Flatten_Inv_metrics.inbound_in_transit,
    _Flatten_Inv_metrics.inbound_receiving,
    _Flatten_Inv_metrics.inbound_shipped,
    _Flatten_Inv_metrics.inbound_working,
    _Flatten_Inv_metrics.inv_age_0_to_90_days,
    _Flatten_Inv_metrics.inv_age_91_to_180_days,
    _Flatten_Inv_metrics.inv_age_181_to_270_days,
    _Flatten_Inv_metrics.inv_age_271_to_365_days,
    _Flatten_Inv_metrics.inv_age_365_plus_days,
    _Flatten_Inv_metrics.reserved_customerorders,
    _Flatten_Inv_metrics.reserved_fc_processing,
    _Flatten_Inv_metrics.reserved_fc_transfers
  FROM _Mission
  LEFT JOIN _Flatten_Inv_metrics
    ON _Mission.asin = _Flatten_Inv_metrics.asin
    AND _Mission.sku = _Flatten_Inv_metrics.sku
), _Distinct_Columns_for_Later AS (
  SELECT
    asin,
    fulfillment_channel,
    grouphack
  FROM _Add_Constants
), _Select_Columns_with_Bundle_Units_in_Listing AS (
  SELECT
    sku,
    name AS sku_name,
    upc AS sku_upc,
    country_id,
    asin,
    amazon_seller_id,
    is_preferred_sku_by_asin,
    reorder_status AS sku_reorder_status,
    units_in_listing,
    is_bundle
  FROM _Add_Formula
), _Add_0_to_dup_rows AS (
  SELECT
    amazon_seller_id,
    asin,
    brand,
    brandid,
    cost,
    marketplace_id,
    partner,
    partnerid,
    sku,
    replenishment_plan,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run,
    (
      COALESCE(po_approved, 0)
    ) AS po_approved,
    (
      COALESCE(po_invoiced, 0)
    ) AS po_invoiced,
    (
      COALESCE(po_processed, 0)
    ) AS po_processed,
    (
      COALESCE(po_received, 0)
    ) AS po_received,
    (
      COALESCE(afn_fulfillable_quantity, 0)
    ) AS afn_fulfillable_quantity,
    (
      COALESCE(afn_researching_quantity, 0)
    ) AS afn_researching_quantity,
    (
      COALESCE(afn_unsellable_quantity, 0)
    ) AS afn_unsellable_quantity,
    (
      COALESCE(inbound_checked_in, 0)
    ) AS inbound_checked_in,
    (
      COALESCE(inbound_delivered, 0)
    ) AS inbound_delivered,
    (
      COALESCE(inbound_in_transit, 0)
    ) AS inbound_in_transit,
    (
      COALESCE(inbound_receiving, 0)
    ) AS inbound_receiving,
    (
      COALESCE(inbound_shipped, 0)
    ) AS inbound_shipped,
    (
      COALESCE(inbound_working, 0)
    ) AS inbound_working,
    (
      COALESCE(reserved_customerorders, 0)
    ) AS reserved_customerorders,
    (
      COALESCE(reserved_fc_processing, 0)
    ) AS reserved_fc_processing,
    (
      COALESCE(reserved_fc_transfers, 0)
    ) AS reserved_fc_transfers,
    (
      COALESCE(inv_age_0_to_90_days, 0)
    ) AS inv_age_0_to_90_days,
    (
      COALESCE(inv_age_91_to_180_days, 0)
    ) AS inv_age_91_to_180_days,
    (
      COALESCE(inv_age_181_to_270_days, 0)
    ) AS inv_age_181_to_270_days,
    (
      COALESCE(inv_age_271_to_365_days, 0)
    ) AS inv_age_271_to_365_days,
    (
      COALESCE(inv_age_365_plus_days, 0)
    ) AS inv_age_365_plus_days
  FROM _Get_flatten_Inv
), _Group_for_Distinct AS (
  SELECT
    asin,
    fulfillment_channel,
    MAX(grouphack) AS grouphack
  FROM _Distinct_Columns_for_Later
  GROUP BY
    asin,
    fulfillment_channel
), _Remove_Duplicates AS (
  SELECT DISTINCT
    *
  FROM _Select_Columns_with_Bundle_Units_in_Listing
), _Clean_Inventory_removing_virtual_tracking_dups AS (
  SELECT
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    amazon_seller_id,
    asin,
    brand,
    brandid,
    cost,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    sku,
    replenishment_plan,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run
  FROM _Everything_else
  UNION ALL
  SELECT
    CAST(po_approved AS DOUBLE) AS po_approved,
    CAST(po_invoiced AS DOUBLE) AS po_invoiced,
    CAST(po_processed AS DOUBLE) AS po_processed,
    CAST(po_received AS DOUBLE) AS po_received,
    CAST(afn_fulfillable_quantity AS DOUBLE) AS afn_fulfillable_quantity,
    CAST(afn_researching_quantity AS DOUBLE) AS afn_researching_quantity,
    CAST(afn_unsellable_quantity AS DOUBLE) AS afn_unsellable_quantity,
    amazon_seller_id,
    asin,
    brand,
    brandid,
    cost,
    CAST(inbound_checked_in AS DOUBLE) AS inbound_checked_in,
    CAST(inbound_delivered AS DOUBLE) AS inbound_delivered,
    CAST(inbound_in_transit AS DOUBLE) AS inbound_in_transit,
    CAST(inbound_receiving AS DOUBLE) AS inbound_receiving,
    CAST(inbound_shipped AS DOUBLE) AS inbound_shipped,
    CAST(inbound_working AS DOUBLE) AS inbound_working,
    CAST(inv_age_0_to_90_days AS DOUBLE) AS inv_age_0_to_90_days,
    CAST(inv_age_181_to_270_days AS DOUBLE) AS inv_age_181_to_270_days,
    CAST(inv_age_271_to_365_days AS DOUBLE) AS inv_age_271_to_365_days,
    CAST(inv_age_365_plus_days AS DOUBLE) AS inv_age_365_plus_days,
    CAST(inv_age_91_to_180_days AS DOUBLE) AS inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    CAST(reserved_customerorders AS DOUBLE) AS reserved_customerorders,
    CAST(reserved_fc_processing AS DOUBLE) AS reserved_fc_processing,
    CAST(reserved_fc_transfers AS DOUBLE) AS reserved_fc_transfers,
    sku,
    replenishment_plan,
    submitted_date,
    imported_at,
    updated_at,
    batch_id,
    batch_last_run
  FROM _Add_0_to_dup_rows
), _ASIN_MFN_FBA_Flags AS (
  SELECT
    asin,
    SUM(has_mfn) AS has_mfn,
    SUM(has_fba) AS has_fba
  FROM _Group_for_Distinct
  GROUP BY
    asin
), _MFN_Only_ASINs AS (
  SELECT
    *
  FROM _ASIN_MFN_FBA_Flags
  WHERE
    (
      has_mfn >= '1' AND has_fba = '0'
    )
), _FF_Join_to_MFN_FF_ASINs AS (
  SELECT
    _FF.asin,
    _FF.created_at,
    _FF.id,
    _FF.local_sku_inventory,
    _FF.local_upc_inventory,
    _FF.ns_upc_inventory,
    _FF.past_sales_sku_qty,
    _FF.past_sales_upc_qty,
    _FF.sku,
    _FF.total_past_sales_upc,
    _FF.units_in_listing,
    _FF.upc,
    _FF.upc_percentage,
    _FF.updated_at,
    _FF.firefly_ignore_mfn,
    _FF.batch_id,
    _FF.batch_last_run
  FROM _FF
  INNER JOIN _MFN_Only_ASINs
    ON _FF.asin = _MFN_Only_ASINs.asin
), _Bring_Together AS (
  SELECT
    asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc,
    upc_percentage,
    updated_at,
    firefly_ignore_mfn,
    batch_id,
    batch_last_run
  FROM _Non_FF
  UNION ALL
  SELECT
    asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc,
    upc_percentage,
    updated_at,
    firefly_ignore_mfn,
    batch_id,
    batch_last_run
  FROM _FF_Join_to_MFN_FF_ASINs
), _FBA_and_MFN_local_inventory AS (
  SELECT
    asin,
    sku,
    units_in_listing,
    is_bundle,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    upc,
    id
  FROM _NS_Local_Inventory_by_SKU
  UNION ALL
  SELECT
    asin,
    sku,
    units_in_listing,
    CAST(NULL AS BIGINT) AS is_bundle,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    upc,
    id
  FROM _Bring_Together
), _reordering_local_inventory AS (
  SELECT
    _Clean_Inventory_removing_virtual_tracking_dups.po_approved,
    _Clean_Inventory_removing_virtual_tracking_dups.po_invoiced,
    _Clean_Inventory_removing_virtual_tracking_dups.po_processed,
    _Clean_Inventory_removing_virtual_tracking_dups.po_received,
    _Clean_Inventory_removing_virtual_tracking_dups.afn_fulfillable_quantity,
    _Clean_Inventory_removing_virtual_tracking_dups.afn_researching_quantity,
    _Clean_Inventory_removing_virtual_tracking_dups.afn_unsellable_quantity,
    _Clean_Inventory_removing_virtual_tracking_dups.amazon_seller_id,
    _Clean_Inventory_removing_virtual_tracking_dups.asin,
    _Clean_Inventory_removing_virtual_tracking_dups.brand,
    _Clean_Inventory_removing_virtual_tracking_dups.brandid,
    _Clean_Inventory_removing_virtual_tracking_dups.cost,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_checked_in,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_delivered,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_in_transit,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_receiving,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_shipped,
    _Clean_Inventory_removing_virtual_tracking_dups.inbound_working,
    _Clean_Inventory_removing_virtual_tracking_dups.inv_age_0_to_90_days,
    _Clean_Inventory_removing_virtual_tracking_dups.inv_age_181_to_270_days,
    _Clean_Inventory_removing_virtual_tracking_dups.inv_age_271_to_365_days,
    _Clean_Inventory_removing_virtual_tracking_dups.inv_age_365_plus_days,
    _Clean_Inventory_removing_virtual_tracking_dups.inv_age_91_to_180_days,
    _Clean_Inventory_removing_virtual_tracking_dups.marketplace_id,
    _Clean_Inventory_removing_virtual_tracking_dups.partner,
    _Clean_Inventory_removing_virtual_tracking_dups.partnerid,
    _Clean_Inventory_removing_virtual_tracking_dups.reserved_customerorders,
    _Clean_Inventory_removing_virtual_tracking_dups.reserved_fc_processing,
    _Clean_Inventory_removing_virtual_tracking_dups.reserved_fc_transfers,
    _Clean_Inventory_removing_virtual_tracking_dups.sku,
    _Clean_Inventory_removing_virtual_tracking_dups.replenishment_plan,
    _Clean_Inventory_removing_virtual_tracking_dups.submitted_date,
    _Clean_Inventory_removing_virtual_tracking_dups.imported_at,
    _Clean_Inventory_removing_virtual_tracking_dups.updated_at,
    _Clean_Inventory_removing_virtual_tracking_dups.batch_id,
    _Clean_Inventory_removing_virtual_tracking_dups.batch_last_run,
    _FBA_and_MFN_local_inventory.asin AS asin_local_inventory,
    _FBA_and_MFN_local_inventory.sku AS sku_local_inventory,
    _FBA_and_MFN_local_inventory.units_in_listing,
    _FBA_and_MFN_local_inventory.is_bundle,
    _FBA_and_MFN_local_inventory.local_sku_inventory,
    _FBA_and_MFN_local_inventory.local_upc_inventory,
    _FBA_and_MFN_local_inventory.ns_upc_inventory,
    _FBA_and_MFN_local_inventory.past_sales_sku_qty,
    _FBA_and_MFN_local_inventory.past_sales_upc_qty,
    _FBA_and_MFN_local_inventory.total_past_sales_upc,
    _FBA_and_MFN_local_inventory.upc,
    _FBA_and_MFN_local_inventory.id
  FROM _Clean_Inventory_removing_virtual_tracking_dups
  FULL JOIN _FBA_and_MFN_local_inventory
    ON _Clean_Inventory_removing_virtual_tracking_dups.sku = _FBA_and_MFN_local_inventory.sku
    AND _Clean_Inventory_removing_virtual_tracking_dups.asin = _FBA_and_MFN_local_inventory.asin
), _Incorporate_Local_Only AS (
  SELECT
    units_in_listing,
    is_bundle,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    upc,
    id,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    amazon_seller_id,
    asin_local_inventory,
    brand,
    brandid,
    cost,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    sku_local_inventory,
    replenishment_plan,
    submitted_date,
    imported_at,
    fba_and_mfn_local_inventory_updated_at,
    ns_local_inventory_by_sku_batch_id,
    ns_local_inventory_by_sku_batch_last_run,
    (
      COALESCE(asin, asin_local_inventory)
    ) AS asin,
    (
      COALESCE(sku, sku_local_inventory)
    ) AS sku
  FROM _reordering_local_inventory
), _Add_NonSellable AS (
  SELECT
    _Incorporate_Local_Only.asin,
    _Incorporate_Local_Only.sku,
    _Incorporate_Local_Only.units_in_listing,
    _Incorporate_Local_Only.is_bundle,
    _Incorporate_Local_Only.local_sku_inventory,
    _Incorporate_Local_Only.local_upc_inventory,
    _Incorporate_Local_Only.ns_upc_inventory,
    _Incorporate_Local_Only.past_sales_sku_qty,
    _Incorporate_Local_Only.past_sales_upc_qty,
    _Incorporate_Local_Only.total_past_sales_upc,
    _Incorporate_Local_Only.upc,
    _Incorporate_Local_Only.id,
    _Incorporate_Local_Only.po_approved,
    _Incorporate_Local_Only.po_invoiced,
    _Incorporate_Local_Only.po_processed,
    _Incorporate_Local_Only.po_received,
    _Incorporate_Local_Only.afn_fulfillable_quantity,
    _Incorporate_Local_Only.afn_researching_quantity,
    _Incorporate_Local_Only.afn_unsellable_quantity,
    _Incorporate_Local_Only.amazon_seller_id,
    _Incorporate_Local_Only.asin_local_inventory,
    _Incorporate_Local_Only.brand,
    _Incorporate_Local_Only.brandid,
    _Incorporate_Local_Only.cost,
    _Incorporate_Local_Only.inbound_checked_in,
    _Incorporate_Local_Only.inbound_delivered,
    _Incorporate_Local_Only.inbound_in_transit,
    _Incorporate_Local_Only.inbound_receiving,
    _Incorporate_Local_Only.inbound_shipped,
    _Incorporate_Local_Only.inbound_working,
    _Incorporate_Local_Only.inv_age_0_to_90_days,
    _Incorporate_Local_Only.inv_age_181_to_270_days,
    _Incorporate_Local_Only.inv_age_271_to_365_days,
    _Incorporate_Local_Only.inv_age_365_plus_days,
    _Incorporate_Local_Only.inv_age_91_to_180_days,
    _Incorporate_Local_Only.marketplace_id,
    _Incorporate_Local_Only.partner,
    _Incorporate_Local_Only.partnerid,
    _Incorporate_Local_Only.reserved_customerorders,
    _Incorporate_Local_Only.reserved_fc_processing,
    _Incorporate_Local_Only.reserved_fc_transfers,
    _Incorporate_Local_Only.sku_local_inventory,
    _Incorporate_Local_Only.replenishment_plan,
    _Incorporate_Local_Only.submitted_date,
    _Incorporate_Local_Only.imported_at,
    _Incorporate_Local_Only.fba_and_mfn_local_inventory_updated_at,
    _Incorporate_Local_Only.ns_local_inventory_by_sku_batch_id,
    _Incorporate_Local_Only.ns_local_inventory_by_sku_batch_last_run,
    _ns_nonsellable_inventory_by_sku.local_sku_inventory AS nonsellable_sku_inventory,
    _ns_nonsellable_inventory_by_sku.local_upc_inventory AS nonsellable_upc_inventory,
    _ns_nonsellable_inventory_by_sku.upc AS upc_local_inventory
  FROM _Incorporate_Local_Only
  FULL JOIN _ns_nonsellable_inventory_by_sku
    ON _Incorporate_Local_Only.sku = _ns_nonsellable_inventory_by_sku.sku
    AND _Incorporate_Local_Only.asin = _ns_nonsellable_inventory_by_sku.asin
    AND _Incorporate_Local_Only.upc = _ns_nonsellable_inventory_by_sku.upc
), _Incorporate_Nonsellable_only_inventory AS (
  SELECT
    asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    sku,
    total_past_sales_upc,
    units_in_listing,
    upc_percentage,
    updated_at,
    batch_id,
    batch_last_run,
    is_bundle,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    amazon_seller_id,
    asin_local_inventory,
    brand,
    brandid,
    cost,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    sku_local_inventory,
    replenishment_plan,
    submitted_date,
    imported_at,
    fba_and_mfn_local_inventory_updated_at,
    ns_local_inventory_by_sku_batch_id,
    ns_local_inventory_by_sku_batch_last_run,
    (
      COALESCE(upc, upc_local_inventory)
    ) AS upc
  FROM _Add_NonSellable
), _inventory_POs_by_SKU AS (
  SELECT
    _Incorporate_Nonsellable_only_inventory.asin,
    _Incorporate_Nonsellable_only_inventory.created_at,
    _Incorporate_Nonsellable_only_inventory.id,
    _Incorporate_Nonsellable_only_inventory.local_sku_inventory,
    _Incorporate_Nonsellable_only_inventory.local_upc_inventory,
    _Incorporate_Nonsellable_only_inventory.ns_upc_inventory,
    _Incorporate_Nonsellable_only_inventory.past_sales_sku_qty,
    _Incorporate_Nonsellable_only_inventory.past_sales_upc_qty,
    _Incorporate_Nonsellable_only_inventory.sku,
    _Incorporate_Nonsellable_only_inventory.total_past_sales_upc,
    _Incorporate_Nonsellable_only_inventory.units_in_listing,
    _Incorporate_Nonsellable_only_inventory.upc,
    _Incorporate_Nonsellable_only_inventory.upc_percentage,
    _Incorporate_Nonsellable_only_inventory.updated_at,
    _Incorporate_Nonsellable_only_inventory.batch_id,
    _Incorporate_Nonsellable_only_inventory.batch_last_run,
    _Incorporate_Nonsellable_only_inventory.is_bundle,
    _Incorporate_Nonsellable_only_inventory.nonsellable_sku_inventory,
    _Incorporate_Nonsellable_only_inventory.nonsellable_upc_inventory,
    _Incorporate_Nonsellable_only_inventory.upc_local_inventory,
    _Incorporate_Nonsellable_only_inventory.po_approved,
    _Incorporate_Nonsellable_only_inventory.po_invoiced,
    _Incorporate_Nonsellable_only_inventory.po_processed,
    _Incorporate_Nonsellable_only_inventory.po_received,
    _Incorporate_Nonsellable_only_inventory.afn_fulfillable_quantity,
    _Incorporate_Nonsellable_only_inventory.afn_researching_quantity,
    _Incorporate_Nonsellable_only_inventory.afn_unsellable_quantity,
    _Incorporate_Nonsellable_only_inventory.amazon_seller_id,
    _Incorporate_Nonsellable_only_inventory.asin_local_inventory,
    _Incorporate_Nonsellable_only_inventory.brand,
    _Incorporate_Nonsellable_only_inventory.brandid,
    _Incorporate_Nonsellable_only_inventory.cost,
    _Incorporate_Nonsellable_only_inventory.inbound_checked_in,
    _Incorporate_Nonsellable_only_inventory.inbound_delivered,
    _Incorporate_Nonsellable_only_inventory.inbound_in_transit,
    _Incorporate_Nonsellable_only_inventory.inbound_receiving,
    _Incorporate_Nonsellable_only_inventory.inbound_shipped,
    _Incorporate_Nonsellable_only_inventory.inbound_working,
    _Incorporate_Nonsellable_only_inventory.inv_age_0_to_90_days,
    _Incorporate_Nonsellable_only_inventory.inv_age_181_to_270_days,
    _Incorporate_Nonsellable_only_inventory.inv_age_271_to_365_days,
    _Incorporate_Nonsellable_only_inventory.inv_age_365_plus_days,
    _Incorporate_Nonsellable_only_inventory.inv_age_91_to_180_days,
    _Incorporate_Nonsellable_only_inventory.marketplace_id,
    _Incorporate_Nonsellable_only_inventory.partner,
    _Incorporate_Nonsellable_only_inventory.partnerid,
    _Incorporate_Nonsellable_only_inventory.reserved_customerorders,
    _Incorporate_Nonsellable_only_inventory.reserved_fc_processing,
    _Incorporate_Nonsellable_only_inventory.reserved_fc_transfers,
    _Incorporate_Nonsellable_only_inventory.sku_local_inventory,
    _Incorporate_Nonsellable_only_inventory.replenishment_plan,
    _Incorporate_Nonsellable_only_inventory.submitted_date,
    _Incorporate_Nonsellable_only_inventory.imported_at,
    _Incorporate_Nonsellable_only_inventory.fba_and_mfn_local_inventory_updated_at,
    _Incorporate_Nonsellable_only_inventory.ns_local_inventory_by_sku_batch_id,
    _Incorporate_Nonsellable_only_inventory.ns_local_inventory_by_sku_batch_last_run,
    _Group_By.asin AS ns_po_qty_by_sku_asin,
    _Group_By.upc AS ns_po_qty_by_sku_upc,
    _Group_By.sku AS ns_po_qty_by_sku_sku,
    _Group_By.po_sku_inventory,
    _Group_By.po_upc_inventory,
    _Group_By.ns_upc_qty,
    _Group_By.ns_upc_fulfilled
  FROM _Incorporate_Nonsellable_only_inventory
  FULL JOIN _Group_By
    ON _Incorporate_Nonsellable_only_inventory.asin = _Group_By.asin
    AND _Incorporate_Nonsellable_only_inventory.upc = _Group_By.upc
    AND _Incorporate_Nonsellable_only_inventory.sku = _Group_By.sku
), _Incorporate_PO_only_inventory AS (
  SELECT
    sku,
    po_sku_inventory,
    po_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    ns_po_qty_by_sku_asin,
    created_at,
    id,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    ns_po_qty_by_sku_sku,
    total_past_sales_upc,
    units_in_listing,
    ns_po_qty_by_sku_upc,
    upc_percentage,
    updated_at,
    batch_id,
    batch_last_run,
    is_bundle,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    amazon_seller_id,
    asin_local_inventory,
    brand,
    brandid,
    cost,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    marketplace_id,
    partner,
    partnerid,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    sku_local_inventory,
    replenishment_plan,
    submitted_date,
    imported_at,
    fba_and_mfn_local_inventory_updated_at,
    ns_local_inventory_by_sku_batch_id,
    ns_local_inventory_by_sku_batch_last_run,
    (
      COALESCE(asin, ns_po_qty_by_sku_asin)
    ) AS asin,
    (
      COALESCE(upc, ns_po_qty_by_sku_upc)
    ) AS upc
  FROM _inventory_POs_by_SKU
), _Join_Data_1 AS (
  SELECT
    _Incorporate_PO_only_inventory.asin,
    _Incorporate_PO_only_inventory.upc,
    _Incorporate_PO_only_inventory.sku,
    _Incorporate_PO_only_inventory.po_sku_inventory,
    _Incorporate_PO_only_inventory.po_upc_inventory,
    _Incorporate_PO_only_inventory.ns_upc_qty,
    _Incorporate_PO_only_inventory.ns_upc_fulfilled,
    _Incorporate_PO_only_inventory.ns_po_qty_by_sku_asin,
    _Incorporate_PO_only_inventory.created_at,
    _Incorporate_PO_only_inventory.id,
    _Incorporate_PO_only_inventory.local_sku_inventory,
    _Incorporate_PO_only_inventory.local_upc_inventory,
    _Incorporate_PO_only_inventory.ns_upc_inventory,
    _Incorporate_PO_only_inventory.past_sales_sku_qty,
    _Incorporate_PO_only_inventory.past_sales_upc_qty,
    _Incorporate_PO_only_inventory.ns_po_qty_by_sku_sku,
    _Incorporate_PO_only_inventory.total_past_sales_upc,
    _Incorporate_PO_only_inventory.units_in_listing,
    _Incorporate_PO_only_inventory.ns_po_qty_by_sku_upc,
    _Incorporate_PO_only_inventory.upc_percentage,
    _Incorporate_PO_only_inventory.updated_at,
    _Incorporate_PO_only_inventory.batch_id,
    _Incorporate_PO_only_inventory.batch_last_run,
    _Incorporate_PO_only_inventory.is_bundle,
    _Incorporate_PO_only_inventory.nonsellable_sku_inventory,
    _Incorporate_PO_only_inventory.nonsellable_upc_inventory,
    _Incorporate_PO_only_inventory.upc_local_inventory,
    _Incorporate_PO_only_inventory.po_approved,
    _Incorporate_PO_only_inventory.po_invoiced,
    _Incorporate_PO_only_inventory.po_processed,
    _Incorporate_PO_only_inventory.po_received,
    _Incorporate_PO_only_inventory.afn_fulfillable_quantity,
    _Incorporate_PO_only_inventory.afn_researching_quantity,
    _Incorporate_PO_only_inventory.afn_unsellable_quantity,
    _Incorporate_PO_only_inventory.amazon_seller_id,
    _Incorporate_PO_only_inventory.asin_local_inventory,
    _Incorporate_PO_only_inventory.brand,
    _Incorporate_PO_only_inventory.brandid,
    _Incorporate_PO_only_inventory.cost,
    _Incorporate_PO_only_inventory.inbound_checked_in,
    _Incorporate_PO_only_inventory.inbound_delivered,
    _Incorporate_PO_only_inventory.inbound_in_transit,
    _Incorporate_PO_only_inventory.inbound_receiving,
    _Incorporate_PO_only_inventory.inbound_shipped,
    _Incorporate_PO_only_inventory.inbound_working,
    _Incorporate_PO_only_inventory.inv_age_0_to_90_days,
    _Incorporate_PO_only_inventory.inv_age_181_to_270_days,
    _Incorporate_PO_only_inventory.inv_age_271_to_365_days,
    _Incorporate_PO_only_inventory.inv_age_365_plus_days,
    _Incorporate_PO_only_inventory.inv_age_91_to_180_days,
    _Incorporate_PO_only_inventory.marketplace_id,
    _Incorporate_PO_only_inventory.partner,
    _Incorporate_PO_only_inventory.partnerid,
    _Incorporate_PO_only_inventory.reserved_customerorders,
    _Incorporate_PO_only_inventory.reserved_fc_processing,
    _Incorporate_PO_only_inventory.reserved_fc_transfers,
    _Incorporate_PO_only_inventory.sku_local_inventory,
    _Incorporate_PO_only_inventory.replenishment_plan,
    _Incorporate_PO_only_inventory.submitted_date,
    _Incorporate_PO_only_inventory.imported_at,
    _Incorporate_PO_only_inventory.fba_and_mfn_local_inventory_updated_at,
    _Incorporate_PO_only_inventory.ns_local_inventory_by_sku_batch_id,
    _Incorporate_PO_only_inventory.ns_local_inventory_by_sku_batch_last_run,
    _Add_Formula_1.created_at,
    _Add_Formula_1.description,
    _Add_Formula_1.name,
    _Add_Formula_1.product_id,
    _Add_Formula_1.quantity_available_to_promise,
    _Add_Formula_1.quantity_on_hand,
    _Add_Formula_1.clean_sku
  FROM _Incorporate_PO_only_inventory
  LEFT JOIN _Add_Formula_1
    ON _Incorporate_PO_only_inventory.amazon_seller_id = _Add_Formula_1.amazon_seller_id
    AND _Incorporate_PO_only_inventory.marketplace_id = _Add_Formula_1.country_id
), _Select_Columns AS (
  SELECT
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    po_sku_inventory,
    po_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    upc AS ns_local_upc,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    marketplace_id,
    submitted_date,
    imported_at,
    updated_at,
    asin_local_inventory,
    sku_local_inventory,
    ns_po_qty_by_sku_asin,
    ns_po_qty_by_sku_upc,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    brandid,
    partnerid,
    batch_id,
    batch_last_run,
    id,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    units_in_listing,
    replenishment_plan,
    quantity_available_to_promise AS ware2go_available_qty,
    quantity_on_hand AS ware2go_on_hand_qty
  FROM _Join_Data_1
), _Validating_Null_Values AS (
  SELECT
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    ns_local_upc,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    marketplace_id,
    submitted_date,
    imported_at,
    updated_at,
    asin_local_inventory,
    sku_local_inventory,
    ns_po_qty_by_sku_asin,
    ns_po_qty_by_sku_upc,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    brandid,
    partnerid,
    batch_id,
    batch_last_run,
    id,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    units_in_listing,
    ware2go_available_qty,
    (
      COALESCE(local_sku_inventory, 0)
    ) AS local_sku_inventory,
    (
      COALESCE(po_sku_inventory, 0)
    ) AS po_sku_inventory,
    (
      COALESCE(ns_upc_qty, 0)
    ) AS ns_upc_qty,
    (
      COALESCE(po_upc_inventory, 0)
    ) AS po_upc_inventory,
    (
      ROUND(
        afn_fulfillable_quantity + afn_researching_quantity + afn_unsellable_quantity + reserved_customerorders + reserved_fc_processing + reserved_fc_transfers + inbound_checked_in + inbound_delivered + inbound_in_transit + inbound_receiving + inbound_shipped + inbound_working + local_sku_inventory
      )
    ) AS total_inventory,
    (
      COALESCE(ns_upc_fulfilled, 0)
    ) AS ns_upc_fulfilled,
    (
      COALESCE(replenishment_plan, 0)
    ) AS replenishment_plan,
    (
      COALESCE(ware2go_available_qty, 0)
    ) AS ware2go_available_qty,
    (
      COALESCE(ware2go_on_hand_qty, 0)
    ) AS ware2go_on_hand_qty
  FROM _Select_Columns
), _Add_seller_name AS (
  SELECT
    _amazon_seller_central_accounts.created_at,
    _amazon_seller_central_accounts.enable_report_gathering,
    _amazon_seller_central_accounts.end_date,
    _amazon_seller_central_accounts.id,
    _amazon_seller_central_accounts.market_place_id AS seller_central_account_marketplace_id,
    _amazon_seller_central_accounts.merchant_id,
    _amazon_seller_central_accounts.name,
    _amazon_seller_central_accounts.secret_access_key,
    _amazon_seller_central_accounts.selling_partner_id,
    _amazon_seller_central_accounts.start_date,
    _amazon_seller_central_accounts.batch_id,
    _amazon_seller_central_accounts.batch_last_run,
    _Validating_Null_Values.asin,
    _Validating_Null_Values.sku,
    _Validating_Null_Values.amazon_seller_id,
    _Validating_Null_Values.partner,
    _Validating_Null_Values.brand,
    _Validating_Null_Values.local_sku_inventory,
    _Validating_Null_Values.local_upc_inventory,
    _Validating_Null_Values.ns_upc_qty,
    _Validating_Null_Values.ns_upc_fulfilled,
    _Validating_Null_Values.po_sku_inventory,
    _Validating_Null_Values.po_upc_inventory,
    _Validating_Null_Values.afn_fulfillable_quantity,
    _Validating_Null_Values.afn_researching_quantity,
    _Validating_Null_Values.afn_unsellable_quantity,
    _Validating_Null_Values.reserved_customerorders,
    _Validating_Null_Values.reserved_fc_transfers,
    _Validating_Null_Values.reserved_fc_processing,
    _Validating_Null_Values.inbound_receiving,
    _Validating_Null_Values.inbound_checked_in,
    _Validating_Null_Values.inbound_delivered,
    _Validating_Null_Values.inbound_in_transit,
    _Validating_Null_Values.inbound_shipped,
    _Validating_Null_Values.inbound_working,
    _Validating_Null_Values.cost,
    _Validating_Null_Values.inv_age_0_to_90_days,
    _Validating_Null_Values.inv_age_91_to_180_days,
    _Validating_Null_Values.inv_age_181_to_270_days,
    _Validating_Null_Values.inv_age_271_to_365_days,
    _Validating_Null_Values.inv_age_365_plus_days,
    _Validating_Null_Values.ns_local_upc,
    _Validating_Null_Values.nonsellable_sku_inventory,
    _Validating_Null_Values.nonsellable_upc_inventory,
    _Validating_Null_Values.marketplace_id,
    _Validating_Null_Values.submitted_date,
    _Validating_Null_Values.imported_at,
    _Validating_Null_Values.updated_at,
    _Validating_Null_Values.asin_local_inventory,
    _Validating_Null_Values.sku_local_inventory,
    _Validating_Null_Values.ns_po_qty_by_sku_asin,
    _Validating_Null_Values.ns_po_qty_by_sku_upc,
    _Validating_Null_Values.upc_local_inventory,
    _Validating_Null_Values.po_approved,
    _Validating_Null_Values.po_invoiced,
    _Validating_Null_Values.po_processed,
    _Validating_Null_Values.po_received,
    _Validating_Null_Values.brandid,
    _Validating_Null_Values.partnerid,
    _Validating_Null_Values.batch_id AS validating_null_values_batch_id,
    _Validating_Null_Values.batch_last_run AS validating_null_values_batch_last_run,
    _Validating_Null_Values.id AS validating_null_values_id,
    _Validating_Null_Values.ns_upc_inventory,
    _Validating_Null_Values.past_sales_sku_qty,
    _Validating_Null_Values.past_sales_upc_qty,
    _Validating_Null_Values.total_past_sales_upc,
    _Validating_Null_Values.units_in_listing,
    _Validating_Null_Values.replenishment_plan,
    _Validating_Null_Values.ware2go_available_qty,
    _Validating_Null_Values.ware2go_on_hand_qty,
    _Validating_Null_Values.total_inventory,
    _Validating_Null_Values.ware2go_available_qty
  FROM _amazon_seller_central_accounts
  INNER JOIN _Validating_Null_Values
    ON _amazon_seller_central_accounts.id = _Validating_Null_Values.amazon_seller_id
), _Join_Data AS (
  SELECT
    _Add_seller_name.created_at,
    _Add_seller_name.enable_report_gathering,
    _Add_seller_name.end_date,
    _Add_seller_name.id,
    _Add_seller_name.seller_central_account_marketplace_id,
    _Add_seller_name.merchant_id,
    _Add_seller_name.name,
    _Add_seller_name.secret_access_key,
    _Add_seller_name.selling_partner_id,
    _Add_seller_name.start_date,
    _Add_seller_name.batch_id,
    _Add_seller_name.batch_last_run,
    _Add_seller_name.asin,
    _Add_seller_name.sku,
    _Add_seller_name.amazon_seller_id,
    _Add_seller_name.partner,
    _Add_seller_name.brand,
    _Add_seller_name.local_sku_inventory,
    _Add_seller_name.local_upc_inventory,
    _Add_seller_name.ns_upc_qty,
    _Add_seller_name.ns_upc_fulfilled,
    _Add_seller_name.po_sku_inventory,
    _Add_seller_name.po_upc_inventory,
    _Add_seller_name.afn_fulfillable_quantity,
    _Add_seller_name.afn_researching_quantity,
    _Add_seller_name.afn_unsellable_quantity,
    _Add_seller_name.reserved_customerorders,
    _Add_seller_name.reserved_fc_transfers,
    _Add_seller_name.reserved_fc_processing,
    _Add_seller_name.inbound_receiving,
    _Add_seller_name.inbound_checked_in,
    _Add_seller_name.inbound_delivered,
    _Add_seller_name.inbound_in_transit,
    _Add_seller_name.inbound_shipped,
    _Add_seller_name.inbound_working,
    _Add_seller_name.cost,
    _Add_seller_name.inv_age_0_to_90_days,
    _Add_seller_name.inv_age_91_to_180_days,
    _Add_seller_name.inv_age_181_to_270_days,
    _Add_seller_name.inv_age_271_to_365_days,
    _Add_seller_name.inv_age_365_plus_days,
    _Add_seller_name.ns_local_upc,
    _Add_seller_name.nonsellable_sku_inventory,
    _Add_seller_name.nonsellable_upc_inventory,
    _Add_seller_name.marketplace_id,
    _Add_seller_name.submitted_date,
    _Add_seller_name.imported_at,
    _Add_seller_name.updated_at,
    _Add_seller_name.asin_local_inventory,
    _Add_seller_name.sku_local_inventory,
    _Add_seller_name.ns_po_qty_by_sku_asin,
    _Add_seller_name.ns_po_qty_by_sku_upc,
    _Add_seller_name.upc_local_inventory,
    _Add_seller_name.po_approved,
    _Add_seller_name.po_invoiced,
    _Add_seller_name.po_processed,
    _Add_seller_name.po_received,
    _Add_seller_name.brandid,
    _Add_seller_name.partnerid,
    _Add_seller_name.validating_null_values_batch_id,
    _Add_seller_name.validating_null_values_batch_last_run,
    _Add_seller_name.validating_null_values_id,
    _Add_seller_name.ns_upc_inventory,
    _Add_seller_name.past_sales_sku_qty,
    _Add_seller_name.past_sales_upc_qty,
    _Add_seller_name.total_past_sales_upc,
    _Add_seller_name.units_in_listing,
    _Add_seller_name.replenishment_plan,
    _Add_seller_name.ware2go_available_qty,
    _Add_seller_name.ware2go_on_hand_qty,
    _Add_seller_name.total_inventory,
    _Add_seller_name.ware2go_available_qty,
    _Remove_Duplicates.sku_name,
    _Remove_Duplicates.sku_upc,
    _Remove_Duplicates.country_id,
    _Remove_Duplicates.asin AS filter_rows_asin,
    _Remove_Duplicates.amazon_seller_id AS remove_duplicates_amazon_seller_id,
    _Remove_Duplicates.is_preferred_sku_by_asin,
    _Remove_Duplicates.sku_reorder_status,
    _Remove_Duplicates.units_in_listing AS remove_duplicates_units_in_listing,
    _Remove_Duplicates.is_bundle
  FROM _Add_seller_name
  LEFT JOIN _Remove_Duplicates
    ON _Add_seller_name.sku = _Remove_Duplicates.sku
    AND _Add_seller_name.marketplace_id = _Remove_Duplicates.country_id
    AND _Add_seller_name.amazon_seller_id = _Remove_Duplicates.amazon_seller_id
), _Obtain_country_id_from_marketplace_id AS (
  SELECT
    created_at,
    enable_report_gathering,
    end_date,
    id,
    seller_central_account_marketplace_id,
    merchant_id,
    name,
    secret_access_key,
    selling_partner_id,
    start_date,
    batch_id,
    batch_last_run,
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    po_sku_inventory,
    po_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    ns_local_upc,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    marketplace_id,
    submitted_date,
    imported_at,
    updated_at,
    asin_local_inventory,
    sku_local_inventory,
    ns_po_qty_by_sku_asin,
    ns_po_qty_by_sku_upc,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    brandid,
    partnerid,
    validating_null_values_batch_id,
    validating_null_values_batch_last_run,
    validating_null_values_id,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    replenishment_plan,
    ware2go_available_qty,
    ware2go_on_hand_qty,
    total_inventory,
    ware2go_available_qty,
    sku_name,
    sku_upc,
    filter_rows_asin,
    remove_duplicates_amazon_seller_id,
    is_preferred_sku_by_asin,
    sku_reorder_status,
    remove_duplicates_units_in_listing,
    is_bundle,
    (
      COALESCE(marketplace_id, country_id)
    ) AS country_id,
    (
      COALESCE(remove_duplicates_units_in_listing, units_in_listing)
    ) AS units_in_listing
  FROM _Join_Data
), _Add_Countries AS (
  SELECT
    _Obtain_country_id_from_marketplace_id.created_at,
    _Obtain_country_id_from_marketplace_id.enable_report_gathering,
    _Obtain_country_id_from_marketplace_id.end_date,
    _Obtain_country_id_from_marketplace_id.id,
    _Obtain_country_id_from_marketplace_id.seller_central_account_marketplace_id,
    _Obtain_country_id_from_marketplace_id.merchant_id,
    _Obtain_country_id_from_marketplace_id.name,
    _Obtain_country_id_from_marketplace_id.secret_access_key,
    _Obtain_country_id_from_marketplace_id.selling_partner_id,
    _Obtain_country_id_from_marketplace_id.start_date,
    _Obtain_country_id_from_marketplace_id.batch_id,
    _Obtain_country_id_from_marketplace_id.batch_last_run,
    _Obtain_country_id_from_marketplace_id.asin,
    _Obtain_country_id_from_marketplace_id.sku,
    _Obtain_country_id_from_marketplace_id.amazon_seller_id,
    _Obtain_country_id_from_marketplace_id.partner,
    _Obtain_country_id_from_marketplace_id.brand,
    _Obtain_country_id_from_marketplace_id.local_sku_inventory,
    _Obtain_country_id_from_marketplace_id.local_upc_inventory,
    _Obtain_country_id_from_marketplace_id.ns_upc_qty,
    _Obtain_country_id_from_marketplace_id.ns_upc_fulfilled,
    _Obtain_country_id_from_marketplace_id.po_sku_inventory,
    _Obtain_country_id_from_marketplace_id.po_upc_inventory,
    _Obtain_country_id_from_marketplace_id.afn_fulfillable_quantity,
    _Obtain_country_id_from_marketplace_id.afn_researching_quantity,
    _Obtain_country_id_from_marketplace_id.afn_unsellable_quantity,
    _Obtain_country_id_from_marketplace_id.reserved_customerorders,
    _Obtain_country_id_from_marketplace_id.reserved_fc_transfers,
    _Obtain_country_id_from_marketplace_id.reserved_fc_processing,
    _Obtain_country_id_from_marketplace_id.inbound_receiving,
    _Obtain_country_id_from_marketplace_id.inbound_checked_in,
    _Obtain_country_id_from_marketplace_id.inbound_delivered,
    _Obtain_country_id_from_marketplace_id.inbound_in_transit,
    _Obtain_country_id_from_marketplace_id.inbound_shipped,
    _Obtain_country_id_from_marketplace_id.inbound_working,
    _Obtain_country_id_from_marketplace_id.cost,
    _Obtain_country_id_from_marketplace_id.inv_age_0_to_90_days,
    _Obtain_country_id_from_marketplace_id.inv_age_91_to_180_days,
    _Obtain_country_id_from_marketplace_id.inv_age_181_to_270_days,
    _Obtain_country_id_from_marketplace_id.inv_age_271_to_365_days,
    _Obtain_country_id_from_marketplace_id.inv_age_365_plus_days,
    _Obtain_country_id_from_marketplace_id.ns_local_upc,
    _Obtain_country_id_from_marketplace_id.nonsellable_sku_inventory,
    _Obtain_country_id_from_marketplace_id.nonsellable_upc_inventory,
    _Obtain_country_id_from_marketplace_id.marketplace_id,
    _Obtain_country_id_from_marketplace_id.submitted_date,
    _Obtain_country_id_from_marketplace_id.imported_at,
    _Obtain_country_id_from_marketplace_id.updated_at,
    _Obtain_country_id_from_marketplace_id.asin_local_inventory,
    _Obtain_country_id_from_marketplace_id.sku_local_inventory,
    _Obtain_country_id_from_marketplace_id.ns_po_qty_by_sku_asin,
    _Obtain_country_id_from_marketplace_id.ns_po_qty_by_sku_upc,
    _Obtain_country_id_from_marketplace_id.upc_local_inventory,
    _Obtain_country_id_from_marketplace_id.po_approved,
    _Obtain_country_id_from_marketplace_id.po_invoiced,
    _Obtain_country_id_from_marketplace_id.po_processed,
    _Obtain_country_id_from_marketplace_id.po_received,
    _Obtain_country_id_from_marketplace_id.brandid,
    _Obtain_country_id_from_marketplace_id.partnerid,
    _Obtain_country_id_from_marketplace_id.validating_null_values_batch_id,
    _Obtain_country_id_from_marketplace_id.validating_null_values_batch_last_run,
    _Obtain_country_id_from_marketplace_id.validating_null_values_id,
    _Obtain_country_id_from_marketplace_id.ns_upc_inventory,
    _Obtain_country_id_from_marketplace_id.past_sales_sku_qty,
    _Obtain_country_id_from_marketplace_id.past_sales_upc_qty,
    _Obtain_country_id_from_marketplace_id.total_past_sales_upc,
    _Obtain_country_id_from_marketplace_id.units_in_listing,
    _Obtain_country_id_from_marketplace_id.replenishment_plan,
    _Obtain_country_id_from_marketplace_id.ware2go_available_qty,
    _Obtain_country_id_from_marketplace_id.ware2go_on_hand_qty,
    _Obtain_country_id_from_marketplace_id.total_inventory,
    _Obtain_country_id_from_marketplace_id.ware2go_available_qty,
    _Obtain_country_id_from_marketplace_id.sku_name,
    _Obtain_country_id_from_marketplace_id.sku_upc,
    _Obtain_country_id_from_marketplace_id.country_id,
    _Obtain_country_id_from_marketplace_id.filter_rows_asin,
    _Obtain_country_id_from_marketplace_id.remove_duplicates_amazon_seller_id,
    _Obtain_country_id_from_marketplace_id.is_preferred_sku_by_asin,
    _Obtain_country_id_from_marketplace_id.sku_reorder_status,
    _Obtain_country_id_from_marketplace_id.remove_duplicates_units_in_listing,
    _Obtain_country_id_from_marketplace_id.is_bundle,
    _countries.created_at AS countries_created_at,
    _countries.currency,
    _countries.enabled,
    _countries.id AS countries_id,
    _countries.marketplace_id AS countries_marketplace_id,
    _countries.name AS countries_name,
    _countries.sales_channel,
    _countries.short_name,
    _countries.updated_at AS countries_updated_at
  FROM _Obtain_country_id_from_marketplace_id
  INNER JOIN _countries
    ON _Obtain_country_id_from_marketplace_id.marketplace_id = _countries.id
), _Validate_UPC AS (
  SELECT
    created_at,
    currency,
    enabled,
    id,
    marketplace_id,
    name,
    sales_channel,
    short_name,
    updated_at,
    batch_id,
    batch_last_run,
    countries_created_at,
    enable_report_gathering,
    end_date,
    countries_id,
    seller_central_account_marketplace_id,
    merchant_id,
    countries_name,
    secret_access_key,
    selling_partner_id,
    start_date,
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    po_sku_inventory,
    po_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    ns_local_upc,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    countries_marketplace_id,
    submitted_date,
    imported_at,
    countries_updated_at,
    asin_local_inventory,
    sku_local_inventory,
    ns_po_qty_by_sku_asin,
    ns_po_qty_by_sku_upc,
    upc_local_inventory,
    po_approved,
    po_invoiced,
    po_processed,
    po_received,
    brandid,
    partnerid,
    validating_null_values_batch_id,
    validating_null_values_batch_last_run,
    validating_null_values_id,
    ns_upc_inventory,
    past_sales_sku_qty,
    past_sales_upc_qty,
    total_past_sales_upc,
    units_in_listing,
    replenishment_plan,
    ware2go_available_qty,
    ware2go_on_hand_qty,
    total_inventory,
    ware2go_available_qty,
    sku_name,
    sku_upc,
    country_id,
    filter_rows_asin,
    remove_duplicates_amazon_seller_id,
    is_preferred_sku_by_asin,
    sku_reorder_status,
    remove_duplicates_units_in_listing,
    is_bundle,
    (
      COALESCE(ns_local_upc, sku_upc)
    ) AS upc
  FROM _Add_Countries
), _Remove_extra_UPC_columns AS (
  SELECT
    enable_report_gathering,
    end_date,
    id,
    marketplace_id AS market_place_id,
    merchant_id,
    name,
    secret_access_key,
    start_date,
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    po_sku_inventory,
    po_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    total_inventory,
    sku_name,
    upc,
    countries_name AS country,
    country_id,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    countries_marketplace_id,
    submitted_date,
    imported_at,
    updated_at,
    is_preferred_sku_by_asin,
    sku_reorder_status,
    units_in_listing,
    is_bundle,
    replenishment_plan,
    ware2go_available_qty AS ware2go_available_qty,
    ware2go_on_hand_qty
  FROM _Validate_UPC
), _Add_new_country_id_20_for_Europe AS (
  SELECT
    enable_report_gathering,
    end_date,
    id,
    market_place_id,
    merchant_id,
    name,
    secret_access_key,
    start_date,
    asin,
    sku,
    amazon_seller_id,
    partner,
    brand,
    local_sku_inventory,
    local_upc_inventory,
    ns_upc_qty,
    ns_upc_fulfilled,
    po_sku_inventory,
    po_upc_inventory,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    cost,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    total_inventory,
    sku_name,
    upc,
    country,
    country_id,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    countries_marketplace_id,
    submitted_date,
    imported_at,
    updated_at,
    is_preferred_sku_by_asin,
    sku_reorder_status,
    units_in_listing,
    is_bundle,
    replenishment_plan,
    ware2go_available_qty,
    ware2go_on_hand_qty,
    (
      CASE
        WHEN LOWER(sku) LIKE '%eu_fba%' AND amazon_seller_id = 3
        THEN 'PanEU'
        ELSE country
      END
    ) AS country_or_paneu,
    (
      CASE
        WHEN LOWER(sku) LIKE '%eu_fba%' AND amazon_seller_id = 3
        THEN 20
        ELSE country_id
      END
    ) AS new_country_id
  FROM _Remove_extra_UPC_columns
), _Group_by_SKU_Inventory_Formula AS (
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    MAX(afn_fulfillable_quantity) AS afn_fulfillable_quantity,
    MAX(afn_researching_quantity) AS afn_researching_quantity,
    MAX(afn_unsellable_quantity) AS afn_unsellable_quantity,
    MAX(reserved_customerorders) AS reserved_customerorders,
    MAX(reserved_fc_transfers) AS reserved_fc_transfers,
    MAX(reserved_fc_processing) AS reserved_fc_processing,
    MAX(inbound_receiving) AS inbound_receiving,
    MAX(inbound_checked_in) AS inbound_checked_in,
    MAX(inbound_delivered) AS inbound_delivered,
    MAX(inbound_in_transit) AS inbound_in_transit,
    MAX(inbound_shipped) AS inbound_shipped,
    MAX(inbound_working) AS inbound_working,
    MAX(po_upc_inventory) AS po_upc_inventory,
    MAX(po_sku_inventory) AS po_sku_inventory,
    MAX(ns_upc_fulfilled) AS ns_upc_fulfilled,
    MAX(ns_upc_qty) AS ns_upc_qty,
    MAX(local_upc_inventory) AS local_upc_inventory,
    SUM(available) AS available,
    SUM(fc_transfer) AS fc_transfer,
    SUM(fc_processing) AS fc_processing,
    SUM(customer_order) AS customer_order,
    SUM(total_inbound) AS total_inbound,
    SUM(working) AS working,
    SUM(unfulfillable) AS unfulfillable,
    SUM(shipped) AS shipped,
    SUM(receiving) AS receiving,
    MIN(name) AS name,
    MIN(sku_name) AS sku_name,
    MIN(merchant_id) AS merchant_id,
    MIN(partner) AS partner,
    MIN(brand) AS brand,
    MAX(cost) AS cost,
    MAX(nonsellable_sku_inventory) AS nonsellable_sku_inventory,
    MAX(nonsellable_upc_inventory) AS nonsellable_upc_inventory,
    MAX(inv_age_0_to_90_days) AS inv_age_0_to_90_days,
    MAX(inv_age_91_to_180_days) AS inv_age_91_to_180_days,
    MAX(inv_age_181_to_270_days) AS inv_age_181_to_270_days,
    MAX(inv_age_271_to_365_days) AS inv_age_271_to_365_days,
    MAX(inv_age_365_plus_days) AS inv_age_365_plus_days,
    SUM(reserved) AS reserved,
    MAX(submitted_date) AS submitted_date,
    MAX(imported_at) AS imported_at,
    MAX(updated_at) AS updated_at,
    MIN(new_country_id) AS country_id,
    MAX(id) AS id,
    MAX(market_place_id) AS market_place_id,
    MIN(upc) AS upc,
    MAX(end_date) AS end_date,
    MAX(enable_report_gathering) AS enable_report_gathering,
    MIN(secret_access_key) AS secret_access_key,
    MIN(countries_marketplace_id) AS countries_marketplace_id,
    MIN(start_date) AS start_date,
    MAX(total_inventory) AS total_inventory,
    MIN(sku_reorder_status) AS sku_reorder_status,
    MIN(is_preferred_sku_by_asin) AS is_preferred_sku_by_asin,
    SUM(min_local_sku_inventory) AS min_local_sku_inventory,
    MAX(local_sku_inventory) AS local_sku_inventory,
    MAX(is_bundle) AS is_bundle,
    SUM(replenishment_plan) AS replenishment_plan,
    MAX(ware2go_on_hand_qty) AS ware2go_on_hand_qty,
    MAX(ware2go_available_qty) AS ware2go_available_qty
  FROM _Add_new_country_id_20_for_Europe
  GROUP BY
    sku,
    new_country_id,
    asin,
    amazon_seller_id
), _Add_Inventory_Columns AS (
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_upc_inventory,
    po_sku_inventory,
    ns_upc_fulfilled,
    ns_upc_qty,
    local_upc_inventory,
    available,
    fc_transfer,
    fc_processing,
    customer_order,
    total_inbound,
    working,
    unfulfillable,
    shipped,
    receiving,
    name,
    sku_name,
    merchant_id,
    partner,
    brand,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    reserved,
    submitted_date,
    imported_at,
    updated_at,
    country_id,
    id,
    market_place_id,
    upc,
    end_date,
    enable_report_gathering,
    secret_access_key,
    countries_marketplace_id,
    start_date,
    total_inventory,
    sku_reorder_status,
    is_preferred_sku_by_asin,
    min_local_sku_inventory,
    local_sku_inventory,
    is_bundle,
    replenishment_plan,
    ware2go_on_hand_qty,
    ware2go_available_qty,
    (
      available + fc_transfer + fc_processing + total_inbound
    ) AS fba_inventory,
    (
      available + fc_transfer + ware2go_available_qty
    ) AS fba_fulfillable,
    (
      CASE WHEN amazon_seller_id = 36 THEN 0 ELSE cost END
    ) AS cost
  FROM _Group_by_SKU_Inventory_Formula
), _Everything_Else AS (
  SELECT
    *
  FROM _Add_Inventory_Columns
  WHERE
    amazon_seller_id <> '17'
), _Firefly_Canada_CAN_SKUs_Only AS (
  SELECT
    *
  FROM _Add_Inventory_Columns
  WHERE
    (
      new_country_id = '2' AND (
        amazon_seller_id = '17' AND sku LIKE '%-CAN'
      )
    )
), _Firefly_US_Only AS (
  SELECT
    *
  FROM _Add_Inventory_Columns
  WHERE
    (
      amazon_seller_id = '17' AND new_country_id = '1'
    )
), _Bring_Back_Together AS (
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_upc_inventory,
    po_sku_inventory,
    ns_upc_fulfilled,
    ns_upc_qty,
    local_upc_inventory,
    available,
    fc_transfer,
    fc_processing,
    customer_order,
    total_inbound,
    working,
    unfulfillable,
    shipped,
    receiving,
    name,
    sku_name,
    merchant_id,
    partner,
    brand,
    cost,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    reserved,
    submitted_date,
    imported_at,
    updated_at,
    country_id,
    id,
    market_place_id,
    upc,
    end_date,
    enable_report_gathering,
    secret_access_key,
    countries_marketplace_id,
    start_date,
    total_inventory,
    sku_reorder_status,
    is_preferred_sku_by_asin,
    min_local_sku_inventory,
    local_sku_inventory,
    is_bundle,
    replenishment_plan,
    ware2go_on_hand_qty,
    ware2go_available_qty,
    fba_inventory,
    fba_fulfillable
  FROM _Everything_Else
  UNION ALL
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_upc_inventory,
    po_sku_inventory,
    ns_upc_fulfilled,
    ns_upc_qty,
    local_upc_inventory,
    available,
    fc_transfer,
    fc_processing,
    customer_order,
    total_inbound,
    working,
    unfulfillable,
    shipped,
    receiving,
    name,
    sku_name,
    merchant_id,
    partner,
    brand,
    cost,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    reserved,
    submitted_date,
    imported_at,
    updated_at,
    country_id,
    id,
    market_place_id,
    upc,
    end_date,
    enable_report_gathering,
    secret_access_key,
    countries_marketplace_id,
    start_date,
    total_inventory,
    sku_reorder_status,
    is_preferred_sku_by_asin,
    min_local_sku_inventory,
    local_sku_inventory,
    is_bundle,
    replenishment_plan,
    ware2go_on_hand_qty,
    ware2go_available_qty,
    fba_inventory,
    fba_fulfillable
  FROM _Firefly_Canada_CAN_SKUs_Only
  UNION ALL
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_upc_inventory,
    po_sku_inventory,
    ns_upc_fulfilled,
    ns_upc_qty,
    local_upc_inventory,
    available,
    fc_transfer,
    fc_processing,
    customer_order,
    total_inbound,
    working,
    unfulfillable,
    shipped,
    receiving,
    name,
    sku_name,
    merchant_id,
    partner,
    brand,
    cost,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    reserved,
    submitted_date,
    imported_at,
    updated_at,
    country_id,
    id,
    market_place_id,
    upc,
    end_date,
    enable_report_gathering,
    secret_access_key,
    countries_marketplace_id,
    start_date,
    total_inventory,
    sku_reorder_status,
    is_preferred_sku_by_asin,
    min_local_sku_inventory,
    local_sku_inventory,
    is_bundle,
    replenishment_plan,
    ware2go_on_hand_qty,
    ware2go_available_qty,
    fba_inventory,
    fba_fulfillable
  FROM _Firefly_US_Only
), _Inventory_at_Amazon_Report_DS AS (
  SELECT
    *
  FROM _Bring_Back_Together
)
SELECT
  *
FROM _Inventory_at_Amazon_Report_DS