/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 374
Dataflow Name: Inventory by ASIN/SKU for DP
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 28
  Successful: 28
  Failed: 0
  Unique Action Types: 8
  Action Types: Constant, ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, PublishToVault, SelectValues
  Pipelines: 4

Generated: 2025-07-02 10:24:53
================================================================================
*/
WITH _Inventory_at_Amazon_Report_DS AS (
  SELECT
    sku,
    new_country_id,
    asin,
    amazon_seller_id,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_upc_inventory,
    po_sku_inventory,
    ns_upc_fulfilled,
    ns_upc_qty,
    local_upc_inventory,
    available,
    fc_transfer,
    fc_processing,
    customer_order,
    total_inbound,
    working,
    unfulfillable,
    shipped,
    receiving,
    name,
    sku_name,
    merchant_id,
    partner,
    brand,
    cost,
    nonsellable_sku_inventory,
    nonsellable_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    reserved,
    submitted_date,
    imported_at,
    updated_at,
    country_id,
    id,
    market_place_id,
    upc,
    end_date,
    enable_report_gathering,
    secret_access_key,
    countries_marketplace_id,
    start_date,
    total_inventory,
    sku_reorder_status,
    is_preferred_sku_by_asin,
    min_local_sku_inventory,
    local_sku_inventory,
    is_bundle,
    replenishment_plan,
    ware2go_on_hand_qty,
    ware2go_available_qty,
    fba_inventory,
    fba_fulfillable
  FROM Inventory_at_Amazon_Report_DS
), _Product_List_DataSet AS (
  SELECT
    amazon_seller_id,
    asin,
    brand_id,
    client_id,
    cost,
    deleted_at,
    fnsku,
    id,
    is_bundle,
    reorder_status,
    sku,
    units_in_listing,
    upc,
    vendor_parameter_id,
    vendor_sku,
    batch_id,
    batch_last_run,
    advertisement_enabled,
    description,
    estimated_annual_sales,
    member_since,
    partner_name,
    currency,
    estimated_anual_sales,
    legacy_brand_id,
    map_formula,
    brand,
    category,
    subcategory,
    brand_growth_target,
    msrp,
    map,
    amazon_asin_id,
    upc_id,
    country_id,
    srp,
    upc_srp,
    upc_default_cost,
    upc_default_discount,
    default_cost,
    default_discount,
    upc_map,
    wholesale_price,
    parent_asin,
    catalog_source,
    country_of_origin,
    min_order_qty,
    units_per_case,
    unit_lxwxh_inches,
    unit_weight_lb,
    sku_reorder_status,
    upc_reorder_status,
    is_discontinued_status,
    upc_components,
    catalog_last_appearance,
    parent_category,
    child_category,
    child_category_3,
    child_category_2,
    sku_reorder_comments,
    upc_reorder_comments,
    is_preferred_sku_by_asin,
    seller_name,
    countries_name,
    sku_created_date,
    upc_created_date,
    sku_cost,
    is_current,
    fulfillment_channel,
    last_seen_price,
    last_known_price,
    estimated_units_sold_last_month,
    hero,
    upc_count_total_components,
    brand_created_at,
    seller_start_date,
    brand_start_date,
    amazon_seller_central_accounts_created_at,
    bp_partner_name,
    bp_brand_name,
    partner_-_brand,
    seller_created_at,
    preferred_skus_on_asin,
    qa_-_count_fbm_offers_current,
    qa_-_count_fba_offers_current,
    qa_-count_reorder_status_yes,
    qa_-count_preferred_skus,
    qa_-current_preferred_skus,
    is_current_asin,
    name,
    upc_name
  FROM Product_List_DataSet
), _sales_by_products_archive AS (
  SELECT
    brand_id,
    client_id,
    cogs,
    country_id,
    date,
    expanded_units,
    id,
    product_id,
    sales,
    units,
    brand_name,
    client_name,
    amazon_seller_id,
    country_1,
    batch_id,
    batch_last_run
  FROM sales_by_products_archive
), _Velocities_by_ASIN AS (
  SELECT
    asin,
    upc,
    upc_name,
    date,
    brand,
    upc_id,
    v_1,
    v_2,
    v_3,
    v_4,
    v_5
  FROM Velocities_by_ASIN
), _Qty_Buckets_by_ASIN_SKU_Seller_Brand_Partner AS (
  SELECT
    asin,
    sku,
    amazon_seller_id,
    name,
    brand,
    partner,
    SUM(afn_fulfillable_quantity) AS afn_fulfillable_quantity,
    SUM(afn_researching_quantity) AS afn_researching_quantity,
    SUM(afn_unsellable_quantity) AS afn_unsellable_quantity,
    SUM(reserved_customerorders) AS reserved_customerorders,
    SUM(reserved_fc_transfers) AS reserved_fc_transfers,
    SUM(reserved_fc_processing) AS reserved_fc_processing,
    SUM(inbound_receiving) AS inbound_receiving,
    SUM(inbound_checked_in) AS inbound_checked_in,
    SUM(inbound_delivered) AS inbound_delivered,
    SUM(inbound_in_transit) AS inbound_in_transit,
    SUM(inbound_shipped) AS inbound_shipped,
    SUM(inbound_working) AS inbound_working,
    SUM(local_sku_inventory) AS po_received,
    SUM(po_sku_inventory) AS po_approved,
    MAX(po_upc_inventory) AS po_upc_inventory,
    SUM(inv_age_0_to_90_days) AS inv_age_0_to_90_days,
    SUM(inv_age_91_to_180_days) AS inv_age_91_to_180_days,
    SUM(inv_age_181_to_270_days) AS inv_age_181_to_270_days,
    SUM(inv_age_271_to_365_days) AS inv_age_271_to_365_days,
    SUM(inv_age_365_plus_days) AS inv_age_365_plus_days,
    SUM(total_inventory) AS total_inventory,
    AVG(cost) AS avg_cost,
    MAX(cost) AS max_cost
  FROM _Inventory_at_Amazon_Report_DS
  GROUP BY
    asin,
    sku,
    amazon_seller_id,
    name,
    brand,
    partner
), _Filter_28_days AS (
  SELECT
    *
  FROM _sales_by_products_archive
  WHERE
    date BETWEEN DATEADD(DAY, '29' * -1, NOW()) AND DATEADD(DAY, '1' * -1, NOW())
), _Filter_7_Days AS (
  SELECT
    *
  FROM _sales_by_products_archive
  WHERE
    date BETWEEN DATEADD(DAY, '8' * -1, NOW()) AND DATEADD(DAY, '1' * -1, NOW())
), _Qty_Totals AS (
  SELECT
    asin,
    sku,
    amazon_seller_id,
    name,
    brand,
    partner,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    reserved_customerorders,
    reserved_fc_transfers,
    reserved_fc_processing,
    inbound_receiving,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_shipped,
    inbound_working,
    po_received,
    po_approved,
    po_upc_inventory,
    inv_age_0_to_90_days,
    inv_age_91_to_180_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    total_inventory,
    avg_cost,
    max_cost,
    (
      0
    ) AS po_created,
    (
      0
    ) AS po_invoiced,
    (
      0
    ) AS po_processed,
    (
      total_inventory * avg_cost
    ) AS inventory_value_-_avg,
    (
      total_inventory * max_cost
    ) AS inventory_value_-_max,
    (
      name
    ) AS account_name,
    (
      0
    ) AS qty_with_removals_in_progress,
    (
      afn_fulfillable_quantity + afn_researching_quantity + afn_unsellable_quantity + reserved_fc_processing + reserved_fc_transfers + inbound_checked_in + inbound_delivered + inbound_receiving + inbound_in_transit + inbound_shipped + inbound_working + po_processed + po_received + po_invoiced
    ) AS total_inv_scorecard
  FROM _Qty_Buckets_by_ASIN_SKU_Seller_Brand_Partner
), _Join_Data AS (
  SELECT
    _Filter_28_days.brand_id,
    _Filter_28_days.client_id,
    _Filter_28_days.cogs,
    _Filter_28_days.country_id,
    _Filter_28_days.date,
    _Filter_28_days.expanded_units,
    _Filter_28_days.id,
    _Filter_28_days.product_id,
    _Filter_28_days.sales,
    _Filter_28_days.units,
    _Filter_28_days.brand_name,
    _Filter_28_days.client_name,
    _Filter_28_days.amazon_seller_id,
    _Filter_28_days.country_1,
    _Filter_28_days.batch_id,
    _Filter_28_days.batch_last_run,
    _Product_List_DataSet.asin,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.sku,
    _Product_List_DataSet.units_in_listing,
    _Product_List_DataSet.upc,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.brand,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.name,
    _Product_List_DataSet.upc_name
  FROM _Filter_28_days
  INNER JOIN _Product_List_DataSet
    ON _Filter_28_days.product_id = _Product_List_DataSet.id
), _Join_L7_Products AS (
  SELECT
    _Filter_7_Days.brand_id,
    _Filter_7_Days.client_id,
    _Filter_7_Days.cogs,
    _Filter_7_Days.country_id,
    _Filter_7_Days.date,
    _Filter_7_Days.expanded_units,
    _Filter_7_Days.id,
    _Filter_7_Days.product_id,
    _Filter_7_Days.sales,
    _Filter_7_Days.units,
    _Filter_7_Days.brand_name,
    _Filter_7_Days.client_name,
    _Filter_7_Days.amazon_seller_id,
    _Filter_7_Days.country_1,
    _Filter_7_Days.batch_id,
    _Filter_7_Days.batch_last_run,
    _Product_List_DataSet.asin,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.sku,
    _Product_List_DataSet.units_in_listing,
    _Product_List_DataSet.upc,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.brand,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.name,
    _Product_List_DataSet.upc_name
  FROM _Filter_7_Days
  INNER JOIN _Product_List_DataSet
    ON _Filter_7_Days.product_id = _Product_List_DataSet.id
), _join_inventory_products AS (
  SELECT
    _Qty_Totals.asin,
    _Qty_Totals.sku,
    _Qty_Totals.amazon_seller_id,
    _Qty_Totals.name,
    _Qty_Totals.brand,
    _Qty_Totals.partner,
    _Qty_Totals.afn_fulfillable_quantity,
    _Qty_Totals.afn_researching_quantity,
    _Qty_Totals.afn_unsellable_quantity,
    _Qty_Totals.reserved_customerorders,
    _Qty_Totals.reserved_fc_transfers,
    _Qty_Totals.reserved_fc_processing,
    _Qty_Totals.inbound_receiving,
    _Qty_Totals.inbound_checked_in,
    _Qty_Totals.inbound_delivered,
    _Qty_Totals.inbound_in_transit,
    _Qty_Totals.inbound_shipped,
    _Qty_Totals.inbound_working,
    _Qty_Totals.po_received,
    _Qty_Totals.po_approved,
    _Qty_Totals.po_upc_inventory,
    _Qty_Totals.inv_age_0_to_90_days,
    _Qty_Totals.inv_age_91_to_180_days,
    _Qty_Totals.inv_age_181_to_270_days,
    _Qty_Totals.inv_age_271_to_365_days,
    _Qty_Totals.inv_age_365_plus_days,
    _Qty_Totals.total_inventory,
    _Qty_Totals.avg_cost,
    _Qty_Totals.max_cost,
    _Qty_Totals.po_created,
    _Qty_Totals.po_invoiced,
    _Qty_Totals.po_processed,
    _Qty_Totals.inventory_value_-_avg,
    _Qty_Totals.inventory_value_-_max,
    _Qty_Totals.account_name,
    _Qty_Totals.total_inv_scorecard,
    _Qty_Totals.qty_with_removals_in_progress,
    _Product_List_DataSet.brand_id,
    _Product_List_DataSet.client_id,
    _Product_List_DataSet.cost,
    _Product_List_DataSet.deleted_at,
    _Product_List_DataSet.fnsku,
    _Product_List_DataSet.id,
    _Product_List_DataSet.is_bundle,
    _Product_List_DataSet.reorder_status,
    _Product_List_DataSet.vendor_parameter_id,
    _Product_List_DataSet.vendor_sku,
    _Product_List_DataSet.advertisement_enabled,
    _Product_List_DataSet.description,
    _Product_List_DataSet.estimated_annual_sales,
    _Product_List_DataSet.member_since,
    _Product_List_DataSet.partner_name,
    _Product_List_DataSet.currency,
    _Product_List_DataSet.estimated_anual_sales,
    _Product_List_DataSet.legacy_brand_id,
    _Product_List_DataSet.map_formula,
    _Product_List_DataSet.category,
    _Product_List_DataSet.subcategory,
    _Product_List_DataSet.brand_growth_target,
    _Product_List_DataSet.msrp,
    _Product_List_DataSet.map,
    _Product_List_DataSet.amazon_asin_id,
    _Product_List_DataSet.upc_id,
    _Product_List_DataSet.country_id,
    _Product_List_DataSet.srp,
    _Product_List_DataSet.upc_srp,
    _Product_List_DataSet.upc_default_cost,
    _Product_List_DataSet.upc_default_discount,
    _Product_List_DataSet.default_cost,
    _Product_List_DataSet.default_discount,
    _Product_List_DataSet.upc_map,
    _Product_List_DataSet.wholesale_price,
    _Product_List_DataSet.parent_asin,
    _Product_List_DataSet.catalog_source,
    _Product_List_DataSet.country_of_origin,
    _Product_List_DataSet.min_order_qty,
    _Product_List_DataSet.units_per_case,
    _Product_List_DataSet.unit_lxwxh_inches,
    _Product_List_DataSet.unit_weight_lb,
    _Product_List_DataSet.sku_reorder_status,
    _Product_List_DataSet.upc_reorder_status,
    _Product_List_DataSet.is_discontinued_status,
    _Product_List_DataSet.upc_components,
    _Product_List_DataSet.catalog_last_appearance,
    _Product_List_DataSet.parent_category,
    _Product_List_DataSet.child_category,
    _Product_List_DataSet.child_category_3,
    _Product_List_DataSet.child_category_2,
    _Product_List_DataSet.sku_reorder_comments,
    _Product_List_DataSet.upc_reorder_comments,
    _Product_List_DataSet.is_preferred_sku_by_asin,
    _Product_List_DataSet.seller_name,
    _Product_List_DataSet.countries_name,
    _Product_List_DataSet.sku_created_date,
    _Product_List_DataSet.upc_created_date,
    _Product_List_DataSet.sku_cost,
    _Product_List_DataSet.is_current,
    _Product_List_DataSet.fulfillment_channel,
    _Product_List_DataSet.last_seen_price,
    _Product_List_DataSet.last_known_price,
    _Product_List_DataSet.estimated_units_sold_last_month,
    _Product_List_DataSet.hero,
    _Product_List_DataSet.upc_count_total_components,
    _Product_List_DataSet.brand_created_at,
    _Product_List_DataSet.seller_start_date,
    _Product_List_DataSet.brand_start_date,
    _Product_List_DataSet.amazon_seller_central_accounts_created_at,
    _Product_List_DataSet.bp_partner_name,
    _Product_List_DataSet.bp_brand_name,
    _Product_List_DataSet.partner_-_brand,
    _Product_List_DataSet.seller_created_at,
    _Product_List_DataSet.preferred_skus_on_asin,
    _Product_List_DataSet.qa_-_count_fbm_offers_current,
    _Product_List_DataSet.qa_-_count_fba_offers_current,
    _Product_List_DataSet.qa_-count_reorder_status_yes,
    _Product_List_DataSet.qa_-count_preferred_skus,
    _Product_List_DataSet.qa_-current_preferred_skus,
    _Product_List_DataSet.is_current_asin,
    _Product_List_DataSet.upc_name
  FROM _Qty_Totals
  RIGHT JOIN _Product_List_DataSet
    ON _Qty_Totals.sku = _Product_List_DataSet.sku
    AND _Qty_Totals.asin = _Product_List_DataSet.asin
    AND _Qty_Totals.amazon_seller_id = _Product_List_DataSet.amazon_seller_id
), _Group_By_Brand_L28 AS (
  SELECT
    brand_id,
    SUM(sales) AS brand_sales_last28,
    MAX(expanded_units) AS brand_max_units_last28,
    MIN(expanded_units) AS brand_min_units_last28,
    AVG(expanded_units) AS brand_avg_units_last28
  FROM _Join_Data
  GROUP BY
    brand_id
), _Group_By_ASIN_L28 AS (
  SELECT
    brand_id,
    asin,
    sku,
    SUM(sales) AS asin_sales_last28,
    SUM(expanded_units) AS asin_expanded_units_last28,
    MIN(expanded_units) AS asin_min_expanded_units_last28,
    MAX(expanded_units) AS asin_max_expanded_units_last28,
    AVG(expanded_units) AS asin_avg_expanded_units_last28,
    SUM(units) AS asin_units_last28,
    AVG(units) AS asin_avg_units_last28,
    MIN(units) AS asin_min_units_last28,
    MAX(units) AS asin_max_units_last28
  FROM _Join_Data
  GROUP BY
    brand_id,
    asin,
    sku
), _Group_By_Brand_L7 AS (
  SELECT
    brand_id,
    SUM(sales) AS brand_sales_last7,
    MAX(expanded_units) AS brand_max_units_last7,
    MIN(expanded_units) AS brand_min_units_last7,
    AVG(expanded_units) AS brand_avg_units_last7
  FROM _Join_L7_Products
  GROUP BY
    brand_id
), _Group_By_ASIN_L7 AS (
  SELECT
    brand_id,
    asin,
    sku,
    SUM(sales) AS asin_sales_last7,
    SUM(expanded_units) AS asin_expanded_units_last7,
    MIN(expanded_units) AS asin_min_expanded_units_last7,
    MAX(expanded_units) AS asin_max_expanded_units_last7,
    AVG(expanded_units) AS asin_avg_expanded_units_last7,
    SUM(units) AS asin_units_last7,
    AVG(units) AS asin_avg_units_last7
  FROM _Join_L7_Products
  GROUP BY
    brand_id,
    asin,
    sku
), _Group_By_asin AS (
  SELECT
    asin,
    brand_id,
    amazon_seller_id,
    sku,
    SUM(po_approved) AS po_approved,
    SUM(po_created) AS po_created,
    SUM(po_invoiced) AS po_invoiced,
    SUM(po_processed) AS po_processed,
    SUM(po_received) AS po_received,
    SUM(afn_fulfillable_quantity) AS afn_fulfillable_quantity,
    SUM(afn_researching_quantity) AS afn_researching_quantity,
    SUM(afn_unsellable_quantity) AS afn_unsellable_quantity,
    SUM(inbound_checked_in) AS inbound_checked_in,
    SUM(inbound_delivered) AS inbound_delivered,
    SUM(inbound_in_transit) AS inbound_in_transit,
    SUM(inbound_receiving) AS inbound_receiving,
    SUM(inbound_shipped) AS inbound_shipped,
    SUM(inbound_working) AS inbound_working,
    SUM(inv_age_0_to_90_days) AS inv_age_0_to_90_days,
    SUM(inv_age_181_to_270_days) AS inv_age_181_to_270_days,
    SUM(inv_age_271_to_365_days) AS inv_age_271_to_365_days,
    SUM(inv_age_365_plus_days) AS inv_age_365_plus_days,
    SUM(inv_age_91_to_180_days) AS inv_age_91_to_180_days,
    SUM(reserved_customerorders) AS reserved_customerorders,
    SUM(reserved_fc_processing) AS reserved_fc_processing,
    SUM(reserved_fc_transfers) AS reserved_fc_transfers
  FROM _join_inventory_products
  GROUP BY
    asin,
    brand_id,
    amazon_seller_id,
    sku
), _Last28 AS (
  SELECT
    _Group_By_ASIN_L28.brand_id,
    _Group_By_ASIN_L28.asin,
    _Group_By_ASIN_L28.sku,
    _Group_By_ASIN_L28.asin_sales_last28,
    _Group_By_ASIN_L28.asin_expanded_units_last28,
    _Group_By_ASIN_L28.asin_min_expanded_units_last28,
    _Group_By_ASIN_L28.asin_max_expanded_units_last28,
    _Group_By_ASIN_L28.asin_avg_expanded_units_last28,
    _Group_By_ASIN_L28.asin_units_last28,
    _Group_By_ASIN_L28.asin_avg_units_last28,
    _Group_By_ASIN_L28.asin_min_units_last28,
    _Group_By_ASIN_L28.asin_max_units_last28,
    _Group_By_Brand_L28.brand_sales_last28,
    _Group_By_Brand_L28.brand_max_units_last28,
    _Group_By_Brand_L28.brand_min_units_last28,
    _Group_By_Brand_L28.brand_avg_units_last28
  FROM _Group_By_ASIN_L28
  INNER JOIN _Group_By_Brand_L28
    ON _Group_By_ASIN_L28.brand_id = _Group_By_Brand_L28.brand_id
), _Last_7 AS (
  SELECT
    _Group_By_Brand_L7.brand_id,
    _Group_By_Brand_L7.brand_sales_last7,
    _Group_By_Brand_L7.brand_max_units_last7,
    _Group_By_Brand_L7.brand_min_units_last7,
    _Group_By_Brand_L7.brand_avg_units_last7,
    _Group_By_ASIN_L7.asin,
    _Group_By_ASIN_L7.sku,
    _Group_By_ASIN_L7.asin_sales_last7,
    _Group_By_ASIN_L7.asin_expanded_units_last7,
    _Group_By_ASIN_L7.asin_min_expanded_units_last7,
    _Group_By_ASIN_L7.asin_max_expanded_units_last7,
    _Group_By_ASIN_L7.asin_avg_expanded_units_last7,
    _Group_By_ASIN_L7.asin_units_last7,
    _Group_By_ASIN_L7.asin_avg_units_last7
  FROM _Group_By_Brand_L7
  INNER JOIN _Group_By_ASIN_L7
    ON _Group_By_Brand_L7.brand_id = _Group_By_ASIN_L7.brand_id
), _add_current_date AS (
  SELECT
    1 AS constant_value
), _L28_L7 AS (
  SELECT
    _Last28.brand_id,
    _Last28.brand_sales_last28,
    _Last28.brand_max_units_last28,
    _Last28.brand_min_units_last28,
    _Last28.brand_avg_units_last28,
    _Last28.asin,
    _Last28.sku,
    _Last28.asin_sales_last28,
    _Last28.asin_expanded_units_last28,
    _Last28.asin_min_expanded_units_last28,
    _Last28.asin_max_expanded_units_last28,
    _Last28.asin_avg_expanded_units_last28,
    _Last28.asin_units_last28,
    _Last28.asin_avg_units_last28,
    _Last28.asin_min_units_last28,
    _Last28.asin_max_units_last28,
    _Last_7.brand_sales_last7,
    _Last_7.brand_max_units_last7,
    _Last_7.brand_min_units_last7,
    _Last_7.brand_avg_units_last7,
    _Last_7.asin_sales_last7,
    _Last_7.asin_expanded_units_last7,
    _Last_7.asin_min_expanded_units_last7,
    _Last_7.asin_max_expanded_units_last7,
    _Last_7.asin_avg_expanded_units_last7,
    _Last_7.asin_units_last7,
    _Last_7.asin_avg_units_last7
  FROM _Last28
  INNER JOIN _Last_7
    ON _Last28.brand_id = _Last_7.brand_id
    AND _Last28.asin = _Last_7.asin
    AND _Last28.sku = _Last_7.sku
), _Add_asin_inventory_field AS (
  SELECT
    asin,
    brand_id,
    amazon_seller_id,
    sku,
    po_approved,
    po_created,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    (
      afn_fulfillable_quantity
    ) AS asin_inventory
  FROM _add_current_date
), _inventory_Sales_L28 AS (
  SELECT
    _Add_asin_inventory_field.asin,
    _Add_asin_inventory_field.brand_id,
    _Add_asin_inventory_field.amazon_seller_id,
    _Add_asin_inventory_field.sku,
    _Add_asin_inventory_field.po_approved,
    _Add_asin_inventory_field.po_created,
    _Add_asin_inventory_field.po_invoiced,
    _Add_asin_inventory_field.po_processed,
    _Add_asin_inventory_field.po_received,
    _Add_asin_inventory_field.afn_fulfillable_quantity,
    _Add_asin_inventory_field.afn_researching_quantity,
    _Add_asin_inventory_field.afn_unsellable_quantity,
    _Add_asin_inventory_field.inbound_checked_in,
    _Add_asin_inventory_field.inbound_delivered,
    _Add_asin_inventory_field.inbound_in_transit,
    _Add_asin_inventory_field.inbound_receiving,
    _Add_asin_inventory_field.inbound_shipped,
    _Add_asin_inventory_field.inbound_working,
    _Add_asin_inventory_field.inv_age_0_to_90_days,
    _Add_asin_inventory_field.inv_age_181_to_270_days,
    _Add_asin_inventory_field.inv_age_271_to_365_days,
    _Add_asin_inventory_field.inv_age_365_plus_days,
    _Add_asin_inventory_field.inv_age_91_to_180_days,
    _Add_asin_inventory_field.reserved_customerorders,
    _Add_asin_inventory_field.reserved_fc_processing,
    _Add_asin_inventory_field.reserved_fc_transfers,
    _Add_asin_inventory_field.asin_inventory,
    _L28_L7.brand_sales_last28,
    _L28_L7.brand_max_units_last28,
    _L28_L7.brand_min_units_last28,
    _L28_L7.brand_avg_units_last28,
    _L28_L7.asin_sales_last28,
    _L28_L7.asin_expanded_units_last28,
    _L28_L7.asin_min_expanded_units_last28,
    _L28_L7.asin_max_expanded_units_last28,
    _L28_L7.asin_avg_expanded_units_last28,
    _L28_L7.asin_units_last28,
    _L28_L7.asin_avg_units_last28,
    _L28_L7.asin_min_units_last28,
    _L28_L7.asin_max_units_last28,
    _L28_L7.brand_sales_last7,
    _L28_L7.brand_max_units_last7,
    _L28_L7.brand_min_units_last7,
    _L28_L7.brand_avg_units_last7,
    _L28_L7.asin_sales_last7,
    _L28_L7.asin_expanded_units_last7,
    _L28_L7.asin_min_expanded_units_last7,
    _L28_L7.asin_max_expanded_units_last7,
    _L28_L7.asin_avg_expanded_units_last7,
    _L28_L7.asin_units_last7,
    _L28_L7.asin_avg_units_last7
  FROM _Add_asin_inventory_field
  LEFT JOIN _L28_L7
    ON _Add_asin_inventory_field.asin = _L28_L7.asin
    AND _Add_asin_inventory_field.brand_id = _L28_L7.brand_id
    AND _Add_asin_inventory_field.sku = _L28_L7.sku
), _Join_Data_1 AS (
  SELECT
    _inventory_Sales_L28.asin,
    _inventory_Sales_L28.brand_id,
    _inventory_Sales_L28.amazon_seller_id,
    _inventory_Sales_L28.sku,
    _inventory_Sales_L28.po_approved,
    _inventory_Sales_L28.po_created,
    _inventory_Sales_L28.po_invoiced,
    _inventory_Sales_L28.po_processed,
    _inventory_Sales_L28.po_received,
    _inventory_Sales_L28.afn_fulfillable_quantity,
    _inventory_Sales_L28.afn_researching_quantity,
    _inventory_Sales_L28.afn_unsellable_quantity,
    _inventory_Sales_L28.inbound_checked_in,
    _inventory_Sales_L28.inbound_delivered,
    _inventory_Sales_L28.inbound_in_transit,
    _inventory_Sales_L28.inbound_receiving,
    _inventory_Sales_L28.inbound_shipped,
    _inventory_Sales_L28.inbound_working,
    _inventory_Sales_L28.inv_age_0_to_90_days,
    _inventory_Sales_L28.inv_age_181_to_270_days,
    _inventory_Sales_L28.inv_age_271_to_365_days,
    _inventory_Sales_L28.inv_age_365_plus_days,
    _inventory_Sales_L28.inv_age_91_to_180_days,
    _inventory_Sales_L28.reserved_customerorders,
    _inventory_Sales_L28.reserved_fc_processing,
    _inventory_Sales_L28.reserved_fc_transfers,
    _inventory_Sales_L28.asin_inventory,
    _inventory_Sales_L28.brand_sales_last28,
    _inventory_Sales_L28.brand_max_units_last28,
    _inventory_Sales_L28.brand_min_units_last28,
    _inventory_Sales_L28.brand_avg_units_last28,
    _inventory_Sales_L28.asin_sales_last28,
    _inventory_Sales_L28.asin_expanded_units_last28,
    _inventory_Sales_L28.asin_min_expanded_units_last28,
    _inventory_Sales_L28.asin_max_expanded_units_last28,
    _inventory_Sales_L28.asin_avg_expanded_units_last28,
    _inventory_Sales_L28.asin_units_last28,
    _inventory_Sales_L28.asin_avg_units_last28,
    _inventory_Sales_L28.asin_min_units_last28,
    _inventory_Sales_L28.asin_max_units_last28,
    _inventory_Sales_L28.brand_sales_last7,
    _inventory_Sales_L28.brand_max_units_last7,
    _inventory_Sales_L28.brand_min_units_last7,
    _inventory_Sales_L28.brand_avg_units_last7,
    _inventory_Sales_L28.asin_sales_last7,
    _inventory_Sales_L28.asin_expanded_units_last7,
    _inventory_Sales_L28.asin_min_expanded_units_last7,
    _inventory_Sales_L28.asin_max_expanded_units_last7,
    _inventory_Sales_L28.asin_avg_expanded_units_last7,
    _inventory_Sales_L28.asin_units_last7,
    _inventory_Sales_L28.asin_avg_units_last7,
    _Velocities_by_ASIN.upc,
    _Velocities_by_ASIN.upc_name,
    _Velocities_by_ASIN.date,
    _Velocities_by_ASIN.brand,
    _Velocities_by_ASIN.upc_id,
    _Velocities_by_ASIN.v_1,
    _Velocities_by_ASIN.v_2,
    _Velocities_by_ASIN.v_3,
    _Velocities_by_ASIN.v_4,
    _Velocities_by_ASIN.v_5
  FROM _inventory_Sales_L28
  LEFT JOIN _Velocities_by_ASIN
    ON _inventory_Sales_L28.asin = _Velocities_by_ASIN.asin
), _Add_DOH_Formula AS (
  SELECT
    asin,
    brand_id,
    amazon_seller_id,
    sku,
    po_approved,
    po_created,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    asin_inventory,
    brand_sales_last28,
    brand_max_units_last28,
    brand_min_units_last28,
    brand_avg_units_last28,
    asin_sales_last28,
    asin_expanded_units_last28,
    asin_min_expanded_units_last28,
    asin_max_expanded_units_last28,
    asin_avg_expanded_units_last28,
    asin_units_last28,
    asin_avg_units_last28,
    asin_min_units_last28,
    asin_max_units_last28,
    brand_sales_last7,
    brand_max_units_last7,
    brand_min_units_last7,
    brand_avg_units_last7,
    asin_sales_last7,
    asin_expanded_units_last7,
    asin_min_expanded_units_last7,
    asin_max_expanded_units_last7,
    asin_avg_expanded_units_last7,
    asin_units_last7,
    asin_avg_units_last7,
    upc,
    upc_name,
    date,
    brand,
    upc_id,
    v_1,
    v_2,
    v_3,
    v_4,
    v_5,
    (
      (
        asin_sales_last28 / NULLIF(brand_sales_last28, 0)
      ) * (
        asin_inventory / NULLIF((
          COALESCE(v_3, 0.125)
        ), 0)
      )
    ) AS doh_fulfillable_weighted_l28,
    (
      (
        asin_sales_last28 / NULLIF(brand_sales_last28, 0)
      ) * (
        (
          afn_fulfillable_quantity + inbound_checked_in + inbound_delivered + inbound_in_transit + inbound_receiving + inbound_shipped + inbound_working + reserved_fc_processing + reserved_fc_transfers + po_invoiced + po_processed + po_received
        ) / NULLIF((
          COALESCE(v_3, 0.125)
        ), 0)
      )
    ) AS doh_total_weighted_l28,
    (
      (
        afn_fulfillable_quantity + reserved_fc_processing + reserved_fc_transfers + po_processed
      ) / NULLIF(asin_max_units_last28, 0)
    ) AS doh_min,
    (
      (
        afn_fulfillable_quantity + reserved_fc_processing + reserved_fc_transfers + po_processed
      ) / NULLIF(asin_min_units_last28, 0)
    ) AS doh_max,
    (
      (
        afn_fulfillable_quantity + reserved_fc_processing + reserved_fc_transfers + po_processed
      ) / NULLIF(asin_avg_units_last28, 0)
    ) AS doh_avg,
    (
      (
        asin_sales_last7 / NULLIF(brand_sales_last7, 0)
      ) * (
        asin_inventory / NULLIF((
          asin_units_last7 / NULLIF(7, 0)
        ), 0)
      )
    ) AS doh_fulfillable_weighted_l7,
    (
      (
        asin_sales_last7 / NULLIF(brand_sales_last7, 0)
      ) * (
        afn_fulfillable_quantity + inbound_checked_in + inbound_delivered + inbound_in_transit + inbound_receiving + inbound_shipped + inbound_working + reserved_fc_processing + reserved_fc_transfers + po_invoiced + po_processed + po_received + po_approved
      ) / NULLIF((
        asin_units_last7 / NULLIF(7, 0)
      ), 0)
    ) AS doh_total_weighted_l7,
    (
      0
    ) AS qty_with_removals_in_progress
  FROM _Join_Data_1
), _DOH_by_Brand AS (
  SELECT
    brand_id,
    SUM(brand_doh_fulfillable_weighted_l28) AS brand_doh_fulfillable_weighted_l28,
    SUM(brand_doh_total_weighted_l28) AS brand_doh_total_weighted_l28,
    SUM(brand_doh_min) AS brand_doh_min,
    SUM(brand_doh_max) AS brand_doh_max,
    SUM(brand_doh_avg) AS brand_doh_avg,
    SUM(brand_doh_fulfillable_weighted_l7) AS brand_doh_fulfillable_weighted_l7,
    SUM(brand_doh_total_weighted_l7) AS brand_doh_total_weighted_l7
  FROM _Add_DOH_Formula
  GROUP BY
    brand_id
), _DOH_ASIN_Brand AS (
  SELECT
    _Add_DOH_Formula.asin,
    _Add_DOH_Formula.brand_id,
    _Add_DOH_Formula.amazon_seller_id,
    _Add_DOH_Formula.sku,
    _Add_DOH_Formula.po_approved,
    _Add_DOH_Formula.po_created,
    _Add_DOH_Formula.po_invoiced,
    _Add_DOH_Formula.po_processed,
    _Add_DOH_Formula.po_received,
    _Add_DOH_Formula.afn_fulfillable_quantity,
    _Add_DOH_Formula.afn_researching_quantity,
    _Add_DOH_Formula.afn_unsellable_quantity,
    _Add_DOH_Formula.inbound_checked_in,
    _Add_DOH_Formula.inbound_delivered,
    _Add_DOH_Formula.inbound_in_transit,
    _Add_DOH_Formula.inbound_receiving,
    _Add_DOH_Formula.inbound_shipped,
    _Add_DOH_Formula.inbound_working,
    _Add_DOH_Formula.inv_age_0_to_90_days,
    _Add_DOH_Formula.inv_age_181_to_270_days,
    _Add_DOH_Formula.inv_age_271_to_365_days,
    _Add_DOH_Formula.inv_age_365_plus_days,
    _Add_DOH_Formula.inv_age_91_to_180_days,
    _Add_DOH_Formula.reserved_customerorders,
    _Add_DOH_Formula.reserved_fc_processing,
    _Add_DOH_Formula.reserved_fc_transfers,
    _Add_DOH_Formula.asin_inventory,
    _Add_DOH_Formula.brand_sales_last28,
    _Add_DOH_Formula.brand_max_units_last28,
    _Add_DOH_Formula.brand_min_units_last28,
    _Add_DOH_Formula.brand_avg_units_last28,
    _Add_DOH_Formula.asin_sales_last28,
    _Add_DOH_Formula.asin_expanded_units_last28,
    _Add_DOH_Formula.asin_min_expanded_units_last28,
    _Add_DOH_Formula.asin_max_expanded_units_last28,
    _Add_DOH_Formula.asin_avg_expanded_units_last28,
    _Add_DOH_Formula.asin_units_last28,
    _Add_DOH_Formula.asin_avg_units_last28,
    _Add_DOH_Formula.asin_min_units_last28,
    _Add_DOH_Formula.asin_max_units_last28,
    _Add_DOH_Formula.brand_sales_last7,
    _Add_DOH_Formula.brand_max_units_last7,
    _Add_DOH_Formula.brand_min_units_last7,
    _Add_DOH_Formula.brand_avg_units_last7,
    _Add_DOH_Formula.asin_sales_last7,
    _Add_DOH_Formula.asin_expanded_units_last7,
    _Add_DOH_Formula.asin_min_expanded_units_last7,
    _Add_DOH_Formula.asin_max_expanded_units_last7,
    _Add_DOH_Formula.asin_avg_expanded_units_last7,
    _Add_DOH_Formula.asin_units_last7,
    _Add_DOH_Formula.asin_avg_units_last7,
    _Add_DOH_Formula.upc,
    _Add_DOH_Formula.upc_name,
    _Add_DOH_Formula.date,
    _Add_DOH_Formula.brand,
    _Add_DOH_Formula.upc_id,
    _Add_DOH_Formula.v_1,
    _Add_DOH_Formula.v_2,
    _Add_DOH_Formula.v_3,
    _Add_DOH_Formula.v_4,
    _Add_DOH_Formula.v_5,
    _Add_DOH_Formula.doh_fulfillable_weighted_l28,
    _Add_DOH_Formula.doh_total_weighted_l28,
    _Add_DOH_Formula.doh_min,
    _Add_DOH_Formula.doh_max,
    _Add_DOH_Formula.doh_avg,
    _Add_DOH_Formula.doh_fulfillable_weighted_l7,
    _Add_DOH_Formula.doh_total_weighted_l7,
    _Add_DOH_Formula.qty_with_removals_in_progress,
    _DOH_by_Brand.brand_doh_fulfillable_weighted_l28,
    _DOH_by_Brand.brand_doh_total_weighted_l28,
    _DOH_by_Brand.brand_doh_min,
    _DOH_by_Brand.brand_doh_max,
    _DOH_by_Brand.brand_doh_avg,
    _DOH_by_Brand.brand_doh_fulfillable_weighted_l7,
    _DOH_by_Brand.brand_doh_total_weighted_l7
  FROM _Add_DOH_Formula
  LEFT JOIN _DOH_by_Brand
    ON _Add_DOH_Formula.brand_id = _DOH_by_Brand.brand_id
), _Select_Columns AS (
  SELECT
    asin,
    po_approved,
    po_created,
    po_invoiced,
    po_processed,
    po_received,
    afn_fulfillable_quantity,
    afn_researching_quantity,
    afn_unsellable_quantity,
    inbound_checked_in,
    inbound_delivered,
    inbound_in_transit,
    inbound_receiving,
    inbound_shipped,
    inbound_working,
    inv_age_0_to_90_days,
    inv_age_181_to_270_days,
    inv_age_271_to_365_days,
    inv_age_365_plus_days,
    inv_age_91_to_180_days,
    reserved_customerorders,
    reserved_fc_processing,
    reserved_fc_transfers,
    inventory_date,
    asin_inventory,
    asin_sales_last28,
    asin_expanded_units_last28,
    brand_sales_last28,
    brand_doh_min,
    brand_doh_max,
    brand_doh_avg,
    brand_doh_fulfillable_weighted_l28,
    brand_doh_fulfillable_weighted_l7,
    brand_doh_total_weighted_l28,
    brand_doh_total_weighted_l7,
    doh_fulfillable_weighted_l28,
    doh_fulfillable_weighted_l7,
    doh_total_weighted_l28,
    doh_total_weighted_l7,
    brand_id,
    amazon_seller_id,
    v_1,
    v_3,
    qty_with_removals_in_progress,
    sku
  FROM _DOH_ASIN_Brand
), _Inventory_by_ASIN_SKU_for_DP AS (
  SELECT
    *
  FROM _Select_Columns
)
SELECT
  *
FROM _Inventory_by_ASIN_SKU_for_DP