/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 264
Dataflow Name: Enforcement Dataflow
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 22
  Successful: 22
  Failed: 0
  Unique Action Types: 7
  Action Types: ExpressionEvaluator, Filter, GroupBy, LoadFromVault, MergeJoin, PublishToVault, SelectValues
  Pipelines: 6

Generated: 2025-07-02 10:24:07
================================================================================
*/
WITH _Limit_Buster_Inventory_DS AS (
  SELECT
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    bp_brand_id,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_id,
    storefront_enforceable,
    storefront_enforceable_code
  FROM Limit_Buster_Inventory_DS
), _bp_enforcements AS (
  SELECT
    staff,
    partner,
    brand,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    storefront_id,
    storefront_name,
    date,
    type,
    notes_comments,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    response_received,
    order_cost,
    usps_tracking_type,
    recipient_address,
    delivered_city,
    error_status,
    rundatetime,
    return_receipt_downloaded,
    enforce_by_brand,
    enforce_by,
    batch_id,
    batch_last_run
  FROM bp_enforcements
), _countries AS (
  SELECT
    created_at,
    currency,
    enabled,
    id,
    marketplace_id,
    name,
    sales_channel,
    short_name,
    updated_at,
    batch_id,
    batch_last_run
  FROM countries
), _bp_enforcement_settings AS (
  SELECT
    bp_partner_id,
    bp_brand_id,
    bp_partner,
    bp_brand,
    settings_by,
    enforce_by,
    country_id,
    country_name,
    country_code,
    marketplace_channel_id,
    marketplace_channel,
    enforcement_configuration,
    offers_scraper,
    suppression_tracking,
    is_bp_enforceable,
    offers_scraper_enabled,
    suppression_tracking_enabled,
    assigned_user_id,
    assigned_user,
    assigned_user_initials,
    count_asin,
    enforcement_codes,
    batch_id,
    batch_last_run
  FROM bp_enforcement_settings
), _bp_amazon_seller_brands AS (
  SELECT
    seller_id,
    bp_partner_id,
    bp_brand_id,
    enforcement_configuration_id,
    comments,
    last_scraped_at,
    last_scraped_date,
    entity_id,
    enforcement_configuration_code,
    enforcement_configuration,
    bp_partner,
    bp_brand,
    assigned_user_id,
    assigned_user,
    assigned_user_initials,
    batch_id,
    batch_last_run
  FROM bp_amazon_seller_brands
), _UPCs AS (
  SELECT
    brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    client_id,
    cost,
    created_at,
    created_by,
    default_cost,
    default_discount,
    deleted_at,
    deleted_by,
    id,
    hero,
    map,
    min_order_qty,
    name,
    old_upc,
    parent_upc,
    reorder_comments,
    reorder_status,
    srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upc,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    is_discontinued_status,
    amazon_seller_id,
    unit_count_type_id,
    unit_count,
    batch_id,
    batch_last_run
  FROM UPCs
), _get_latest_scraped_date AS (
  SELECT
    *
  FROM _Limit_Buster_Inventory_DS
  WHERE
    scraped_date = DATEADD(DAY, '1' * -1, CURRENT_DATE)
), _Add_Formula AS (
  SELECT
    staff,
    partner,
    brand,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    storefront_id,
    storefront_name,
    date,
    type,
    notes_comments,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    response_received,
    order_cost,
    usps_tracking_type,
    recipient_address,
    delivered_city,
    error_status,
    rundatetime,
    return_receipt_downloaded,
    enforce_by_brand,
    enforce_by,
    batch_id,
    batch_last_run,
    (
      CASE WHEN enforce_by_brand THEN brand ELSE '-' END
    ) AS group_partner_brand
  FROM _bp_enforcements
), _Select_name AS (
  SELECT
    id,
    name AS country
  FROM _countries
), _Join_Data_4 AS (
  SELECT
    _bp_enforcement_settings.bp_partner_id,
    _bp_enforcement_settings.bp_brand_id,
    _bp_enforcement_settings.bp_partner,
    _bp_enforcement_settings.bp_brand,
    _bp_enforcement_settings.settings_by,
    _bp_enforcement_settings.enforce_by,
    _bp_enforcement_settings.country_id,
    _bp_enforcement_settings.country_name,
    _bp_enforcement_settings.country_code,
    _bp_enforcement_settings.marketplace_channel_id,
    _bp_enforcement_settings.marketplace_channel,
    _bp_enforcement_settings.enforcement_configuration AS brand_enforceable,
    _bp_enforcement_settings.offers_scraper,
    _bp_enforcement_settings.suppression_tracking,
    _bp_enforcement_settings.is_bp_enforceable,
    _bp_enforcement_settings.offers_scraper_enabled,
    _bp_enforcement_settings.suppression_tracking_enabled,
    _bp_enforcement_settings.assigned_user_id,
    _bp_enforcement_settings.assigned_user,
    _bp_enforcement_settings.assigned_user_initials,
    _bp_enforcement_settings.count_asin,
    _bp_enforcement_settings.enforcement_codes,
    _bp_enforcement_settings.batch_id,
    _bp_enforcement_settings.batch_last_run,
    _bp_amazon_seller_brands.seller_id,
    _bp_amazon_seller_brands.enforcement_configuration_id,
    _bp_amazon_seller_brands.comments,
    _bp_amazon_seller_brands.last_scraped_at,
    _bp_amazon_seller_brands.last_scraped_date,
    _bp_amazon_seller_brands.entity_id,
    _bp_amazon_seller_brands.enforcement_configuration_code,
    _bp_amazon_seller_brands.enforcement_configuration AS storefront_enforceable
  FROM _bp_enforcement_settings
  LEFT JOIN _bp_amazon_seller_brands
    ON _bp_enforcement_settings.bp_brand_id = _bp_amazon_seller_brands.bp_brand_id
), _Fix_Vendor_SKU AS (
  SELECT
    brand_id,
    cases_per_layer,
    cases_per_pallet,
    catalog_source,
    client_id,
    cost,
    created_at,
    created_by,
    default_cost,
    default_discount,
    deleted_at,
    deleted_by,
    id,
    hero,
    map,
    min_order_qty,
    name,
    old_upc,
    parent_upc,
    reorder_comments,
    reorder_status,
    srp,
    unit_lxwxh_inches,
    unit_weight_lb,
    units_per_case,
    upc,
    updated_at,
    updated_by,
    vendor_sku,
    wholesale_price,
    is_discontinued_status,
    amazon_seller_id,
    unit_count_type_id,
    unit_count,
    batch_id,
    batch_last_run,
    (
      CASE
        WHEN brand_id IN (75, 601, 602, 1270, 1936) AND LENGTH(vendor_sku) >= 5
        THEN NULL
        ELSE vendor_sku
      END
    ) AS vendor_sku_corrected
  FROM _UPCs
), _add_Channel AS (
  SELECT
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    country_id,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    bp_brand_id,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_id,
    storefront_enforceable,
    storefront_enforceable_code,
    (
      1
    ) AS marketplace_channel_id,
    (
      'Amazon'
    ) AS marketplace_channel
  FROM _get_latest_scraped_date
), _Group_By AS (
  SELECT
    storefront_id,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    partner,
    group_partner_brand,
    MAX(type) AS last_notice_type,
    MAX(date) AS last_notice_sent,
    MAX(notes_comments) AS last_note,
    MAX(invoice_id) AS invoice_id,
    MAX(job_id) AS job_id,
    MAX(usps_tracking) AS usps_tracking,
    MAX(delivery_status) AS delivery_status,
    MAX(delivery_date) AS delivery_date,
    LISTAGG(type, '') AS enforcement_history,
    MAX(error_status) AS c2m_error_status,
    MAX(recipient_address) AS recipient_address,
    LISTAGG(notes_comments, '') AS notes,
    MAX(brand) AS brand
  FROM _Add_Formula
  GROUP BY
    storefront_id,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    partner,
    group_partner_brand
), _seller_brands_cols AS (
  SELECT
    seller_id,
    enforcement_configuration_id,
    bp_brand_id,
    assigned_user AS brand_assigned_user,
    assigned_user_initials AS brand_assigned_user_initials,
    storefront_enforceable,
    brand_enforceable,
    assigned_user_id,
    country_id,
    enforce_by
  FROM _Join_Data_4
), _Group_by_UPC AS (
  SELECT
    upc,
    MAX(vendor_sku_corrected) AS vendor_code,
    MAX(map) AS catalog_map
  FROM _Fix_Vendor_SKU
  GROUP BY
    upc
), _limit_buster_country AS (
  SELECT
    _add_Channel.sales_country_id,
    _add_Channel.revenue,
    _add_Channel.asins_units,
    _add_Channel.revenue_brand,
    _add_Channel.asins_units_brand,
    _add_Channel.percent_mix_of_brand,
    _add_Channel.revenue_rank_r3mth,
    _add_Channel.revenue_distribution_r3mth,
    _add_Channel.scraped_date,
    _add_Channel.amazonid,
    _add_Channel.sellerid,
    _add_Channel.sellername,
    _add_Channel.storefront_name,
    _add_Channel.asin,
    _add_Channel.isquantityrestricted,
    _add_Channel.brand,
    _add_Channel.isfba,
    _add_Channel.upc,
    _add_Channel.upc_name,
    _add_Channel.msrp,
    _add_Channel.srp,
    _add_Channel.map,
    _add_Channel.parent_category,
    _add_Channel.child_category,
    _add_Channel.child_category_2,
    _add_Channel.child_category_3,
    _add_Channel.partner_name,
    _add_Channel.country_id,
    _add_Channel.offer_price,
    _add_Channel.offer_date_max_price,
    _add_Channel.units,
    _add_Channel.limit_buster_units,
    _add_Channel.redirect_asin,
    _add_Channel.created_date,
    _add_Channel.created_time,
    _add_Channel.sku_map,
    _add_Channel.sku_name,
    _add_Channel.buy_box_count,
    _add_Channel.partner_-_brand,
    _add_Channel.cod_condition,
    _add_Channel.unit_in_listing,
    _add_Channel.bp_brand_id,
    _add_Channel.asin_bp_enforceable,
    _add_Channel.asin_active,
    _add_Channel.asin_offers_scraper_enabled,
    _add_Channel.asin_hero_configuration,
    _add_Channel.asin_transparency_status,
    _add_Channel.country,
    _add_Channel.sales_channel,
    _add_Channel.date,
    _add_Channel.day_of_week,
    _add_Channel.month,
    _add_Channel.445_week,
    _add_Channel.445_week_number,
    _add_Channel.445_month,
    _add_Channel.445_month_number,
    _add_Channel.445_calendar,
    _add_Channel.445_year,
    _add_Channel.bbc_original_status,
    _add_Channel.bbc_2_8_22_status,
    _add_Channel.seller_id,
    _add_Channel.storefront_enforceable,
    _add_Channel.storefront_enforceable_code,
    _add_Channel.marketplace_channel_id,
    _add_Channel.marketplace_channel,
    _Select_name.id
  FROM _add_Channel
  INNER JOIN _Select_name
    ON _add_Channel.country_id = _Select_name.id
), _Add_Storefront_Enforceable AS (
  SELECT
    _limit_buster_country.sales_country_id,
    _limit_buster_country.revenue,
    _limit_buster_country.asins_units,
    _limit_buster_country.revenue_brand,
    _limit_buster_country.asins_units_brand,
    _limit_buster_country.percent_mix_of_brand,
    _limit_buster_country.revenue_rank_r3mth,
    _limit_buster_country.revenue_distribution_r3mth,
    _limit_buster_country.scraped_date,
    _limit_buster_country.amazonid,
    _limit_buster_country.sellerid,
    _limit_buster_country.sellername,
    _limit_buster_country.storefront_name,
    _limit_buster_country.asin,
    _limit_buster_country.isquantityrestricted,
    _limit_buster_country.brand,
    _limit_buster_country.isfba,
    _limit_buster_country.upc,
    _limit_buster_country.upc_name,
    _limit_buster_country.msrp,
    _limit_buster_country.srp,
    _limit_buster_country.map,
    _limit_buster_country.parent_category,
    _limit_buster_country.child_category,
    _limit_buster_country.child_category_2,
    _limit_buster_country.child_category_3,
    _limit_buster_country.partner_name,
    _limit_buster_country.country_id,
    _limit_buster_country.offer_price,
    _limit_buster_country.offer_date_max_price,
    _limit_buster_country.units,
    _limit_buster_country.limit_buster_units,
    _limit_buster_country.redirect_asin,
    _limit_buster_country.created_date,
    _limit_buster_country.created_time,
    _limit_buster_country.sku_map,
    _limit_buster_country.sku_name,
    _limit_buster_country.buy_box_count,
    _limit_buster_country.partner_-_brand,
    _limit_buster_country.cod_condition,
    _limit_buster_country.unit_in_listing,
    _limit_buster_country.bp_brand_id,
    _limit_buster_country.asin_bp_enforceable,
    _limit_buster_country.asin_active,
    _limit_buster_country.asin_offers_scraper_enabled,
    _limit_buster_country.asin_hero_configuration,
    _limit_buster_country.asin_transparency_status,
    _limit_buster_country.country,
    _limit_buster_country.sales_channel,
    _limit_buster_country.date,
    _limit_buster_country.day_of_week,
    _limit_buster_country.month,
    _limit_buster_country.445_week,
    _limit_buster_country.445_week_number,
    _limit_buster_country.445_month,
    _limit_buster_country.445_month_number,
    _limit_buster_country.445_calendar,
    _limit_buster_country.445_year,
    _limit_buster_country.bbc_original_status,
    _limit_buster_country.bbc_2_8_22_status,
    _limit_buster_country.seller_id,
    _limit_buster_country.storefront_enforceable,
    _limit_buster_country.storefront_enforceable_code,
    _limit_buster_country.marketplace_channel_id,
    _limit_buster_country.marketplace_channel,
    _limit_buster_country.id,
    _seller_brands_cols.enforcement_configuration_id,
    _seller_brands_cols.brand_assigned_user,
    _seller_brands_cols.brand_assigned_user_initials,
    _seller_brands_cols.storefront_enforceable AS seller_brands_cols_storefront_enforceable,
    _seller_brands_cols.brand_enforceable,
    _seller_brands_cols.assigned_user_id,
    _seller_brands_cols.enforce_by
  FROM _limit_buster_country
  LEFT JOIN _seller_brands_cols
    ON _limit_buster_country.sellerid = _seller_brands_cols.seller_id
    AND _limit_buster_country.bp_brand_id = _seller_brands_cols.bp_brand_id
    AND _limit_buster_country.country_id = _seller_brands_cols.country_id
), _Group_by_Partner AS (
  SELECT
    seller_id,
    enforcement_configuration_id,
    bp_brand_id,
    brand_assigned_user,
    brand_assigned_user_initials,
    storefront_enforceable,
    brand_enforceable,
    assigned_user_id,
    country_id,
    enforce_by,
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    brand,
    isfba,
    upc,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_brands_cols_storefront_enforceable,
    storefront_enforceable_code,
    marketplace_channel_id,
    marketplace_channel,
    id,
    (
      CASE WHEN enforce_by = 'Partner' THEN '-' ELSE brand END
    ) AS group_partner_brand
  FROM _Add_Storefront_Enforceable
), _Join_Data AS (
  SELECT
    _Group_by_Partner.seller_id,
    _Group_by_Partner.enforcement_configuration_id,
    _Group_by_Partner.bp_brand_id,
    _Group_by_Partner.brand_assigned_user,
    _Group_by_Partner.brand_assigned_user_initials,
    _Group_by_Partner.storefront_enforceable,
    _Group_by_Partner.brand_enforceable,
    _Group_by_Partner.assigned_user_id,
    _Group_by_Partner.country_id,
    _Group_by_Partner.enforce_by,
    _Group_by_Partner.sales_country_id,
    _Group_by_Partner.revenue,
    _Group_by_Partner.asins_units,
    _Group_by_Partner.revenue_brand,
    _Group_by_Partner.asins_units_brand,
    _Group_by_Partner.percent_mix_of_brand,
    _Group_by_Partner.revenue_rank_r3mth,
    _Group_by_Partner.revenue_distribution_r3mth,
    _Group_by_Partner.scraped_date,
    _Group_by_Partner.amazonid,
    _Group_by_Partner.sellerid,
    _Group_by_Partner.sellername,
    _Group_by_Partner.storefront_name,
    _Group_by_Partner.asin,
    _Group_by_Partner.isquantityrestricted,
    _Group_by_Partner.brand,
    _Group_by_Partner.isfba,
    _Group_by_Partner.upc,
    _Group_by_Partner.upc_name,
    _Group_by_Partner.msrp,
    _Group_by_Partner.srp,
    _Group_by_Partner.map,
    _Group_by_Partner.parent_category,
    _Group_by_Partner.child_category,
    _Group_by_Partner.child_category_2,
    _Group_by_Partner.child_category_3,
    _Group_by_Partner.partner_name,
    _Group_by_Partner.offer_price,
    _Group_by_Partner.offer_date_max_price,
    _Group_by_Partner.units,
    _Group_by_Partner.limit_buster_units,
    _Group_by_Partner.redirect_asin,
    _Group_by_Partner.created_date,
    _Group_by_Partner.created_time,
    _Group_by_Partner.sku_map,
    _Group_by_Partner.sku_name,
    _Group_by_Partner.buy_box_count,
    _Group_by_Partner.partner_-_brand,
    _Group_by_Partner.cod_condition,
    _Group_by_Partner.unit_in_listing,
    _Group_by_Partner.asin_bp_enforceable,
    _Group_by_Partner.asin_active,
    _Group_by_Partner.asin_offers_scraper_enabled,
    _Group_by_Partner.asin_hero_configuration,
    _Group_by_Partner.asin_transparency_status,
    _Group_by_Partner.country,
    _Group_by_Partner.sales_channel,
    _Group_by_Partner.date,
    _Group_by_Partner.day_of_week,
    _Group_by_Partner.month,
    _Group_by_Partner.445_week,
    _Group_by_Partner.445_week_number,
    _Group_by_Partner.445_month,
    _Group_by_Partner.445_month_number,
    _Group_by_Partner.445_calendar,
    _Group_by_Partner.445_year,
    _Group_by_Partner.bbc_original_status,
    _Group_by_Partner.bbc_2_8_22_status,
    _Group_by_Partner.seller_brands_cols_storefront_enforceable,
    _Group_by_Partner.storefront_enforceable_code,
    _Group_by_Partner.marketplace_channel_id,
    _Group_by_Partner.marketplace_channel,
    _Group_by_Partner.id,
    _Group_by_Partner.group_partner_brand,
    _Group_By.storefront_id,
    _Group_By.partner,
    _Group_By.last_notice_type,
    _Group_By.last_notice_sent,
    _Group_By.last_note,
    _Group_By.invoice_id,
    _Group_By.job_id,
    _Group_By.usps_tracking,
    _Group_By.delivery_status,
    _Group_By.delivery_date,
    _Group_By.enforcement_history,
    _Group_By.c2m_error_status,
    _Group_By.recipient_address,
    _Group_By.notes
  FROM _Group_by_Partner
  LEFT JOIN _Group_By
    ON _Group_by_Partner.sellerid = _Group_By.storefront_id
    AND _Group_by_Partner.marketplace_channel_id = _Group_By.marketplace_channel_id
    AND _Group_by_Partner.country_id = _Group_By.country_id
    AND _Group_by_Partner.partner_name = _Group_By.partner
    AND _Group_by_Partner.group_partner_brand = _Group_By.group_partner_brand
), _Join_Data_5 AS (
  SELECT
    _Group_by_UPC.upc,
    _Group_by_UPC.vendor_code,
    _Group_by_UPC.catalog_map,
    _Join_Data.storefront_id,
    _Join_Data.marketplace_channel_id,
    _Join_Data.marketplace_channel,
    _Join_Data.country_id,
    _Join_Data.country,
    _Join_Data.partner,
    _Join_Data.group_partner_brand,
    _Join_Data.last_notice_type,
    _Join_Data.last_notice_sent,
    _Join_Data.last_note,
    _Join_Data.invoice_id,
    _Join_Data.job_id,
    _Join_Data.usps_tracking,
    _Join_Data.delivery_status,
    _Join_Data.delivery_date,
    _Join_Data.enforcement_history,
    _Join_Data.c2m_error_status,
    _Join_Data.recipient_address,
    _Join_Data.notes,
    _Join_Data.brand,
    _Join_Data.seller_id,
    _Join_Data.enforcement_configuration_id,
    _Join_Data.bp_brand_id,
    _Join_Data.brand_assigned_user,
    _Join_Data.brand_assigned_user_initials,
    _Join_Data.storefront_enforceable,
    _Join_Data.brand_enforceable,
    _Join_Data.assigned_user_id,
    _Join_Data.enforce_by,
    _Join_Data.sales_country_id,
    _Join_Data.revenue,
    _Join_Data.asins_units,
    _Join_Data.revenue_brand,
    _Join_Data.asins_units_brand,
    _Join_Data.percent_mix_of_brand,
    _Join_Data.revenue_rank_r3mth,
    _Join_Data.revenue_distribution_r3mth,
    _Join_Data.scraped_date,
    _Join_Data.amazonid,
    _Join_Data.sellerid,
    _Join_Data.sellername,
    _Join_Data.storefront_name,
    _Join_Data.asin,
    _Join_Data.isquantityrestricted,
    _Join_Data.isfba,
    _Join_Data.upc_name,
    _Join_Data.msrp,
    _Join_Data.srp,
    _Join_Data.map,
    _Join_Data.parent_category,
    _Join_Data.child_category,
    _Join_Data.child_category_2,
    _Join_Data.child_category_3,
    _Join_Data.partner_name,
    _Join_Data.offer_price,
    _Join_Data.offer_date_max_price,
    _Join_Data.units,
    _Join_Data.limit_buster_units,
    _Join_Data.redirect_asin,
    _Join_Data.created_date,
    _Join_Data.created_time,
    _Join_Data.sku_map,
    _Join_Data.sku_name,
    _Join_Data.buy_box_count,
    _Join_Data.partner_-_brand,
    _Join_Data.cod_condition,
    _Join_Data.unit_in_listing,
    _Join_Data.asin_bp_enforceable,
    _Join_Data.asin_active,
    _Join_Data.asin_offers_scraper_enabled,
    _Join_Data.asin_hero_configuration,
    _Join_Data.asin_transparency_status,
    _Join_Data.country,
    _Join_Data.sales_channel,
    _Join_Data.date,
    _Join_Data.day_of_week,
    _Join_Data.month,
    _Join_Data.445_week,
    _Join_Data.445_week_number,
    _Join_Data.445_month,
    _Join_Data.445_month_number,
    _Join_Data.445_calendar,
    _Join_Data.445_year,
    _Join_Data.bbc_original_status,
    _Join_Data.bbc_2_8_22_status,
    _Join_Data.seller_brands_cols_storefront_enforceable,
    _Join_Data.storefront_enforceable_code,
    _Join_Data.id
  FROM _Group_by_UPC
  RIGHT JOIN _Join_Data
    ON _Group_by_UPC.upc = _Join_Data.upc
), _Add_Formula_4 AS (
  SELECT
    upc,
    vendor_code,
    catalog_map,
    storefront_id,
    marketplace_channel_id,
    marketplace_channel,
    country_id,
    country,
    partner,
    group_partner_brand,
    last_notice_type,
    last_notice_sent,
    last_note,
    invoice_id,
    job_id,
    usps_tracking,
    delivery_status,
    delivery_date,
    enforcement_history,
    c2m_error_status,
    recipient_address,
    notes,
    brand,
    seller_id,
    enforcement_configuration_id,
    bp_brand_id,
    brand_assigned_user,
    brand_assigned_user_initials,
    storefront_enforceable,
    brand_enforceable,
    assigned_user_id,
    enforce_by,
    sales_country_id,
    revenue,
    asins_units,
    revenue_brand,
    asins_units_brand,
    percent_mix_of_brand,
    revenue_rank_r3mth,
    revenue_distribution_r3mth,
    scraped_date,
    amazonid,
    sellerid,
    sellername,
    storefront_name,
    asin,
    isquantityrestricted,
    isfba,
    upc_name,
    msrp,
    srp,
    map,
    parent_category,
    child_category,
    child_category_2,
    child_category_3,
    partner_name,
    offer_price,
    offer_date_max_price,
    units,
    limit_buster_units,
    redirect_asin,
    created_date,
    created_time,
    sku_map,
    sku_name,
    buy_box_count,
    partner_-_brand,
    cod_condition,
    unit_in_listing,
    asin_bp_enforceable,
    asin_active,
    asin_offers_scraper_enabled,
    asin_hero_configuration,
    asin_transparency_status,
    country,
    sales_channel,
    date,
    day_of_week,
    month,
    445_week,
    445_week_number,
    445_month,
    445_month_number,
    445_calendar,
    445_year,
    bbc_original_status,
    bbc_2_8_22_status,
    seller_brands_cols_storefront_enforceable,
    storefront_enforceable_code,
    id,
    (
      CASE WHEN sellername = 'XXXXXXXXX' THEN CURRENT_DATE ELSE '' END
    ) AS enter_date,
    (
      CASE WHEN sellername = 'XXXXXXXXX' THEN CURRENT_DATE ELSE '' END
    ) AS new_notes,
    (
      CASE WHEN sellername = 'XXXXXXXXX' THEN CURRENT_DATE ELSE '' END
    ) AS new_invoice_id
  FROM _Join_Data_5
), _Enforcement_DS AS (
  SELECT
    *
  FROM _Add_Formula_4
)
SELECT
  *
FROM _Enforcement_DS