/*
================================================================================
DOMO DATAFLOW TRANSLATION
================================================================================
Dataflow ID: 534
Dataflow Name: IT Enforcement DS
Target Dialect: MYSQL

TRANSLATION SUMMARY:
  Total Actions: 28
  Successful: 28
  Failed: 0
  Unique Action Types: 5
  Action Types: ExpressionEvaluator, GroupBy, LoadFromVault, MergeJoin, PublishToVault
  Pipelines: 8

Generated: 2025-07-02 10:25:37
================================================================================
*/

WITH _IT_Limit_Buster_Inventory_DS AS (
  SELECT `scraped_date`, `amazonID`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `Brand`, `isFBA`, `upc`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `Date`, `Day of Week`, `Month`, `445 Week`, `445 Week Number`, `445 Month`, `445 Month Number`, `445 Calendar`, `445 Year`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS`, `ASIN Link`, `Inventory Value`, `Offer Type`, `Price Δ (%) - map`, `Price Δ (€) - map`, `Authorized Sellers`, `MAP / MSRP Exceptions`, `MAP Violations (sku map)`, `Storefront DB URL` FROM IT_Limit_Buster_Inventory_DS
),

_BP_PlatformNotices_Sent AS (
  SELECT `Staff`, `Brand`, `Storefront ID`, `storefront_name`, `ASIN`, `Date of First Message`, `Complaint Date`, `Complaint ID`, `Message`, `Column_10` FROM BP_PlatformNotices_Sent
),

_bp_enforcements AS (
  SELECT `Staff`, `Partner`, `Brand`, `marketplace_channel_id`, `marketplace_channel`, `country_id`, `country`, `Storefront ID`, `storefront_name`, `Date`, `Type`, `Notes/Comments`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Response Received`, `Order Cost`, `USPS Tracking Type`, `Recipient Address`, `Delivered City`, `ERROR_STATUS`, `RunDateTime`, `return Receipt Downloaded?`, `enforce_by_brand`, `enforce_by`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM bp_enforcements
),

_Amazon_Sellers AS (
  SELECT `internal_id`, `seller_id`, `name`, `storefront_name`, `amazon_businessname`, `amazon_businessaddress`, `last_scraped_at`, `zip_code`, `country`, `state`, `city`, `address_line1`, `address_line2`, `review_count`, `review_count_last_30`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM Amazon_Sellers
),

_Amazon_Sellers_Addresses AS (
  SELECT `internal_id`, `seller_id`, `marketplace`, `storefront_name`, `address`, `city`, `state`, `country`, `zip`, `created_at`, `updated_at`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM Amazon_Sellers_Addresses
),

_Amazon_Sellers_Details_Contacts AS (
  SELECT `internal_id`, `seller_id`, `marketplace`, `storefront_name`, `email`, `extension`, `phone`, `first_name`, `last_name`, `created_at`, `updated_at`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM Amazon_Sellers_Details_Contacts
),

_ASIN_Buy_Box_Status AS (
  SELECT `asin`, `scraped_date`, `Brand`, `partner name`, `upc`, `upc_name`, `country_id`, `brand_assigned_user_initials`, `brand_assigned_user`, `is_buy_box_#_sum`, `MAP`, `MSRP`, `Offer Price`, `buy_box_status`, `Country PanEU`, `% Active by day`, `% Suppressed by day` FROM ASIN_Buy_Box_Status
),

_UPCs AS (
  SELECT `brand_id`, `cases_per_layer`, `cases_per_pallet`, `catalog_source`, `client_id`, `cost`, `created_at`, `created_by`, `default_cost`, `default_discount`, `deleted_at`, `deleted_by`, `id`, `hero`, `map`, `min_order_qty`, `name`, `old_upc`, `parent_upc`, `reorder_comments`, `reorder_status`, `srp`, `unit_lxwxh_inches`, `unit_weight_lb`, `units_per_case`, `upc`, `updated_at`, `updated_by`, `vendor_sku`, `wholesale_price`, `is_discontinued_status`, `amazon_seller_id`, `unit_count_type_id`, `unit_count`, `_BATCH_ID_`, `_BATCH_LAST_RUN_` FROM UPCs
),

_Join_Data_6 AS (
  SELECT _bp_enforcements.`Staff`, _bp_enforcements.`Partner`, _bp_enforcements.`Brand`, _bp_enforcements.`marketplace_channel_id`, _bp_enforcements.`marketplace_channel`, _bp_enforcements.`country_id`, _bp_enforcements.`country`, _bp_enforcements.`Storefront ID`, _bp_enforcements.`storefront_name`, _bp_enforcements.`Date`, _bp_enforcements.`Type`, _bp_enforcements.`Notes/Comments`, _bp_enforcements.`Invoice ID`, _bp_enforcements.`Job ID`, _bp_enforcements.`USPS Tracking`, _bp_enforcements.`Delivery Status`, _bp_enforcements.`Delivery Date`, _bp_enforcements.`Response Received`, _bp_enforcements.`Order Cost`, _bp_enforcements.`USPS Tracking Type`, _bp_enforcements.`Recipient Address`, _bp_enforcements.`Delivered City`, _bp_enforcements.`ERROR_STATUS`, _bp_enforcements.`RunDateTime`, _bp_enforcements.`return Receipt Downloaded?`, _bp_enforcements.`enforce_by_brand`, _bp_enforcements.`enforce_by`, _bp_enforcements.`_BATCH_ID_`, _bp_enforcements.`_BATCH_LAST_RUN_`, _BP_PlatformNotices_Sent.`ASIN`, _BP_PlatformNotices_Sent.`Date of First Message`, _BP_PlatformNotices_Sent.`Complaint Date`, _BP_PlatformNotices_Sent.`Complaint ID`, _BP_PlatformNotices_Sent.`Message`, _BP_PlatformNotices_Sent.`Column_10` FROM _bp_enforcements LEFT JOIN _BP_PlatformNotices_Sent ON _bp_enforcements.`Brand` = _BP_PlatformNotices_Sent.`Brand` AND _bp_enforcements.`Storefront ID` = _BP_PlatformNotices_Sent.`Storefront ID`
),

_Group_By_2 AS (
  SELECT `internal_id`, MAX(`address`) AS `Address`, MAX(`city`) AS `City`, MAX(`state`) AS `State`, MAX(`zip`) AS `Zip`, MAX(`country`) AS `Country` FROM _Amazon_Sellers_Addresses GROUP BY `internal_id`
),

_Add_Formula_3 AS (
  SELECT `internal_id`, `seller_id`, `marketplace`, `storefront_name`, `email`, `extension`, `phone`, `first_name`, `last_name`, `created_at`, `updated_at`, `_BATCH_ID_`, `_BATCH_LAST_RUN_`, (CONCAT(`first_name`,' ',`last_name`)) AS `Seller Contact` FROM _Amazon_Sellers_Details_Contacts
),

_Group_By_6 AS (
  SELECT `asin`, MAX(`buy_box_status`) AS `buy_box_status`, MAX(`scraped_date`) AS `buybox_status_date` FROM _ASIN_Buy_Box_Status GROUP BY `asin`
),

_Add_Formula_2 AS (
  SELECT `brand_id`, `cases_per_layer`, `cases_per_pallet`, `catalog_source`, `client_id`, `cost`, `created_at`, `created_by`, `default_cost`, `default_discount`, `deleted_at`, `deleted_by`, `id`, `hero`, `map`, `min_order_qty`, `name`, `old_upc`, `parent_upc`, `reorder_comments`, `reorder_status`, `srp`, `unit_lxwxh_inches`, `unit_weight_lb`, `units_per_case`, `upc`, `updated_at`, `updated_by`, `vendor_sku`, `wholesale_price`, `is_discontinued_status`, `amazon_seller_id`, `unit_count_type_id`, `unit_count`, `_BATCH_ID_`, `_BATCH_LAST_RUN_`, (CASE when `brand_id` IN (75,601,602,1270,1936) AND LENGTH(`vendor_sku`) >= 5 then null else `vendor_sku` END) AS `Vendor_SKU_Corrected` FROM _UPCs
),

_Group_By AS (
  SELECT `Brand`, `Storefront ID`, MAX(`Type`) AS `Last Notice Type`, MAX(`Date`) AS `Last Notice Sent`, GROUP_CONCAT(`Notes/Comments`) AS `Notes`, MAX(`Invoice ID`) AS `Invoice ID`, MAX(`Job ID`) AS `Job ID`, MAX(`USPS Tracking`) AS `USPS Tracking`, MAX(`Delivery Status`) AS `Delivery Status`, MAX(`Delivery Date`) AS `Delivery Date`, GROUP_CONCAT(`Type`) AS `Enforcement History`, MAX(`ERROR_STATUS`) AS `C2M ERROR_STATUS`, MAX(`Recipient Address`) AS `Recipient Address`, MAX(`Date of First Message`) AS `Platform Sent?` FROM _Join_Data_6 GROUP BY `Brand`, `Storefront ID`
),

_Join_Data_2 AS (
  SELECT _Amazon_Sellers.`internal_id`, _Amazon_Sellers.`seller_id`, _Amazon_Sellers.`name`, _Amazon_Sellers.`storefront_name`, _Amazon_Sellers.`amazon_businessname`, _Amazon_Sellers.`amazon_businessaddress`, _Amazon_Sellers.`last_scraped_at`, _Amazon_Sellers.`zip_code`, _Amazon_Sellers.`country`, _Amazon_Sellers.`state`, _Amazon_Sellers.`city`, _Amazon_Sellers.`address_line1`, _Amazon_Sellers.`address_line2`, _Amazon_Sellers.`review_count`, _Amazon_Sellers.`review_count_last_30`, _Amazon_Sellers.`_BATCH_ID_`, _Amazon_Sellers.`_BATCH_LAST_RUN_`, _Group_By_2.`Address`, _Group_By_2.`City` AS `Violator City`, _Group_By_2.`State` AS `Violator State`, _Group_By_2.`Zip`, _Group_By_2.`Country` AS `Violator Country` FROM _Amazon_Sellers LEFT JOIN _Group_By_2 ON _Amazon_Sellers.`internal_id` = _Group_By_2.`internal_id`
),

_Group_By_3 AS (
  SELECT `internal_id`, MAX(`email`) AS `Email`, MAX(`Seller Contact`) AS `Seller Contact`, MAX(`phone`) AS `Phone` FROM _Add_Formula_3 GROUP BY `internal_id`
),

_Group_By_4 AS (
  SELECT `upc`, MAX(`Vendor_SKU_Corrected`) AS `vendor_code` FROM _Add_Formula_2 GROUP BY `upc`
),

_Join_Data AS (
  SELECT _IT_Limit_Buster_Inventory_DS.`scraped_date`, _IT_Limit_Buster_Inventory_DS.`amazonID`, _IT_Limit_Buster_Inventory_DS.`sellerId`, _IT_Limit_Buster_Inventory_DS.`sellerName`, _IT_Limit_Buster_Inventory_DS.`storefront_name`, _IT_Limit_Buster_Inventory_DS.`asin`, _IT_Limit_Buster_Inventory_DS.`isQuantityRestricted`, _IT_Limit_Buster_Inventory_DS.`Brand`, _IT_Limit_Buster_Inventory_DS.`isFBA`, _IT_Limit_Buster_Inventory_DS.`upc`, _IT_Limit_Buster_Inventory_DS.`upc_name`, _IT_Limit_Buster_Inventory_DS.`msrp`, _IT_Limit_Buster_Inventory_DS.`srp`, _IT_Limit_Buster_Inventory_DS.`map`, _IT_Limit_Buster_Inventory_DS.`parent_category`, _IT_Limit_Buster_Inventory_DS.`child_category`, _IT_Limit_Buster_Inventory_DS.`child_category_2`, _IT_Limit_Buster_Inventory_DS.`child_category_3`, _IT_Limit_Buster_Inventory_DS.`partner name`, _IT_Limit_Buster_Inventory_DS.`country_id`, _IT_Limit_Buster_Inventory_DS.`offer_price`, _IT_Limit_Buster_Inventory_DS.`offer_date_max_price`, _IT_Limit_Buster_Inventory_DS.`Units`, _IT_Limit_Buster_Inventory_DS.`Limit Buster Units`, _IT_Limit_Buster_Inventory_DS.`redirect_asin`, _IT_Limit_Buster_Inventory_DS.`created_date`, _IT_Limit_Buster_Inventory_DS.`created_time`, _IT_Limit_Buster_Inventory_DS.`sku_map`, _IT_Limit_Buster_Inventory_DS.`sku_name`, _IT_Limit_Buster_Inventory_DS.`buy_box_count`, _IT_Limit_Buster_Inventory_DS.`Partner - Brand`, _IT_Limit_Buster_Inventory_DS.`Date`, _IT_Limit_Buster_Inventory_DS.`Day of Week`, _IT_Limit_Buster_Inventory_DS.`Month`, _IT_Limit_Buster_Inventory_DS.`445 Week`, _IT_Limit_Buster_Inventory_DS.`445 Week Number`, _IT_Limit_Buster_Inventory_DS.`445 Month`, _IT_Limit_Buster_Inventory_DS.`445 Month Number`, _IT_Limit_Buster_Inventory_DS.`445 Calendar`, _IT_Limit_Buster_Inventory_DS.`445 Year`, _IT_Limit_Buster_Inventory_DS.`BBC_ORIGINAL_STATUS`, _IT_Limit_Buster_Inventory_DS.`BBC_2_8_22_STATUS`, _IT_Limit_Buster_Inventory_DS.`ASIN Link`, _IT_Limit_Buster_Inventory_DS.`Inventory Value`, _IT_Limit_Buster_Inventory_DS.`Offer Type`, _IT_Limit_Buster_Inventory_DS.`Price Δ (%) - map`, _IT_Limit_Buster_Inventory_DS.`Price Δ (€) - map`, _IT_Limit_Buster_Inventory_DS.`Authorized Sellers`, _IT_Limit_Buster_Inventory_DS.`MAP / MSRP Exceptions`, _IT_Limit_Buster_Inventory_DS.`MAP Violations (sku map)`, _IT_Limit_Buster_Inventory_DS.`Storefront DB URL`, _Group_By.`Storefront ID`, _Group_By.`Last Notice Type`, _Group_By.`Last Notice Sent`, _Group_By.`Notes`, _Group_By.`Invoice ID`, _Group_By.`Job ID`, _Group_By.`USPS Tracking`, _Group_By.`Delivery Status`, _Group_By.`Delivery Date`, _Group_By.`Enforcement History`, _Group_By.`C2M ERROR_STATUS`, _Group_By.`Recipient Address`, _Group_By.`Platform Sent?` FROM _IT_Limit_Buster_Inventory_DS LEFT JOIN _Group_By ON _IT_Limit_Buster_Inventory_DS.`Brand` = _Group_By.`Brand` AND _IT_Limit_Buster_Inventory_DS.`sellerId` = _Group_By.`Storefront ID`
),

_Join_Data_3 AS (
  SELECT _Join_Data_2.`internal_id`, _Join_Data_2.`seller_id`, _Join_Data_2.`name`, _Join_Data_2.`storefront_name`, _Join_Data_2.`amazon_businessname`, _Join_Data_2.`amazon_businessaddress`, _Join_Data_2.`last_scraped_at`, _Join_Data_2.`zip_code`, _Join_Data_2.`country`, _Join_Data_2.`state`, _Join_Data_2.`city`, _Join_Data_2.`address_line1`, _Join_Data_2.`address_line2`, _Join_Data_2.`review_count`, _Join_Data_2.`review_count_last_30`, _Join_Data_2.`_BATCH_ID_`, _Join_Data_2.`_BATCH_LAST_RUN_`, _Join_Data_2.`Address`, _Join_Data_2.`Violator City`, _Join_Data_2.`Violator State`, _Join_Data_2.`Zip`, _Join_Data_2.`Violator Country`, _Group_By_3.`Email`, _Group_By_3.`Seller Contact`, _Group_By_3.`Phone` FROM _Join_Data_2 LEFT JOIN _Group_By_3 ON _Join_Data_2.`internal_id` = _Group_By_3.`internal_id`
),

_Group_By_1 AS (
  SELECT `Brand`, `amazonID`, MIN(`scraped_date`) AS `First Seen Date`, MAX(`scraped_date`) AS `Last Seen Date` FROM _Join_Data GROUP BY `Brand`, `amazonID`
),

_Add_Formula_1 AS (
  SELECT `internal_id`, `seller_id`, `name`, `storefront_name`, `amazon_businessname`, `amazon_businessaddress`, `last_scraped_at`, `zip_code`, `country`, `state`, `city`, `address_line1`, `address_line2`, `review_count`, `review_count_last_30`, `_BATCH_ID_`, `_BATCH_LAST_RUN_`, `Address`, `Violator City`, `Violator State`, `Zip`, `Violator Country`, `Email`, `Seller Contact`, `Phone`, (case when `Email` is NULL then 'No' else 'Yes' end) AS `Email Available?`, (case when `Address` is NULL then 'No' else 'Yes' end) AS `Address Available?` FROM _Join_Data_3
),

_Join_Data_1 AS (
  SELECT _Join_Data.`scraped_date`, _Join_Data.`amazonID`, _Join_Data.`sellerId`, _Join_Data.`sellerName`, _Join_Data.`storefront_name`, _Join_Data.`asin`, _Join_Data.`isQuantityRestricted`, _Join_Data.`Brand`, _Join_Data.`isFBA`, _Join_Data.`upc`, _Join_Data.`upc_name`, _Join_Data.`msrp`, _Join_Data.`srp`, _Join_Data.`map`, _Join_Data.`parent_category`, _Join_Data.`child_category`, _Join_Data.`child_category_2`, _Join_Data.`child_category_3`, _Join_Data.`partner name`, _Join_Data.`country_id`, _Join_Data.`offer_price`, _Join_Data.`offer_date_max_price`, _Join_Data.`Units`, _Join_Data.`Limit Buster Units`, _Join_Data.`redirect_asin`, _Join_Data.`created_date`, _Join_Data.`created_time`, _Join_Data.`sku_map`, _Join_Data.`sku_name`, _Join_Data.`buy_box_count`, _Join_Data.`Partner - Brand`, _Join_Data.`Date`, _Join_Data.`Day of Week`, _Join_Data.`Month`, _Join_Data.`445 Week`, _Join_Data.`445 Week Number`, _Join_Data.`445 Month`, _Join_Data.`445 Month Number`, _Join_Data.`445 Calendar`, _Join_Data.`445 Year`, _Join_Data.`BBC_ORIGINAL_STATUS`, _Join_Data.`BBC_2_8_22_STATUS`, _Join_Data.`ASIN Link`, _Join_Data.`Inventory Value`, _Join_Data.`Offer Type`, _Join_Data.`Price Δ (%) - map`, _Join_Data.`Price Δ (€) - map`, _Join_Data.`Authorized Sellers`, _Join_Data.`MAP / MSRP Exceptions`, _Join_Data.`MAP Violations (sku map)`, _Join_Data.`Storefront DB URL`, _Join_Data.`Storefront ID`, _Join_Data.`Last Notice Type`, _Join_Data.`Last Notice Sent`, _Join_Data.`Notes`, _Join_Data.`Invoice ID`, _Join_Data.`Job ID`, _Join_Data.`USPS Tracking`, _Join_Data.`Delivery Status`, _Join_Data.`Delivery Date`, _Join_Data.`Enforcement History`, _Join_Data.`C2M ERROR_STATUS`, _Join_Data.`Recipient Address`, _Join_Data.`Platform Sent?`, _Group_By_1.`First Seen Date`, _Group_By_1.`Last Seen Date` FROM _Join_Data LEFT JOIN _Group_By_1 ON _Join_Data.`amazonID` = _Group_By_1.`amazonID` AND _Join_Data.`Brand` = _Group_By_1.`Brand`
),

_Add_Formula AS (
  SELECT `Brand`, `amazonID`, `First Seen Date`, `Last Seen Date`, `scraped_date`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `isFBA`, `upc`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `Date`, `Day of Week`, `Month`, `445 Week`, `445 Week Number`, `445 Month`, `445 Month Number`, `445 Calendar`, `445 Year`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS`, `ASIN Link`, `Inventory Value`, `Offer Type`, `Price Δ (%) - map`, `Price Δ (€) - map`, `Authorized Sellers`, `MAP / MSRP Exceptions`, `MAP Violations (sku map)`, `Storefront DB URL`, `Storefront ID`, `Last Notice Type`, `Last Notice Sent`, `Notes`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Enforcement History`, `C2M ERROR_STATUS`, `Recipient Address`, `Platform Sent?`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 7 DAY) then 1 else 0 END) AS `New Storefront within 7 days`, (DATEDIFF(`First Seen Date`,CURRENT_DATE())) AS `Days since first listing`, (DATEDIFF(`Last Seen Date`,CURRENT_DATE())) AS `Days since last listing`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 1 DAY) then 1 else 0 END) AS `New Storefront within 2 days`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 14 DAY) then 1 else 0 END) AS `New Storefront within 14 days`, (CASE WHEN `First Seen Date` >= date_sub(CURRENT_DATE(),interval 28 DAY) then 1 else 0 END) AS `New Storefront within 28 days` FROM _Join_Data_1
),

_Join_Data_4 AS (
  SELECT _Add_Formula.`Brand`, _Add_Formula.`amazonID`, _Add_Formula.`First Seen Date`, _Add_Formula.`Last Seen Date`, _Add_Formula.`scraped_date`, _Add_Formula.`sellerId`, _Add_Formula.`sellerName`, _Add_Formula.`storefront_name`, _Add_Formula.`asin`, _Add_Formula.`isQuantityRestricted`, _Add_Formula.`isFBA`, _Add_Formula.`upc`, _Add_Formula.`upc_name`, _Add_Formula.`msrp`, _Add_Formula.`srp`, _Add_Formula.`map`, _Add_Formula.`parent_category`, _Add_Formula.`child_category`, _Add_Formula.`child_category_2`, _Add_Formula.`child_category_3`, _Add_Formula.`partner name`, _Add_Formula.`country_id`, _Add_Formula.`offer_price`, _Add_Formula.`offer_date_max_price`, _Add_Formula.`Units`, _Add_Formula.`Limit Buster Units`, _Add_Formula.`redirect_asin`, _Add_Formula.`created_date`, _Add_Formula.`created_time`, _Add_Formula.`sku_map`, _Add_Formula.`sku_name`, _Add_Formula.`buy_box_count`, _Add_Formula.`Partner - Brand`, _Add_Formula.`Date`, _Add_Formula.`Day of Week`, _Add_Formula.`Month`, _Add_Formula.`445 Week`, _Add_Formula.`445 Week Number`, _Add_Formula.`445 Month`, _Add_Formula.`445 Month Number`, _Add_Formula.`445 Calendar`, _Add_Formula.`445 Year`, _Add_Formula.`BBC_ORIGINAL_STATUS`, _Add_Formula.`BBC_2_8_22_STATUS`, _Add_Formula.`ASIN Link`, _Add_Formula.`Inventory Value`, _Add_Formula.`Offer Type`, _Add_Formula.`Price Δ (%) - map`, _Add_Formula.`Price Δ (€) - map`, _Add_Formula.`Authorized Sellers`, _Add_Formula.`MAP / MSRP Exceptions`, _Add_Formula.`MAP Violations (sku map)`, _Add_Formula.`Storefront DB URL`, _Add_Formula.`Storefront ID`, _Add_Formula.`Last Notice Type`, _Add_Formula.`Last Notice Sent`, _Add_Formula.`Notes`, _Add_Formula.`Invoice ID`, _Add_Formula.`Job ID`, _Add_Formula.`USPS Tracking`, _Add_Formula.`Delivery Status`, _Add_Formula.`Delivery Date`, _Add_Formula.`Enforcement History`, _Add_Formula.`C2M ERROR_STATUS`, _Add_Formula.`Recipient Address`, _Add_Formula.`Platform Sent?`, _Add_Formula.`New Storefront within 7 days`, _Add_Formula.`Days since first listing`, _Add_Formula.`Days since last listing`, _Add_Formula.`New Storefront within 2 days`, _Add_Formula.`New Storefront within 14 days`, _Add_Formula.`New Storefront within 28 days`, _Add_Formula_1.`internal_id`, _Add_Formula_1.`seller_id`, _Add_Formula_1.`name`, _Add_Formula_1.`last_scraped_at`, _Add_Formula_1.`address_line1`, _Add_Formula_1.`address_line2`, _Add_Formula_1.`review_count`, _Add_Formula_1.`review_count_last_30`, _Add_Formula_1.`_BATCH_ID_`, _Add_Formula_1.`_BATCH_LAST_RUN_`, _Add_Formula_1.`Address`, _Add_Formula_1.`Violator City`, _Add_Formula_1.`Violator State`, _Add_Formula_1.`Zip`, _Add_Formula_1.`Violator Country`, _Add_Formula_1.`Email`, _Add_Formula_1.`Seller Contact`, _Add_Formula_1.`Phone`, _Add_Formula_1.`Email Available?`, _Add_Formula_1.`Address Available?` FROM _Add_Formula LEFT JOIN _Add_Formula_1 ON _Add_Formula.`amazonID` = _Add_Formula_1.`seller_id`
),

_Join_Data_5 AS (
  SELECT _Join_Data_4.`Brand`, _Join_Data_4.`amazonID`, _Join_Data_4.`First Seen Date`, _Join_Data_4.`Last Seen Date`, _Join_Data_4.`scraped_date`, _Join_Data_4.`sellerId`, _Join_Data_4.`sellerName`, _Join_Data_4.`storefront_name`, _Join_Data_4.`asin`, _Join_Data_4.`isQuantityRestricted`, _Join_Data_4.`isFBA`, _Join_Data_4.`upc`, _Join_Data_4.`upc_name`, _Join_Data_4.`msrp`, _Join_Data_4.`srp`, _Join_Data_4.`map`, _Join_Data_4.`parent_category`, _Join_Data_4.`child_category`, _Join_Data_4.`child_category_2`, _Join_Data_4.`child_category_3`, _Join_Data_4.`partner name`, _Join_Data_4.`country_id`, _Join_Data_4.`offer_price`, _Join_Data_4.`offer_date_max_price`, _Join_Data_4.`Units`, _Join_Data_4.`Limit Buster Units`, _Join_Data_4.`redirect_asin`, _Join_Data_4.`created_date`, _Join_Data_4.`created_time`, _Join_Data_4.`sku_map`, _Join_Data_4.`sku_name`, _Join_Data_4.`buy_box_count`, _Join_Data_4.`Partner - Brand`, _Join_Data_4.`Date`, _Join_Data_4.`Day of Week`, _Join_Data_4.`Month`, _Join_Data_4.`445 Week`, _Join_Data_4.`445 Week Number`, _Join_Data_4.`445 Month`, _Join_Data_4.`445 Month Number`, _Join_Data_4.`445 Calendar`, _Join_Data_4.`445 Year`, _Join_Data_4.`BBC_ORIGINAL_STATUS`, _Join_Data_4.`BBC_2_8_22_STATUS`, _Join_Data_4.`ASIN Link`, _Join_Data_4.`Inventory Value`, _Join_Data_4.`Offer Type`, _Join_Data_4.`Price Δ (%) - map`, _Join_Data_4.`Price Δ (€) - map`, _Join_Data_4.`Authorized Sellers`, _Join_Data_4.`MAP / MSRP Exceptions`, _Join_Data_4.`MAP Violations (sku map)`, _Join_Data_4.`Storefront DB URL`, _Join_Data_4.`Storefront ID`, _Join_Data_4.`Last Notice Type`, _Join_Data_4.`Last Notice Sent`, _Join_Data_4.`Notes`, _Join_Data_4.`Invoice ID`, _Join_Data_4.`Job ID`, _Join_Data_4.`USPS Tracking`, _Join_Data_4.`Delivery Status`, _Join_Data_4.`Delivery Date`, _Join_Data_4.`Enforcement History`, _Join_Data_4.`C2M ERROR_STATUS`, _Join_Data_4.`Recipient Address`, _Join_Data_4.`Platform Sent?`, _Join_Data_4.`New Storefront within 7 days`, _Join_Data_4.`Days since first listing`, _Join_Data_4.`Days since last listing`, _Join_Data_4.`New Storefront within 2 days`, _Join_Data_4.`New Storefront within 14 days`, _Join_Data_4.`New Storefront within 28 days`, _Join_Data_4.`internal_id`, _Join_Data_4.`seller_id`, _Join_Data_4.`name`, _Join_Data_4.`last_scraped_at`, _Join_Data_4.`address_line1`, _Join_Data_4.`address_line2`, _Join_Data_4.`review_count`, _Join_Data_4.`review_count_last_30`, _Join_Data_4.`_BATCH_ID_`, _Join_Data_4.`_BATCH_LAST_RUN_`, _Join_Data_4.`Address`, _Join_Data_4.`Violator City`, _Join_Data_4.`Violator State`, _Join_Data_4.`Zip`, _Join_Data_4.`Violator Country`, _Join_Data_4.`Email`, _Join_Data_4.`Seller Contact`, _Join_Data_4.`Phone`, _Join_Data_4.`Email Available?`, _Join_Data_4.`Address Available?`, _Group_By_6.`buy_box_status`, _Group_By_6.`buybox_status_date` FROM _Join_Data_4 LEFT JOIN _Group_By_6 ON _Join_Data_4.`asin` = _Group_By_6.`asin`
),

_Add_Vendor_Code AS (
  SELECT _Join_Data_5.`Brand`, _Join_Data_5.`amazonID`, _Join_Data_5.`First Seen Date`, _Join_Data_5.`Last Seen Date`, _Join_Data_5.`scraped_date`, _Join_Data_5.`sellerId`, _Join_Data_5.`sellerName`, _Join_Data_5.`storefront_name`, _Join_Data_5.`asin`, _Join_Data_5.`isQuantityRestricted`, _Join_Data_5.`isFBA`, _Join_Data_5.`upc`, _Join_Data_5.`upc_name`, _Join_Data_5.`msrp`, _Join_Data_5.`srp`, _Join_Data_5.`map`, _Join_Data_5.`parent_category`, _Join_Data_5.`child_category`, _Join_Data_5.`child_category_2`, _Join_Data_5.`child_category_3`, _Join_Data_5.`partner name`, _Join_Data_5.`country_id`, _Join_Data_5.`offer_price`, _Join_Data_5.`offer_date_max_price`, _Join_Data_5.`Units`, _Join_Data_5.`Limit Buster Units`, _Join_Data_5.`redirect_asin`, _Join_Data_5.`created_date`, _Join_Data_5.`created_time`, _Join_Data_5.`sku_map`, _Join_Data_5.`sku_name`, _Join_Data_5.`buy_box_count`, _Join_Data_5.`Partner - Brand`, _Join_Data_5.`Date`, _Join_Data_5.`Day of Week`, _Join_Data_5.`Month`, _Join_Data_5.`445 Week`, _Join_Data_5.`445 Week Number`, _Join_Data_5.`445 Month`, _Join_Data_5.`445 Month Number`, _Join_Data_5.`445 Calendar`, _Join_Data_5.`445 Year`, _Join_Data_5.`BBC_ORIGINAL_STATUS`, _Join_Data_5.`BBC_2_8_22_STATUS`, _Join_Data_5.`ASIN Link`, _Join_Data_5.`Inventory Value`, _Join_Data_5.`Offer Type`, _Join_Data_5.`Price Δ (%) - map`, _Join_Data_5.`Price Δ (€) - map`, _Join_Data_5.`Authorized Sellers`, _Join_Data_5.`MAP / MSRP Exceptions`, _Join_Data_5.`MAP Violations (sku map)`, _Join_Data_5.`Storefront DB URL`, _Join_Data_5.`Storefront ID`, _Join_Data_5.`Last Notice Type`, _Join_Data_5.`Last Notice Sent`, _Join_Data_5.`Notes`, _Join_Data_5.`Invoice ID`, _Join_Data_5.`Job ID`, _Join_Data_5.`USPS Tracking`, _Join_Data_5.`Delivery Status`, _Join_Data_5.`Delivery Date`, _Join_Data_5.`Enforcement History`, _Join_Data_5.`C2M ERROR_STATUS`, _Join_Data_5.`Recipient Address`, _Join_Data_5.`Platform Sent?`, _Join_Data_5.`New Storefront within 7 days`, _Join_Data_5.`Days since first listing`, _Join_Data_5.`Days since last listing`, _Join_Data_5.`New Storefront within 2 days`, _Join_Data_5.`New Storefront within 14 days`, _Join_Data_5.`New Storefront within 28 days`, _Join_Data_5.`internal_id`, _Join_Data_5.`seller_id`, _Join_Data_5.`name`, _Join_Data_5.`last_scraped_at`, _Join_Data_5.`address_line1`, _Join_Data_5.`address_line2`, _Join_Data_5.`review_count`, _Join_Data_5.`review_count_last_30`, _Join_Data_5.`_BATCH_ID_`, _Join_Data_5.`_BATCH_LAST_RUN_`, _Join_Data_5.`Address`, _Join_Data_5.`Violator City`, _Join_Data_5.`Violator State`, _Join_Data_5.`Zip`, _Join_Data_5.`Violator Country`, _Join_Data_5.`Email`, _Join_Data_5.`Seller Contact`, _Join_Data_5.`Phone`, _Join_Data_5.`Email Available?`, _Join_Data_5.`Address Available?`, _Join_Data_5.`buy_box_status`, _Join_Data_5.`buybox_status_date`, _Group_By_4.`vendor_code` AS `Vendor Code` FROM _Join_Data_5 LEFT JOIN _Group_By_4 ON _Join_Data_5.`upc` = _Group_By_4.`upc`
),

_Add_Formula_4 AS (
  SELECT `Brand`, `amazonID`, `First Seen Date`, `Last Seen Date`, `scraped_date`, `sellerId`, `sellerName`, `storefront_name`, `asin`, `isQuantityRestricted`, `isFBA`, `upc`, `upc_name`, `msrp`, `srp`, `map`, `parent_category`, `child_category`, `child_category_2`, `child_category_3`, `partner name`, `country_id`, `offer_price`, `offer_date_max_price`, `Units`, `Limit Buster Units`, `redirect_asin`, `created_date`, `created_time`, `sku_map`, `sku_name`, `buy_box_count`, `Partner - Brand`, `Date`, `Day of Week`, `Month`, `445 Week`, `445 Week Number`, `445 Month`, `445 Month Number`, `445 Calendar`, `445 Year`, `BBC_ORIGINAL_STATUS`, `BBC_2_8_22_STATUS`, `ASIN Link`, `Inventory Value`, `Offer Type`, `Price Δ (%) - map`, `Price Δ (€) - map`, `Authorized Sellers`, `MAP / MSRP Exceptions`, `MAP Violations (sku map)`, `Storefront DB URL`, `Storefront ID`, `Last Notice Type`, `Last Notice Sent`, `Notes`, `Invoice ID`, `Job ID`, `USPS Tracking`, `Delivery Status`, `Delivery Date`, `Enforcement History`, `C2M ERROR_STATUS`, `Recipient Address`, `Platform Sent?`, `New Storefront within 7 days`, `Days since first listing`, `Days since last listing`, `New Storefront within 2 days`, `New Storefront within 14 days`, `New Storefront within 28 days`, `internal_id`, `seller_id`, `name`, `last_scraped_at`, `address_line1`, `address_line2`, `review_count`, `review_count_last_30`, `_BATCH_ID_`, `_BATCH_LAST_RUN_`, `Address`, `Violator City`, `Violator State`, `Zip`, `Violator Country`, `Email`, `Seller Contact`, `Phone`, `Email Available?`, `Address Available?`, `buy_box_status`, `buybox_status_date`, `Vendor Code`, (CONCAT('<div><a href="https://www.google.it/search?tbm=shop&q=',`upc`,'&q=',`Brand`,'&q=',`upc_name`,'"','target="_blank">',`upc`,'</a></div>')) AS `UPC Search (Google)`, (CONCAT('<div><a href="https://www.amazon.it/sp?ie=UTF8&seller=',`sellerId`,'"',' target="_blank">',`sellerId`,'</a></div>') ) AS `Seller Profile` FROM _Add_Vendor_Code
),

_IT_Enforcement_DS AS (
  SELECT * FROM _Add_Formula_4
)

SELECT * FROM _IT_Enforcement_DS