#!/usr/bin/env python3
"""
Snowflake Schema to SQL View Generator

This script connects to a Snowflake database, inspects a specified schema,
and generates a SQL file for each table with an explicit SELECT statement.
The generated SQL sanitizes column names to be valid identifiers.
"""

import os
import sys
import logging
import re
from pathlib import Path
from dotenv import load_dotenv
from typing import List

# Add project root to path to import from tools
project_root = Path(__file__).parent
sys.path.insert(0, str(project_root))

from tools.utils.snowflake import SnowflakeHandler

# Load environment variables from .env file
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def sanitize_name(name: str, for_sql_identifier: bool = True) -> str:
    """
    Sanitizes a string to be a valid SQL identifier or a safe filename component.

    Args:
        name (str): The string to sanitize.
        for_sql_identifier (bool): If True, sanitizes for SQL (allows underscores).
                                   If False, sanitizes for filenames (alphanumeric only).

    Returns:
        str: The sanitized string.
    """
    # Replace spaces and common separators with underscores
    sanitized = re.sub(r'[ \-./&]+', '_', name)
    
    # Remove any characters that are not alphanumeric or underscore
    if for_sql_identifier:
        sanitized = re.sub(r'[^a-zA-Z0-9_]', '', sanitized)
    else: # for filenames
        sanitized = re.sub(r'[^a-zA-Z0-9]', '', sanitized)
        
    # Remove leading/trailing underscores
    sanitized = sanitized.strip('_')
    
    # Prepend with 'col_' if the name starts with a number
    if re.match(r'^\d', sanitized):
        sanitized = 'col_' + sanitized

    # Convert to lowercase
    return sanitized.lower()


def generate_sql_view_file(table_name: str, columns: List[str], output_dir: Path):
    """
    Generates and saves a SQL file for a given table.

    Args:
        table_name (str): The original name of the table.
        columns (List[str]): The list of original column names.
        output_dir (Path): The directory to save the SQL file.
    """
    try:
        # Sanitize table name for filename
        sanitized_table_name = sanitize_name(table_name, for_sql_identifier=False)
        filename = output_dir / f"stg_{sanitized_table_name}.sql"

        # Build the explicit SELECT statement with sanitized aliases
        select_clauses = []
        for col in columns:
            alias = sanitize_name(col, for_sql_identifier=True)
            # Quote original column name to handle special characters and spaces
            select_clauses.append(f'    "{col}" AS {alias}')
        
        select_statement = ",\n".join(select_clauses)
        
        # Get full qualified table name for the FROM clause
        db = os.getenv("SNOWFLAKE_DATABASE")
        schema = os.getenv("SNOWFLAKE_SCHEMA")
        qualified_table_name = f'"{db}"."{schema}"."{table_name}"'

        # Final SQL content
        sql_content = f"""
-- Staging model for {qualified_table_name}
-- Generated by generate_view_scripts.py

SELECT
{select_statement}
FROM {qualified_table_name}
"""
        # Write to file
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(sql_content)
        
        logger.info(f"✅ Generated SQL file: {filename}")
        
    except Exception as e:
        logger.error(f"❌ Failed to generate SQL for table {table_name}: {e}")


def main():
    """
    Main function to orchestrate the SQL generation process.
    """
    logger.info("🚀 Starting Snowflake SQL View Generator...")
    
    # Define and create output directory
    output_dir = Path("sql/stg")
    output_dir.mkdir(parents=True, exist_ok=True)
    logger.info(f"📁 Output directory set to: {output_dir.absolute()}")
    
    generated_count = 0
    failed_count = 0

    try:
        # Use the existing SnowflakeHandler for connection
        snowflake_handler = SnowflakeHandler()
        
        if not snowflake_handler.setup_connection():
            logger.error("❌ Could not connect to Snowflake. Please check credentials.")
            return 1

        try:
            db = os.getenv("SNOWFLAKE_DATABASE")
            schema = os.getenv("SNOWFLAKE_SCHEMA")
            
            logger.info(f"Fetching tables from schema: {schema}...")
            
            # Fetch tables
            tables_query = f"SHOW TABLES IN SCHEMA \"{db}\".\"{schema}\";"
            tables_df = snowflake_handler.execute_query(tables_query)
            
            if tables_df is None or len(tables_df) == 0:
                logger.warning("No tables found to process.")
                return 1
            
            table_names = tables_df['name'].tolist()
            logger.info(f"📊 Found {len(table_names)} tables.")

            for table in table_names:
                # Fetch columns for each table
                columns_query = f"DESCRIBE TABLE \"{db}\".\"{schema}\".\"{table}\";"
                columns_df = snowflake_handler.execute_query(columns_query)
                
                if columns_df is not None and len(columns_df) > 0:
                    columns = columns_df['name'].tolist()
                    generate_sql_view_file(table, columns, output_dir)
                    generated_count += 1
                else:
                    logger.error(f"❌ Failed to fetch columns for table {table}")
                    failed_count += 1
        
        finally:
            snowflake_handler.cleanup()
    
    except ValueError as e:
        logger.error(f"Configuration error: {e}")
        return 1
    except Exception as e:
        logger.error(f"An unexpected error occurred: {e}")
        return 1
    
    # Final summary
    logger.info("\n" + "="*50)
    logger.info("🎉 Generation Complete!")
    logger.info(f"   ✅ Successfully generated files: {generated_count}")
    logger.info(f"   ❌ Failed files: {failed_count}")
    logger.info("="*50)

    return 0


if __name__ == "__main__":
    sys.exit(main()) 