with
    source as (select * from {{ source("TEMP_ARGO_RAW", "OBSOLETE_ATLANTA_FIREFLY_DAILY_PRODUCTS_DIM") }})

select
    "AMZ Brand" as amz_brand,
    "AMZ CA Link" as amz_ca_link,
    "AMZ UK Link" as amz_uk_link,
    "AMZ US Link" as amz_us_link,
    "ASIN" as asin,
    "CA ASIN" as ca_asin,
    "Category 1" as category_1,
    "Category 2" as category_2,
    "Category 3" as category_3,
    "Expanded Units" as expanded_units,
    "Height" as height,
    "Length" as length,
    "ProductKey" as productkey,
    "RTI Link" as rti_link,
    "Receiving Case Qty" as receiving_case_qty,
    "Recom UPC Brand ID" as recom_upc_brand_id,
    "Recom UPC Brand Name" as recom_upc_brand_name,
    "Recom UPC Client ID" as recom_upc_client_id,
    "Recom UPC Client Name" as recom_upc_client_name,
    "Recom UPC ID" as recom_upc_id,
    "SKU" as sku,
    "SKU and Short Title" as sku_and_short_title,
    "Short Title" as short_title,
    "SubCategory 1" as subcategory_1,
    "SubCategory 2" as subcategory_2,
    "SubCategory 3" as subcategory_3,
    "Title" as title,
    "UK ASIN" as uk_asin,
    "UPC" as upc,
    "Vendor MPN" as vendor_mpn,
    "VendorKey" as vendorkey,
    "Weight" as weight,
    "Width" as width,
    "_BATCH_ID_" as _batch_id_,
    "_BATCH_LAST_RUN_" as _batch_last_run_

from source