with
    source as (select * from {{ source("TEMP_ARGO_RAW", "AMAZON_FULFILLMENTS") }})

select
    "amazon_customer_id" as amazon_customer_id,
    "amazon_order_id" as amazon_order_id,
    "amazon_order_item_id" as amazon_order_item_id,
    "amazon_seller_id" as amazon_seller_id,
    "asin" as asin,
    "buyer_email" as buyer_email,
    "buyer_name" as buyer_name,
    "buyer_phone_number" as buyer_phone_number,
    "carrier" as carrier,
    "currency" as currency,
    "estimated_arrival_date" as estimated_arrival_date,
    "expanded_units" as expanded_units,
    "feedback_request" as feedback_request,
    "fulfillment_center_id" as fulfillment_center_id,
    "fulfillment_channel" as fulfillment_channel,
    "gift_wrap_price" as gift_wrap_price,
    "gift_wrap_tax" as gift_wrap_tax,
    "id" as id,
    "is_business_order" as is_business_order,
    "item_price" as item_price,
    "item_promotion_discount" as item_promotion_discount,
    "item_status" as item_status,
    "item_tax" as item_tax,
    "last_updated_date" as last_updated_date,
    "merchant_order_id" as merchant_order_id,
    "merchant_order_item_id" as merchant_order_item_id,
    "number_of_items" as number_of_items,
    "old_product_id" as old_product_id,
    "order_channel" as order_channel,
    "order_status" as order_status,
    "payments_date" as payments_date,
    "postal_code_id" as postal_code_id,
    "price_designation" as price_designation,
    "product_id" as product_id,
    "product_name" as product_name,
    "promotion_ids" as promotion_ids,
    "purchase_date" as purchase_date,
    "purchase_order_number" as purchase_order_number,
    "quantity" as quantity,
    "quantity_shipped" as quantity_shipped,
    "recipient_name" as recipient_name,
    "reporting_date" as reporting_date,
    "sales_channel" as sales_channel,
    "selled_id" as selled_id,
    "ship_address_1" as ship_address_1,
    "ship_address_2" as ship_address_2,
    "ship_address_3" as ship_address_3,
    "ship_city" as ship_city,
    "ship_country" as ship_country,
    "ship_phone_number" as ship_phone_number,
    "ship_postal_code" as ship_postal_code,
    "ship_promotion_discount" as ship_promotion_discount,
    "ship_service_level" as ship_service_level,
    "ship_state" as ship_state,
    "shipment_date" as shipment_date,
    "shipment_id" as shipment_id,
    "shipment_item_id" as shipment_item_id,
    "shipping_price" as shipping_price,
    "shipping_tax" as shipping_tax,
    "sku" as sku,
    "tracking_number" as tracking_number,
    "url" as url,
    "Amazon Account Name" as amazon_account_name,
    "_BATCH_ID_" as _batch_id_,
    "_BATCH_LAST_RUN_" as _batch_last_run_

from source